# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 00:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnpj', models.CharField(default='', max_length=21)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reference',
        ),
    ]
