# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 02:04
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_photo',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], keep_meta=True, quality=100, size=[390, 200], upload_to='category'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='photo_medium',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], keep_meta=True, quality=90, size=[700, 510], upload_to='products_photos/medium'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='photo_thumb',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'left'], keep_meta=True, quality=75, size=[250, 250], upload_to='products_photos/thumb'),
        ),
    ]
