# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170610_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='user_photos',
        ),
    ]
