# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170701_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=144),
        ),
    ]
