# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 03:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20170701_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('absperm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.AbsPerm')),
                ('title', models.CharField(max_length=30)),
                ('category_photo', django_resized.forms.ResizedImageField(upload_to='category')),
                ('description', models.TextField(max_length=144)),
            ],
            bases=('core.absperm', models.Model),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='author',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='category',
        ),
        migrations.AddField(
            model_name='produto',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='category_product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.Category'),
            preserve_default=False,
        ),
    ]
