# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170610_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(default='', max_length=200),
        ),
    ]
