# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='image4',
        ),
    ]
