# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171027_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerfilUser',
            new_name='Profile',
        ),
    ]
