# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 00:25
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171027_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, default='/imagens/img/user.svg', keep_meta=True, quality=75, size=[200, 200], upload_to='user/profile', verbose_name='imagem'),
        ),
    ]
