# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171027_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='address',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='postal_code',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='state',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sexo',
            field=models.BooleanField(choices=[(0, 'Masculino'), (1, 'Feminino'), (2, 'Outro'), (3, 'Prefiro nao informar')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, default='/imagens/img/user.svg', keep_meta=True, quality=75, size=[160, 160], upload_to='user/profile', verbose_name='imagem'),
        ),
    ]
