# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='members',
        ),
    ]
