# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_store_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='adm',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=200),
        ),
    ]
