# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 00:23
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171101_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, default='/imagens/img/user.svg', keep_meta=True, quality=75, size=[400, 400], upload_to=''),
        ),
    ]
