# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171102_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighRatingProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
            ],
        ),
    ]
