# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20171218_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthy',
            field=models.DateField(default=0, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='/imagens/img/user.svg', keep_meta=True, quality=75, size=[160, 160], upload_to='user/profile', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
