# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20171219_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthy',
        ),
    ]
