# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20171219_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthy',
        ),
    ]
