# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_profile_birthy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='store',
            name='adm',
            field=models.CharField(blank=True, default=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL), max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='/imagens/img/user.svg', keep_meta=True, quality=75, size=[400, 400], upload_to=''),
        ),
    ]
