# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20171220_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.BooleanField(choices=[(0, 'Masculino'), (1, 'Feminino'), (2, 'Outro'), (3, 'Prefiro não informar')], default=0),
        ),
    ]
