# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20171222_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='administrative_area_level_1',
        ),
        migrations.AddField(
            model_name='address',
            name='administrative_area_level_2',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='route',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='sublocality_level_1',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
