# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20180123_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='street_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='administrative_area_level_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='administrative_area_level_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='route',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='sublocality_level_1',
            field=models.CharField(max_length=200),
        ),
    ]
