# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171102_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sizes',
            field=models.ManyToManyField(to='product.ProductSize', verbose_name='Tamanhos'),
        ),
    ]
