# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20171102_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Cometário', 'verbose_name_plural': 'Cometários'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'Tamanho de produto', 'verbose_name_plural': 'Tamanhos de produto'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=144, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=144, verbose_name='Cometário'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='product.Produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=0, verbose_name='Status entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Dinheiro'), (1, 'Cartão de debito'), (2, 'Cartão de crédito')], default=0, verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='product.Produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Predido realizado'), (1, 'Pedido visualizado'), (2, 'Em Andamento'), (3, 'Saiu para entrega'), (4, 'Entregue'), (5, 'Cancelado')], default=0, verbose_name='Andamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='photo_medium',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], help_text='600x600', keep_meta=True, quality=90, size=[700, 510], upload_to='products_photos/medium', verbose_name='Imagem Média'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='photo_thumb',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'left'], help_text='250x250', keep_meta=True, quality=75, size=[250, 250], upload_to='products_photos/thumb', verbose_name='Imagem Thumb'),
        ),
    ]
