# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20171220_2010'),
        ('product', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='core.Address', verbose_name='endereco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=0, verbose_name='entregue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Dinheiro'), (1, 'Cartão de debito'), (2, 'Cartão de crédito')], default=0, verbose_name='forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='product.Produto', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Predido realizado'), (1, 'Pedido visualizado'), (2, 'Em Andamento'), (3, 'Saiu para entrega'), (4, 'Entregue'), (5, 'Cancelado')], default=0, verbose_name='andamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.IntegerField(blank=True, default=0, verbose_name='valor'),
        ),
    ]
