# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20171221_2313'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_auto_20171220_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('absperm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.AbsPerm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pedido', to=settings.AUTH_USER_MODEL, verbose_name='usuario_pedido')),
            ],
            bases=('core.absperm', models.Model),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=144, verbose_name='cometário'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='product.Produto', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='core.Address', verbose_name='entregar em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Dinheiro'), (1, 'Cartão de débito'), (2, 'Cartão de crédito')], default=0, verbose_name='forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pedido realizado'), (1, 'Pedido visualizado'), (2, 'Em Andamento'), (3, 'Saiu para entrega'), (4, 'Entregue'), (5, 'Cancelado')], default=0, verbose_name='andamento'),
        ),
    ]
