# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20171221_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='value_cart',
            field=models.FloatField(default=0, verbose_name='valor do carrinho'),
        ),
    ]
