# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbussiness',
            old_name='nome',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='userbussiness',
            name='address',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbussiness',
            name='cnpj',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbussiness',
            name='lat',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbussiness',
            name='lng',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbussiness',
            name='phone',
            field=models.CharField(default=11, max_length=10),
            preserve_default=False,
        ),
    ]
