# abstractile
# Autogenerated from man page /usr/share/man/man6/abstractile.6x.gz
complete -c abstractile -o sleep --description 'Specify the number of seconds to sleep between screens (0-60).'
complete -c abstractile -o speed --description 'A value between 0 and 5 used to specify the speed at which each screen is dra…'
complete -c abstractile -o tile --description 'The type of tile that is drawn on each screen.'
complete -c abstractile -o fps --description 'Display the current frame rate and CPU load.'

