# aidl
# Autogenerated from man page /usr/share/man/man1/aidl.1.gz
complete -c aidl -o 'I<DIR>' --description 'Search path for import statements. RS . RE.'
complete -c aidl -o 'd<FILE>' --description 'Generate dependency file. RS . RE.'
complete -c aidl -s a --description 'Generate dependency file next to the output file with the name based on the i…'
complete -c aidl -o 'p<FILE>' --description 'File created by \\f[B]--preprocess\\f[] to import. RS . RE.'
complete -c aidl -o 'o<FOLDER>' --description 'Base output folder for generated files. RS . RE.'
complete -c aidl -s b --description 'Fail when trying to compile a parcelable. RS . RE.'

