# anemotaxis
# Autogenerated from man page /usr/share/man/man6/anemotaxis.6x.gz
complete -c anemotaxis -o visual --description 'Specify which visual to use.'
complete -c anemotaxis -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c anemotaxis -o root --description 'Draw on the root window.'
complete -c anemotaxis -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c anemotaxis -o distance --description 'Max initial distance to the source .   10 - 250.   Default: 40.'
complete -c anemotaxis -o sources --description 'Max number of sources.   Default: 25.'
complete -c anemotaxis -o searchers --description 'Max number of searchers.  Default: 25.'
complete -c anemotaxis -o fps --description 'Display the current frame rate and CPU load.'

