# anemone
# Autogenerated from man page /usr/share/man/man6/anemone.6x.gz
complete -c anemone -o visual --description 'Specify which visual to use.'
complete -c anemone -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c anemone -o root --description 'Draw on the root window.'
complete -c anemone -o delay --description 'Per-frame delay, in microseconds.   Default: 40000 (0. 04 seconds. ).'
complete -c anemone -o arms --description 'Arms.   2 - 500.   Default: 128.'
complete -c anemone -o finpoints --description 'Tentacles.   3 - 200.   Default: 64.'
complete -c anemone -o withdraw --description 'Frequency that the arms withdraw.'
complete -c anemone -o turnspeed --description 'How fast it turns.'
complete -c anemone -o width --description 'Thickness.   1 - 10.   Default: 2.'
complete -c anemone -o fps --description 'Display the current frame rate and CPU load.'

