# antinspect
# Autogenerated from man page /usr/share/man/man6/antinspect.6x.gz
complete -c antinspect -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c antinspect -o root --description 'Draw on the root window.'
complete -c antinspect -o install --description 'Install a private colormap for the window.'
complete -c antinspect -o shadows --description 'Draw shadows on ground.'
complete -c antinspect -o visual --description 'Specify which visual to use.'
complete -c antinspect -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

