# antmaze
# Autogenerated from man page /usr/share/man/man6/antmaze.6x.gz
complete -c antmaze -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c antmaze -o root --description 'Draw on the root window.'
complete -c antmaze -o install --description 'Install a private colormap for the window.'
complete -c antmaze -o visual --description 'Specify which visual to use.'
complete -c antmaze -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

