# apollonian
# Autogenerated from man page /usr/share/man/man6/apollonian.6x.gz
complete -c apollonian -o visual --description 'Specify which visual to use.'
complete -c apollonian -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c apollonian -o root --description 'Draw on the root window.'
complete -c apollonian -o label -o no-label --description 'Draw Labels.   Boolean.'
complete -c apollonian -o altgeom -o no-altgeom --description 'Include Alternate Geometries.   Boolean.'
complete -c apollonian -o cycles --description 'Depth. 	1 - 20.   Default: 20.'
complete -c apollonian -o ncolors --description 'Number of Colors.   Default: 64.'
complete -c apollonian -o delay --description 'Per-frame delay, in microseconds.   Default: 1000000 (1. 00 seconds. ).'
complete -c apollonian -o fps --description 'Display the current frame rate and CPU load.'

