# apt-clone
# Autogenerated from man page /usr/share/man/man8/apt-clone.8.gz
complete -c apt-clone -s h -l help --description 'show help message for apt-clone.'
complete -c apt-clone -l debug --description 'enable debug output .'

