# ar
# Autogenerated from man page /usr/share/man/man1/ar.1.gz
complete -c ar -l help --description 'Displays the list of command line options supported by ar and then exits.'
complete -c ar -l version --description 'Displays the version information of ar and then exits.'

