# archdetect
# Autogenerated from man page /usr/share/man/man1/archdetect.1.gz
complete -c archdetect -s g --description 'When bringing up new subarchitectures, archdetect may not yet have been taugh…'

