# assistant-qt4
# Autogenerated from man page /usr/share/man/man1/assistant-qt4.1.gz
complete -c assistant-qt4 -o collectionFile --description 'Uses the specified collection file instead of the default one.'
complete -c assistant-qt4 -o showUrl --description 'Shows the document with the url.'
complete -c assistant-qt4 -o enableRemoteControl --description 'Enables Assistant to be remotely controlled.'
complete -c assistant-qt4 -o show --description 'Shows the specified dockwidget which can be "contents", "index", "bookmarks" …'
complete -c assistant-qt4 -o activate --description 'Activates the specified dockwidget which can be "contents", "index", "bookmar…'
complete -c assistant-qt4 -o hide --description 'Hides the specified dockwidget which can be "contents", "index" "bookmarks" o…'
complete -c assistant-qt4 -o register --description 'Registers the specified help file (. qch) in the given collection file.'
complete -c assistant-qt4 -o unregister --description 'Unregisters the specified help file (. qch) from the give collection file.'
complete -c assistant-qt4 -o setCurrentFilter --description 'Set the filter as the active filter.'
complete -c assistant-qt4 -o quiet --description 'Does not display any error or status message.'
complete -c assistant-qt4 -o help --description 'Displays a help message.  SEE ALSO /usr/share/qt4/doc/html/assistant-manual.'

