# atlantis
# Autogenerated from man page /usr/share/man/man6/atlantis.6x.gz
complete -c atlantis -o visual --description 'Specify which visual to use.'
complete -c atlantis -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c atlantis -o root --description 'Draw on the root window.'
complete -c atlantis -o whalespeed --description 'Whale Speed.   0 - 1000.   Default: 250.'
complete -c atlantis -o cycles --description 'Shark Speed.   Default: 100.'
complete -c atlantis -o size --description 'Shark Proximity.   100 - 10000. 	Default: 6000.'
complete -c atlantis -o count --description 'Number of Sharks.   0 - 20.   Default: 4.'
complete -c atlantis -o texture -o no-texture --description 'Whether to show shimmering water.'
complete -c atlantis -o gradient --description 'Whether to draw a gradient on the background, making it darker at the bottom.'
complete -c atlantis -o wireframe --description 'Render in wireframe instead of solid.'
complete -c atlantis -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

