# atunnel
# Autogenerated from man page /usr/share/man/man6/atunnel.6x.gz
complete -c atunnel -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c atunnel -o root --description 'Draw on the root window.'
complete -c atunnel -o install --description 'Install a private colormap for the window.'
complete -c atunnel -o visual --description 'Specify which visual to use.'
complete -c atunnel -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c atunnel -o texture --description 'Show a textured tunnel.  This is the default.'
complete -c atunnel -o no-texture --description 'Disables texturing the animation.'
complete -c atunnel -o wire --description 'Draw a wireframe rendition of the tunnel.'

