# barcode
# Autogenerated from man page /usr/share/man/man6/barcode.6x.gz
complete -c barcode -o visual --description 'Specify which visual to use.'
complete -c barcode -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c barcode -o root --description 'Draw on the root window.'
complete -c barcode -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 02 seconds. ).'
complete -c barcode -o clock --description 'Instead of drawing a stream of barcodes, draw a barcode-based digital clock.'
complete -c barcode -o clock24 --description 'Same as -clock, but display 24-hour time instead of 12-hour time.'
complete -c barcode -o fps --description 'Display the current frame rate and CPU load.'

