# binaryring
# Autogenerated from man page /usr/share/man/man6/binaryring.6x.gz
complete -c binaryring -o fps --description 'Display the current frame rate and CPU load.'
complete -c binaryring -o install --description 'Install a private colormap for the window.'
complete -c binaryring -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c binaryring -o noinstall --description 'Don\'t install a private colormap for the window.'
complete -c binaryring -o root --description 'Draw on the root window.'
complete -c binaryring -o visual --description 'Specify which visual to use.'
complete -c binaryring -o window --description 'Draw on a newly-created window.  This is the default.'
complete -c binaryring -o window-id --description 'Specify which window id to use.'
complete -c binaryring -o color --description 'Particles have random generated colors that gradually change over time.'
complete -c binaryring -o no-color --description 'Use the original black and white visualization.'
complete -c binaryring -o growth-delay --description 'Delay in ms between growth cycles.'
complete -c binaryring -o particles-number --description 'The number of particles in the system.'
complete -c binaryring -o ring-radius --description 'The radius of the ring where the particles are born, in pixels.'

