# blaster
# Autogenerated from man page /usr/share/man/man6/blaster.6x.gz
complete -c blaster -o visual --description 'Specify which visual to use.'
complete -c blaster -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c blaster -o root --description 'Draw on the root window.'
complete -c blaster -o num_robots --description 'Robots.   2 - 50.   Default: 5.'
complete -c blaster -o num_lasers --description 'Lasers.   1 - 100.   Default: 3.'
complete -c blaster -o num_stars --description 'Stars. 	5 - 200.   Default: 50.'
complete -c blaster -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c blaster -o fps --description 'Display the current frame rate and CPU load.'

