# blinkbox
# Autogenerated from man page /usr/share/man/man6/blinkbox.6x.gz
complete -c blinkbox -o visual --description 'Specify which visual to use.'
complete -c blinkbox -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c blinkbox -o root --description 'Draw on the root window.'
complete -c blinkbox -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c blinkbox -o wireframe -o no-wireframe --description 'Render in wireframe instead of solid.'
complete -c blinkbox -o boxsize --description 'Sets the size of the colored boxes.  Should be between 1 and 8.  Default: 2.'
complete -c blinkbox -o dissolve -o no-dissolve --description 'Boxes shrink instead of just vanishing.'
complete -c blinkbox -o fade -o no-fade --description 'Boxes fade to transparency instead of just vanishing.'
complete -c blinkbox -o blur -o no-blur --description 'Enable or disable motion blur on the ball.   Default: blurry.'
complete -c blinkbox -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

