# blitspin
# Autogenerated from man page /usr/share/man/man6/blitspin.6x.gz
complete -c blitspin -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c blitspin -o root --description 'Draw on the root window.'
complete -c blitspin -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c blitspin -o install --description 'Install a private colormap for the window.'
complete -c blitspin -o visual --description 'Specify which visual to use.'
complete -c blitspin -o bitmap --description 'The file name of a bitmap to rotate.'
complete -c blitspin -o grab-screen --description 'If this option is specified, then the image which is spun will be grabbed fro…'
complete -c blitspin -o delay --description 'How long to delay between steps of the rotation process, in microseconds.'
complete -c blitspin -o duration --description 'How long to run before loading a new image.   Default 120 seconds.'
complete -c blitspin -o delay2 --description 'How long to delay between each 90-degree rotation, in microseconds.'
complete -c blitspin -o fps --description 'Display the current frame rate and CPU load.'

