# blocktube
# Autogenerated from man page /usr/share/man/man6/blocktube.6x.gz
complete -c blocktube -o visual --description 'Specify which visual to use.'
complete -c blocktube -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c blocktube -o root --description 'Draw on the root window.'
complete -c blocktube -o delay --description 'Per-frame delay, in microseconds.   Default: 40000 (0. 04 seconds. ).'
complete -c blocktube -o holdtime --description 'How long to stay on the same color.   Default: 1000 frames.'
complete -c blocktube -o changetime --description 'How long it takes to fade to a new color.   Default: 200 frames.'
complete -c blocktube -o no-texture --description 'Draw solid blocks intstead of reflective blocks.'
complete -c blocktube -o no-fog --description 'Do not make blocks in the distance be darker.'
complete -c blocktube -o wireframe --description 'Only draw outlines.'
complete -c blocktube -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

