# boing
# Autogenerated from man page /usr/share/man/man6/boing.6x.gz
complete -c boing -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c boing -o root --description 'Draw on the root window.'
complete -c boing -o install --description 'Install a private colormap for the window.'
complete -c boing -o visual --description 'Specify which visual to use.'
complete -c boing -o delay --description 'The delay between frames of the animation, in microseconds: default 15000.'
complete -c boing -o smooth --description 'Draw a smooth sphere instead of a faceted polyhedron.'
complete -c boing -o lighting --description 'Do shaded lighting instead of flat colors.'
complete -c boing -o scanlines --description 'If the window is large enough, draw horizontal lines to simulate the scanline…'
complete -c boing -o speed --description 'Change the animation speed; 0. 5 to go half as fast, 2. 0 to go twice as fast.'
complete -c boing -o no-spin --description 'Don\'t rotate the ball.'
complete -c boing -o angle --description 'The jaunty angle at which the ball sits.   Default 15 degrees.'
complete -c boing -o size --description 'How big the ball is; default 0. 5 meaning about half the size of the window.'
complete -c boing -o parallels --description '-meridians n The pattern of rectangles on the ball.   Default 8x16.'
complete -c boing -o wireframe --description 'Look crummy.'
complete -c boing -o meridians --description 'The pattern of rectangles on the ball.   Default 8x16.'
complete -c boing -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

