# bouboule
# Autogenerated from man page /usr/share/man/man6/bouboule.6x.gz
complete -c bouboule -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c bouboule -o root --description 'Draw on the root window.'
complete -c bouboule -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c bouboule -o install --description 'Install a private colormap for the window.'
complete -c bouboule -o visual --description 'Specify which visual to use.'
complete -c bouboule -o ncolors --description 'How many colors should be used (if possible).   Default 64.'
complete -c bouboule -o 3d --description 'Do red/blue 3d separations (for 3d glasses. ).'
complete -c bouboule -o cycles --description '.'
complete -c bouboule -o count --description '.'
complete -c bouboule -o fps --description 'Display the current frame rate and CPU load.'

