# bouncingcow
# Autogenerated from man page /usr/share/man/man6/bouncingcow.6x.gz
complete -c bouncingcow -o visual --description 'Specify which visual to use.'
complete -c bouncingcow -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c bouncingcow -o root --description 'Draw on the root window.'
complete -c bouncingcow -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c bouncingcow -o speed --description 'How fast the cow bounces.   Larger for faster.   Default: 1. 0.'
complete -c bouncingcow -o count --description 'How many cows!  Default 1.'
complete -c bouncingcow -o texture --description 'An image file to paint on the cow\'s hide.'
complete -c bouncingcow -o wireframe --description 'Render in wireframe instead of solid.'
complete -c bouncingcow -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

