# boxed
# Autogenerated from man page /usr/share/man/man6/boxed.6x.gz
complete -c boxed -o visual --description 'Specify which visual to use.'
complete -c boxed -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c boxed -o root --description 'Draw on the root window.'
complete -c boxed -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c boxed -o wireframe --description 'Render in wireframe instead of solid.'
complete -c boxed -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

