# boxfit
# Autogenerated from man page /usr/share/man/man6/boxfit.6x.gz
complete -c boxfit -o visual --description 'Specify which visual to use.'
complete -c boxfit -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c boxfit -o root --description 'Draw on the root window.'
complete -c boxfit -o delay --description 'How much of a delay should be introduced between steps of the animation.'
complete -c boxfit -o count --description 'How many boxes or circles to animate simultaneously; default 50.'
complete -c boxfit -o growby --description 'How many pixels the objects should grow by, each frame.   Default 1.'
complete -c boxfit -o spacing --description 'How many pixels of space should be left between the objects.   Default 1.'
complete -c boxfit -o border --description 'Thickness of the colored border around each object.   Default 1.'
complete -c boxfit -o circles -o squares -o random --description 'Draw circles, squares, or choose randomly (the default).'
complete -c boxfit -o grab --description 'Normally it colors the boxes with a horizontal or vertical gradient.'
complete -c boxfit -o peek --description 'This option says to briefly show you the underlying image before beginning.'
complete -c boxfit -o fps --description 'Display the current frame rate and CPU load.'

