# btrfs-balance
# Autogenerated from man page /usr/share/man/man8/btrfs-balance.8.gz
complete -c btrfs-balance -s d --description '.'
complete -c btrfs-balance -s m --description '.'
complete -c btrfs-balance -s s --description '.'
complete -c btrfs-balance -s f --description 'FILTERS section for details about filters.'
complete -c btrfs-balance -s v --description '.'

