# btrfs-send
# Autogenerated from man page /usr/share/man/man8/btrfs-send.8.gz
complete -c btrfs-send -s v --description '.'
complete -c btrfs-send -s e --description '.'
complete -c btrfs-send -s p --description '.'
complete -c btrfs-send -s c --description '.'
complete -c btrfs-send -s f --description '.'
complete -c btrfs-send -l no-data --description '.'

