# btrfs-check
# Autogenerated from man page /usr/share/man/man8/btrfs-check.8.gz
complete -c btrfs-check -s s -l super --description 'use <superblock>th superblock copy, valid values are 0 up to 2 if the respect…'
complete -c btrfs-check -l repair --description 'try to repair the filesystem.'
complete -c btrfs-check -l init-csum-tree --description 'create a new CRC tree and recalculate all checksums.'
complete -c btrfs-check -l init-extent-tree --description 'create a new extent tree.'
complete -c btrfs-check -l check-data-csum --description 'verify checkums of data blocks.'
complete -c btrfs-check -s p -l progress --description 'indicate progress at various checking phases.'
complete -c btrfs-check -l qgroup-report --description 'verify qgroup accounting and compare against filesystem accounting.'
complete -c btrfs-check -l subvol-extents --description 'show extent state for a subvolume.'
complete -c btrfs-check -l tree-root --description 'use the given bytenr for the tree root.'

