# btrfs-restore
# Autogenerated from man page /usr/share/man/man8/btrfs-restore.8.gz
complete -c btrfs-restore -s s -l snapshots --description 'get snapshots, btrfs restore skips snapshots in default.'
complete -c btrfs-restore -s x -l xattr --description 'get extended attributes.'
complete -c btrfs-restore -s m -l metadata --description 'restore owner, mode and times.'
complete -c btrfs-restore -s S -l symlinks --description 'restore symbolic links as well as normal files.'
complete -c btrfs-restore -s v -l verbose --description 'verbose.'
complete -c btrfs-restore -s i -l ignore-errors --description 'ignore errors.'
complete -c btrfs-restore -s o -l overwrite --description 'overwrite directories/files in <path>.'
complete -c btrfs-restore -s t --description 'use <bytenr> to read root tree.'
complete -c btrfs-restore -s f --description 'only restore files that are under specified root whose root bytenr is <bytenr…'
complete -c btrfs-restore -s u -l super --description 'use given superblock mirror identified by <mirror>, it can be 0,1,2.'
complete -c btrfs-restore -s r -l root --description 'only restore files that are under specified root whose objectid is <rootid>.'
complete -c btrfs-restore -s d --description 'find dir.'
complete -c btrfs-restore -s l -l list-roots --description 'list tree roots.'
complete -c btrfs-restore -s D -l dry-run --description 'dry run (only list files that would be recovered).'
complete -c btrfs-restore -l path-regex --description 'restore only filenames matching regex, you have to use following syntax (poss…'
complete -c btrfs-restore -s c --description 'ignore case (--path-regex only).'

