# btrfs-zero-log
# Autogenerated from man page /usr/share/man/man8/btrfs-zero-log.8.gz
complete -c btrfs-zero-log -s y --description '.'
complete -c btrfs-zero-log -s v --description '.'
complete -c btrfs-zero-log -s h --description '.'

