# btrfs-find-root
# Autogenerated from man page /usr/share/man/man8/btrfs-find-root.8.gz
complete -c btrfs-find-root -s a --description 'Search through all the metadata extents, even the root is already found.'
complete -c btrfs-find-root -s g --description 'Filter root tree by it\\(cqs original transaction id, tree root\\(cqs generatio…'
complete -c btrfs-find-root -s o --description 'Filter root tree by it\\(cqs objectid,tree root\\(cqs objectid in default.'
complete -c btrfs-find-root -s l --description 'Filter root tree by B-+ tree\\(cqs level, level 0 in default.'

