# btrfs-show-super
# Autogenerated from man page /usr/share/man/man8/btrfs-show-super.8.gz
complete -c btrfs-show-super -s f --description 'Print full superblock information.'
complete -c btrfs-show-super -s a --description 'Print information of all superblocks.'
complete -c btrfs-show-super -s i --description 'Specify which mirror to print out. sp <super_mirror> is between 0 and 2.'
complete -c btrfs-show-super -s F --description 'Attempt to print the superblock even if no superblock magic is found.'
complete -c btrfs-show-super -s s --description 'specifiy offset to a superblock in a non-standard location at bytenr, useful …'

