# btrfstune
# Autogenerated from man page /usr/share/man/man8/btrfstune.8.gz
complete -c btrfstune -s S --description 'Enable seeding on a given device.'
complete -c btrfstune -s r --description 'Enable extended inode refs (hardlink limit per file in a directory is 65536),…'
complete -c btrfstune -s x --description 'Enable skinny metadata extent refs (more efficient representation of extents)…'
complete -c btrfstune -s n --description 'Enable no-holes feature (more efficient representation of file holes), enable…'
complete -c btrfstune -s f --description 'Allow dangerous changes, e. g.  clear the seeding flag or change fsid.'
complete -c btrfstune -s u --description 'Change fsid to a randomly generated UUID or continue previous fsid change ope…'
complete -c btrfstune -s U --description 'Change fsid to UUID.'
complete -c btrfstune -o 'u.' --description 'Warning Cancelling or interrupting a UUID change operation will make the file…'

