# btrfs-device
# Autogenerated from man page /usr/share/man/man8/btrfs-device.8.gz
complete -c btrfs-device -s K -l nodiscard --description '.'
complete -c btrfs-device -s f -l force --description '.'
complete -c btrfs-device -l all-devices --description 'or.'
complete -c btrfs-device -s d --description 'is passed, all the devices under /dev are scanned.'
complete -c btrfs-device -s z --description '.'
complete -c btrfs-device -s b -l raw --description '.'
complete -c btrfs-device -s h -l human-readable --description '.'
complete -c btrfs-device -s H --description '.'
complete -c btrfs-device -l iec --description '.'
complete -c btrfs-device -l si --description '.'
complete -c btrfs-device -s k -l kbytes --description '.'
complete -c btrfs-device -s m -l mbytes --description '.'
complete -c btrfs-device -s g -l gbytes --description '.'
complete -c btrfs-device -s t -l tbytes --description '.'

