# btrfs-inspect-internal
# Autogenerated from man page /usr/share/man/man8/btrfs-inspect-internal.8.gz
complete -c btrfs-inspect-internal -s v --description '.'
complete -c btrfs-inspect-internal -s P --description '.'
complete -c btrfs-inspect-internal -s s --description '.'
complete -c btrfs-inspect-internal -l id --description '.'

