# btrfs-debug-tree
# Autogenerated from man page /usr/share/man/man8/btrfs-debug-tree.8.gz
complete -c btrfs-debug-tree -s e --description 'Print detailed extents info.'
complete -c btrfs-debug-tree -s d --description 'Print info of btrfs device and root tree dirs only.'
complete -c btrfs-debug-tree -s r --description 'Print info of roots only.'
complete -c btrfs-debug-tree -s b --description 'Print info of the specified block only.'

