# bubble3d
# Autogenerated from man page /usr/share/man/man6/bubble3d.6x.gz
complete -c bubble3d -o visual --description 'Specify which visual to use.'
complete -c bubble3d -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c bubble3d -o root --description 'Draw on the root window.'
complete -c bubble3d -o transparent --description 'Draw transparent bubbles instead of solid ones.'
complete -c bubble3d -o color --description 'Draw bubbles of the specified color.'
complete -c bubble3d -o delay --description 'Per-frame delay, in microseconds.   Default: 15000 (0. 015 seconds. ).'
complete -c bubble3d -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

