# bumps
# Autogenerated from man page /usr/share/man/man6/bumps.6x.gz
complete -c bumps -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c bumps -o root --description 'Draw on the root window.'
complete -c bumps -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c bumps -o install --description 'Install a private colormap for the window.'
complete -c bumps -o visual --description 'Specify which visual to use.'
complete -c bumps -o delay --description 'Slow it down.'
complete -c bumps -o duration --description 'How long to run before loading a new image.   Default 120 seconds.'
complete -c bumps -o fps --description 'Display the current frame rate and CPU load.'

