# cage
# Autogenerated from man page /usr/share/man/man6/cage.6x.gz
complete -c cage -o visual --description 'Specify which visual to use.'
complete -c cage -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c cage -o root --description 'Draw on the root window.'
complete -c cage -o delay --description 'Per-frame delay, in microseconds.   Default: 25000 (0. 03 seconds. ).'
complete -c cage -o mono --description 'Render solid instead of textured.'
complete -c cage -o wireframe --description 'Render in wireframe instead of textured.'
complete -c cage -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

