# carousel
# Autogenerated from man page /usr/share/man/man6/carousel.6x.gz
complete -c carousel -o visual --description 'Specify which visual to use.'
complete -c carousel -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c carousel -o root --description 'Draw on the root window.'
complete -c carousel -o count --description 'How many images to display.   Default 7.'
complete -c carousel -o zoom -o no-zoom --description 'Whether the images should move in and out (toward and away from the axis of r…'
complete -c carousel -o tilt -o no-tilt --description 'Whether the axis of rotation should tilt, and how.'
complete -c carousel -o titles -o no-titles --description 'Whether to display the file names of the images beneath them.   Default: yes.'
complete -c carousel -o font --description 'The font to use for titles.'
complete -c carousel -o duration --description 'Every duration seconds, one of the images will be replaced with a new one.'
complete -c carousel -o speed --description 'Speed up or slow down the animation.   0.'
complete -c carousel -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c carousel -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c carousel -o debug --description 'Prints debugging info to stderr.'
complete -c carousel -o wireframe --description 'Another debug mode.'

