# casper-snapshot
# Autogenerated from man page /usr/share/man/man1/casper-snapshot.1.gz
complete -c casper-snapshot -s c -l cow --description 'specifies the input directory to be cloned in the image file.'
complete -c casper-snapshot -s d -l device --description 'sets the device where the media which the snapshot/persistence file/partition…'
complete -c casper-snapshot -s e -l exclude-list --description 'a file containing a list of filenames/paths that should not be saved.'
complete -c casper-snapshot -s o -l output --description 'the filename/label used for the output file/partition.'
complete -c casper-snapshot -s r -l resync-string --description 'internally used on resyncs.'
complete -c casper-snapshot -s t -l type --description 'Type could be one of "cpio", "squashfs" or "ext2".'

