# ccurve
# Autogenerated from man page /usr/share/man/man6/ccurve.6x.gz
complete -c ccurve -o visual --description 'Specify which visual to use.'
complete -c ccurve -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c ccurve -o root --description 'Draw on the root window.'
complete -c ccurve -o delay --description 'Delay. 	0 - 60.   Default: 1.'
complete -c ccurve -o pause --description 'Duration.   1 - 60.   Default: 3.'
complete -c ccurve -o limit --description 'Density.   3 - 300000.   Default: 200000.'
complete -c ccurve -o fps --description 'Display the current frame rate and CPU load.'

