# celtic
# Autogenerated from man page /usr/share/man/man6/celtic.6x.gz
complete -c celtic -o visual --description 'Specify which visual to use.'
complete -c celtic -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c celtic -o root --description 'Draw on the root window.'
complete -c celtic -o delay --description 'Per-frame delay, in microseconds.   Default: 10000.'
complete -c celtic -o delay2 --description 'Delay between patterns, in seconds.   Default: 5.'
complete -c celtic -o ncolors --description 'Number of colours to use.  Default: 20.'
complete -c celtic -o graph --description 'Whether to render the underlying graph.   Default: no.'
complete -c celtic -o fps --description 'Display the current frame rate and CPU load.'

