# cgmanager
# Autogenerated from man page /usr/share/man/man8/cgmanager.8.gz
complete -c cgmanager -l max-depth --description 'Maximum cgroup depth.'
complete -c cgmanager -s M -l skip --description 'Subsystems to not mount.'
complete -c cgmanager -s m -l mount --description 'Extra subsystems to mount.'
complete -c cgmanager -l daemon --description 'Detach and run in the background.'
complete -c cgmanager -l sigstop --description 'Raise SIGSTOP when ready.'
complete -c cgmanager -s q -l quiet --description 'reduce output to errors only.'
complete -c cgmanager -s v -l verbose --description 'increase output to include informational messages.'
complete -c cgmanager -l help --description 'display this help and exit.'
complete -c cgmanager -l version --description 'output version information and exit.'

