# cgproxy
# Autogenerated from man page /usr/share/man/man8/cgproxy.8.gz
complete -c cgproxy -l daemon --description 'Detach and run in the background.'
complete -c cgproxy -l sigstop --description 'Raise SIGSTOP when ready.'
complete -c cgproxy -l check-master --description 'Check whether cgmanager is running.'
complete -c cgproxy -s q -l quiet --description 'reduce output to errors only.'
complete -c cgproxy -s v -l verbose --description 'increase output to include informational messages.'
complete -c cgproxy -l help --description 'display this help and exit.'
complete -c cgproxy -l version --description 'output version information and exit.'

