# cifs
# Autogenerated from man page /usr/share/man/man8/cifs.upcall.8.gz
complete -c cifs -s c --description 'This option is deprecated and is currently ignored.'
complete -c cifs -l krb5conf -s k --description 'This option allows administrators to set an alternate location for the krb5.'
complete -c cifs -l keytab -s K --description 'This option allows administrators to specify a keytab file to be used.'
complete -c cifs -l trust-dns --description 'With krb5 upcalls, the name used as the host portion of the service principal…'
complete -c cifs -l legacy-uid -s l --description 'Traditionally, the kernel has sent only a single uid= parameter to the upcall…'

