# cinnamon-settings-daemon
# Autogenerated from man page /usr/share/man/man1/cinnamon-settings-daemon.1.gz
complete -c cinnamon-settings-daemon -s '?' -l help --description 'Show this help message . PP Application options.'
complete -c cinnamon-settings-daemon -l debug --description 'Enable debugging code.'
complete -c cinnamon-settings-daemon -l no-daemon --description 'Do not detach the daemon process from its controlling terminal.'
complete -c cinnamon-settings-daemon -l gconf-prefix --description 'Specify a custom GConf settings prefix for settings manager plugins.'
complete -c cinnamon-settings-daemon -l display --description 'X display to use.'

