# cinnamon2d
# Autogenerated from man page /usr/share/man/man1/cinnamon2d.1.gz
complete -c cinnamon2d -l replace --description 'Replace the running window manager . br.'
complete -c cinnamon2d -l sm-disable --description 'Disable connection to the session manager . br.'
complete -c cinnamon2d -l sm-client-id --description 'Specify session management ID . br.'
complete -c cinnamon2d -l sm-save-file --description 'Initialize session from savefile . br.'
complete -c cinnamon2d -l screen --description 'X screen to use . br.'
complete -c cinnamon2d -s d -l display --description 'X display to use . br.'
complete -c cinnamon2d -l sync --description 'Make X calls synchronous . br.'
complete -c cinnamon2d -l version --description 'Print version and exit . br.'
complete -c cinnamon2d -l help --description 'Display help and exit.'

