# circuit
# Autogenerated from man page /usr/share/man/man6/circuit.6x.gz
complete -c circuit -o visual --description 'Specify which visual to use.'
complete -c circuit -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c circuit -o root --description 'Draw on the root window.'
complete -c circuit -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c circuit -o parts --description 'Number of parts.   Default: 10.'
complete -c circuit -o spin -o no-spin --description 'Whether the objects should spin.'
complete -c circuit -o rotate -o no-rotate --description 'Whether the scene should spin.'
complete -c circuit -o speed --description 'Rotation speed, 0 - 100.   Default: 1.'
complete -c circuit -o light -o no-light --description 'Whether to us lighting, or flat coloring.'
complete -c circuit -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

