# cityflow
# Autogenerated from man page /usr/share/man/man6/cityflow.6x.gz
complete -c cityflow -o visual --description 'Specify which visual to use.'
complete -c cityflow -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c cityflow -o root --description 'Draw on the root window.'
complete -c cityflow -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds).'
complete -c cityflow -o count --description 'Boxes. 	50 - 4000.   Default: 800.'
complete -c cityflow -o wave-speed --description 'Wave speed.   5 - 150.   Default: 25.'
complete -c cityflow -o wave-radius --description 'Wave overlap.   5 - 512.   Default: 256.'
complete -c cityflow -o waves --description 'Wave complexity.   1 - 20.   Default: 6.'
complete -c cityflow -o skew --description 'Skew.   0 - 45. 	Default: 12.'
complete -c cityflow -o wireframe -o no-wireframe --description 'Render in wireframe instead of solid.'
complete -c cityflow -o fps -o no-fps --description 'Whether to show a frames-per-second display at the bottom of the screen.'

