# cli-gacutil
# Autogenerated from man page /usr/share/man/man1/cli-gacutil.1.gz
complete -c cli-gacutil -o package --description '.'
complete -c cli-gacutil -s i -o root -o gacdir --description '.'
complete -c cli-gacutil -s l --description '.'
complete -c cli-gacutil -s u --description '.'
complete -c cli-gacutil -o us --description 'Uninstalls an assembly using the specified assembly\'s full name.'
complete -c cli-gacutil -o ul --description 'Uninstalls one or more assemblies from the global assembly cache.'

