# cloudlife
# Autogenerated from man page /usr/share/man/man6/cloudlife.6x.gz
complete -c cloudlife -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c cloudlife -o root --description 'Draw on the root window.'
complete -c cloudlife -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c cloudlife -o install --description 'Install a private colormap for the window.'
complete -c cloudlife -o visual --description 'Specify which visual to use.'
complete -c cloudlife -o cycle-delay --description 'Time in microseconds to sleep between ticks.   Default 25000.'
complete -c cloudlife -o cycle-colors --description 'How many ticks should elapse between cycling colors.'
complete -c cloudlife -o ncolors --description 'How many colors should be used (if possible).   Default 64.'
complete -c cloudlife -o cell-size --description 'Size of each cell, in powers of 2.   Default 3 (8-pixel cells).'
complete -c cloudlife -o initial-density --description 'Percentage of cells that are alive at start and when the field is repopulated.'
complete -c cloudlife -o max-age --description 'Maximum age for a cell.   Default 64.'
complete -c cloudlife -o fps --description 'Display the current frame rate and CPU load.'

