# combinediff
# Autogenerated from man page /usr/share/man/man1/combinediff.1.gz
complete -c combinediff -s p -l strip-match --description 'When comparing filenames, ignore the first n pathname components from both pa…'
complete -c combinediff -s q -l quiet --description 'Quieter output.'
complete -c combinediff -s U -l unified --description 'Attempt to display n lines of context (requires at least n lines of context i…'
complete -c combinediff -s d -l drop-context --description 'Don\\*(Aqt display any context on files that match the shell wildcard pattern.'
complete -c combinediff -s i -l ignore-case --description 'Consider upper- and lower-case to be the same.'
complete -c combinediff -s w -l ignore-all-space --description 'Ignore whitespace changes in patches.'
complete -c combinediff -s b -l ignore-space-change --description 'Ignore changes in the amount of whitespace.'
complete -c combinediff -s B -l ignore-blank-lines --description 'Ignore changes whose lines are all blank.'
complete -c combinediff -s z -l decompress --description 'Decompress files with extensions . gz and . bz2.'
complete -c combinediff -l interpolate --description 'Run as \\(lqinterdiff\\(rq.'
complete -c combinediff -l combine --description 'Run as \\(lqcombinediff\\(rq.  This is the default.'
complete -c combinediff -l help --description 'Display a short usage message.'
complete -c combinediff -l version --description 'Display the version number of combinediff.'

