# companioncube
# Autogenerated from man page /usr/share/man/man6/companioncube.6x.gz
complete -c companioncube -o visual --description 'Specify which visual to use.'
complete -c companioncube -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c companioncube -o root --description 'Draw on the root window.'
complete -c companioncube -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c companioncube -o speed --description 'How fast the animation should run.'
complete -c companioncube -o count --description 'How many cubes.   Default 3.'
complete -c companioncube -o spin --description '-no-spin Instead of bouncing, float and spin.'
complete -c companioncube -o wander --description '-no-wander Instead of bouncing, float and drift.'
complete -c companioncube -o wireframe --description 'Render in wireframe instead of solid.'
complete -c companioncube -o no-spin --description 'Instead of bouncing, float and spin.'
complete -c companioncube -o no-wander --description 'Instead of bouncing, float and drift.'
complete -c companioncube -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

