# compass
# Autogenerated from man page /usr/share/man/man6/compass.6x.gz
complete -c compass -o visual --description 'Specify which visual to use.'
complete -c compass -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c compass -o root --description 'Draw on the root window.'
complete -c compass -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c compass -o db -o no-db --description 'Double Buffer. 	Boolean.'
complete -c compass -o fps --description 'Display the current frame rate and CPU load.'

