# conchftp
# Autogenerated from man page /usr/share/man/man1/conchftp.1.gz
complete -c conchftp -s B --description 'Specifies the default size of the buffer to use for sending and receiving.'
complete -c conchftp -s b --description 'File to read commands from, \'-\' for stdin.  (Default value: interactive/stdin.'
complete -c conchftp -s R --description 'Number of requests to make before waiting for a reply.'
complete -c conchftp -s s --description 'Subsystem/server program to connect to.'

