# cowthink
# Autogenerated from man page /usr/share/man/man6/cowthink.6.gz
complete -c cowthink -s n --description 'option.   If it is specified, the given message will not be word-wrapped.'
complete -c cowthink -s W --description 'specifies roughly where the message should be wrapped.'
complete -c cowthink -s b --description 'option initiates Borg mode; .'
complete -c cowthink -s d --description 'causes the cow to appear dead; .'
complete -c cowthink -s g --description 'invokes greedy mode;.'
complete -c cowthink -s p --description 'causes a state of paranoia to come over the cow;.'
complete -c cowthink -s s --description 'makes the cow appear thoroughly stoned;.'
complete -c cowthink -s t --description 'yields a tired cow;.'
complete -c cowthink -s w --description 'is somewhat the opposite of .'
complete -c cowthink -s y --description 'brings on the cow\'s youthful appearance.'
complete -c cowthink -s e --description 'option to select the appearance of the cow\'s eyes, in which case the first tw…'
complete -c cowthink -s T --description 'and tongue_string ; it must be two characters and does not appear by default.'
complete -c cowthink -s f --description 'option specifies a particular cow picture file (``cowfile\'\') to use.'
complete -c cowthink -s l --description 'switch.'

