# cpufreq-info
# Autogenerated from man page /usr/share/man/man1/cpufreq-info.1.gz
complete -c cpufreq-info -s c -l cpu --description '<CPU> number which information shall be determined about.'
complete -c cpufreq-info -s e -l debug --description 'Prints out debug information.'
complete -c cpufreq-info -s f -l freq --description 'Get frequency the CPU currently runs at, according to the cpufreq core.'
complete -c cpufreq-info -s w -l hwfreq --description 'Get frequency the CPU currently runs at, by reading it from hardware (only av…'
complete -c cpufreq-info -s l -l hwlimits --description 'Determine the minimum and maximum CPU frequency allowed.'
complete -c cpufreq-info -s d -l driver --description 'Determines the used cpufreq kernel driver.'
complete -c cpufreq-info -s p -l policy --description 'Gets the currently used cpufreq policy.'
complete -c cpufreq-info -s g -l governors --description 'Determines available cpufreq governors.'
complete -c cpufreq-info -s a -l related-cpus --description 'Determines which CPUs run at the same hardware frequency.'
complete -c cpufreq-info -l affected-cpus --description 'Determines which CPUs need to have their frequency coordinated by software.'
complete -c cpufreq-info -s s -l stats --description 'Shows cpufreq statistics if available.'
complete -c cpufreq-info -s y -l latency --description 'Determines the maximum latency on CPU frequency changes.'
complete -c cpufreq-info -s o -l proc --description 'Prints out information like provided by the /proc/cpufreq interface in 2. 4.'
complete -c cpufreq-info -s m -l human --description 'human-readable output for the -f, -w, -s and -y parameters.'

