# crackberg
# Autogenerated from man page /usr/share/man/man6/crackberg.6x.gz
complete -c crackberg -o root --description 'Draw on the root window.'
complete -c crackberg -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c crackberg -o install --description 'Install a private colormap for the window.'
complete -c crackberg -o visual --description 'Specify which visual to use.'
complete -c crackberg -o delay --description 'Delay between frames; default 20000 (1/50th of a second).'
complete -c crackberg -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c crackberg -o crack --description 'Use all possible methods to animate tile instantiation.'
complete -c crackberg -o boring --description 'Do not animate instatiation at all; use this to get standard landscape  gener…'
complete -c crackberg -o letterbox --description 'Drawable window region has a 16:9 aspect ratio, regardless of actual window s…'
complete -c crackberg -o lit --description 'Enable lighting.'
complete -c crackberg -o flat --description 'Flat shading (OpenGL will use one color per primitive, rather than interpolat…'
complete -c crackberg -o wire --description 'Wireframe.'
complete -c crackberg -o nowater --description 'Do not display \'water\' (forces negative values to zero, and selects a  differ…'
complete -c crackberg -o visibility --description 'Value in range [0. 2,1. 0] (default 0.'
complete -c crackberg -o color --description 'Selects color scheme.   Use with no or bogus argument for current list.'
complete -c crackberg -o nsubdivs --description 'Number of times to recursively subdivide each triangular tile.'

