# crystal
# Autogenerated from man page /usr/share/man/man6/crystal.6x.gz
complete -c crystal -o visual --description 'Specify which visual to use.'
complete -c crystal -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c crystal -o root --description 'Draw on the root window.'
complete -c crystal -o grid -o no-grid --description 'Whether to draw grid.'
complete -c crystal -o cell -o no-cell --description 'Whether to draw the cell.'
complete -c crystal -o centre -o no-centre --description 'Whether to center on screen.'
complete -c crystal -o nx --description 'Horizontal Symmetries. 	-10 - 10.   Default: -3.'
complete -c crystal -o ny --description 'Vertical Symmetries.   -10 - 10.   Default: -3.'
complete -c crystal -o count --description 'Count. 	-5000 - 5000.   Default: -500.'
complete -c crystal -o delay --description 'Per-frame delay, in microseconds.   Default: 60000 (0. 06 seconds. ).'
complete -c crystal -o ncolors --description 'Number of Colors.   Default: 100.'
complete -c crystal -o fps --description 'Display the current frame rate and CPU load.'

