# cubenetic
# Autogenerated from man page /usr/share/man/man6/cubenetic.6x.gz
complete -c cubenetic -o visual --description 'Specify which visual to use.'
complete -c cubenetic -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c cubenetic -o root --description 'Draw on the root window.'
complete -c cubenetic -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c cubenetic -o count --description 'How many boxes make up the object.   Default: 5.'
complete -c cubenetic -o wander -o no-wander --description 'Whether the object should wander around the screen.'
complete -c cubenetic -o spin --description 'Around which axes should the object spin?.'
complete -c cubenetic -o no-spin --description 'Don\'t spin.'
complete -c cubenetic -o wireframe --description 'Render in wireframe instead of solid.'
complete -c cubenetic -o texture -o no-texture --description 'Display Solid Colors.'
complete -c cubenetic -o wave-speed --description 'Surface Pattern Speed. 	5 - 150.   Default: 80.'
complete -c cubenetic -o wave-radius --description 'Surface Pattern Overlap.   5 - 600.   Default: 512.'
complete -c cubenetic -o waves --description 'Surface Pattern Complexity.   1 - 20.   Default: 3.'
complete -c cubenetic -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

