# cubestorm
# Autogenerated from man page /usr/share/man/man6/cubestorm.6x.gz
complete -c cubestorm -o visual --description 'Specify which visual to use.'
complete -c cubestorm -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c cubestorm -o root --description 'Draw on the root window.'
complete -c cubestorm -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c cubestorm -o speed --description 'Larger numbers mean run faster.   Default: 1. 0.'
complete -c cubestorm -o count --description 'Number of cubes.   Default 4.'
complete -c cubestorm -o thickness --description 'How thick the struts making up the cubes should be (0. 0-1. 0).   Default 0.'
complete -c cubestorm -o wander -o no-wander --description 'Whether the cubes should wander around the screen.'
complete -c cubestorm -o spin -o no-spin --description 'Whether the cubes should spin.'
complete -c cubestorm -o wireframe -o no-wireframe --description 'Render in wireframe instead of solid.'
complete -c cubestorm -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

