# cubicgrid
# Autogenerated from man page /usr/share/man/man6/cubicgrid.6x.gz
complete -c cubicgrid -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c cubicgrid -o root --description 'Draw on the root window.'
complete -c cubicgrid -o install --description 'Install a private colormap for the window.'
complete -c cubicgrid -o visual --description 'Specify which visual to use.'
complete -c cubicgrid -o delay --description 'How long to pause between frames.   Default is 20000, or 0. 02 second.'
complete -c cubicgrid -o mono --description 'Draw in black and white.   If not used, a fixed all-color scheme is chosen.'
complete -c cubicgrid -o speed --description 'The maximum speed of the rotation.'
complete -c cubicgrid -o zoom --description 'Size of the lattice.'
complete -c cubicgrid -o ticks --description 'The count of points drawn along every axis.   10 - 100.   The default is 30.'
complete -c cubicgrid -o bigdots --description 'Draw the points twice as big.'
complete -c cubicgrid -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

