# dangerball
# Autogenerated from man page /usr/share/man/man6/dangerball.6x.gz
complete -c dangerball -o visual --description 'Specify which visual to use.'
complete -c dangerball -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c dangerball -o root --description 'Draw on the root window.'
complete -c dangerball -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c dangerball -o speed --description 'Spike growth frequency.   0. 0 - 0. 25.   Default: 0. 05.'
complete -c dangerball -o count --description 'Number o spikes.   Default: 30.'
complete -c dangerball -o wander -o no-wander --description 'Whether the object should wander around the screen.'
complete -c dangerball -o spin -o no-spin --description 'Whether the object should spin.'
complete -c dangerball -o wireframe -o no-wireframe --description 'Render in wireframe instead of solid.'
complete -c dangerball -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

