# darktable-viewer
# Autogenerated from man page /usr/share/man/man1/darktable-viewer.1.gz
complete -c darktable-viewer -s h -l help --description 'Gives usage information and terminates.'
complete -c darktable-viewer -l version --description 'Gives copyright and version information and terminates.'
complete -c darktable-viewer -l random --description 'Displays images in random instead of the default sequential order.'
complete -c darktable-viewer -l repeat --description 'Continues the slideshow in an endless loop instead of terminating after the l…'

