# darktable
# Autogenerated from man page /usr/share/man/man1/darktable.1.gz
complete -c darktable -s d --description 'This option enables debug output to the terminal.'
complete -c darktable -l disable-opencl --description 'Prevent darktable from initializing the OpenCL subsystem.'
complete -c darktable -l library --description 'darktable keeps image information in an sqlite database for fast access.'
complete -c darktable -l datadir --description 'This option defines the directory where darktable finds its runtime data.'
complete -c darktable -l moduledir --description 'darktable has a modular structure and organizes its modules as shared librari…'
complete -c darktable -l tmpdir --description 'The place where darktable stores its temporary files.'
complete -c darktable -l configdir --description 'This option defines the directory where darktable stores the user specific co…'
complete -c darktable -l cachedir --description 'darktable keeps a cache of image thumbnails for fast image preview and of pre…'
complete -c darktable -l localedir --description 'The place where darktable finds its language specific text strings.'
complete -c darktable -l luacmd --description 'A string containing lua commands to execute after lua initialization.'
complete -c darktable -l conf --description 'darktable supports a rich set of configuration parameters which the user defi…'

