# darktable-generate-cache
# Autogenerated from man page /usr/share/man/man1/darktable-generate-cache.1.gz
complete -c darktable-generate-cache -s h -l help --description 'Gives usage information and terminates.'
complete -c darktable-generate-cache -l version --description 'Gives copyright and version information and terminates.'
complete -c darktable-generate-cache -s m -l max-mip --description 'darktable can handle and store thumbnails with up to eight different resoluti…'

