# dbconfig-generate-include
# Autogenerated from man page /usr/share/man/man1/dbconfig-generate-include.1.gz
complete -c dbconfig-generate-include -s f -l format --description 'use the given output format (default: sh).'
complete -c dbconfig-generate-include -s o -l options --description 'pass options specific to an output format in a semicolon separated list.'
complete -c dbconfig-generate-include -s a -l all --description 'include all information in output (default).'
complete -c dbconfig-generate-include -s d -l dbname --description 'include the dbname in the output.'
complete -c dbconfig-generate-include -s p -l dbpass --description 'include the dbpass in the output.'
complete -c dbconfig-generate-include -s s -l dbserver --description 'include the dbserver in the output.'
complete -c dbconfig-generate-include -s P -l dbport --description 'include the dbport in the output.'
complete -c dbconfig-generate-include -s u -l dbuser --description 'include the dbuser in the output.'
complete -c dbconfig-generate-include -s t -l dbtype --description 'include the dbtype in the output.'
complete -c dbconfig-generate-include -s C -l comment --description '"comment out" any unset variables, using a string appropriate comment string …'
complete -c dbconfig-generate-include -s O -l owner --description 'set the owner:group of the output file.'
complete -c dbconfig-generate-include -s m -l mode --description 'set the permissions on the output file.'
complete -c dbconfig-generate-include -s U -l ucf --description 'register the outputfile with ucf.'
complete -c dbconfig-generate-include -s h -l help --description 'display this helpful message.'
complete -c dbconfig-generate-include -s v -l version --description 'output the version and exit.'

