# dbconfig-load-include
# Autogenerated from man page /usr/share/man/man1/dbconfig-load-include.1.gz
complete -c dbconfig-load-include -s f -l format --description 'use the given output format (default: sh).'
complete -c dbconfig-load-include -s a -l all --description 'include all information in output (default).'
complete -c dbconfig-load-include -s d -l dbname --description 'include the dbname in the output.'
complete -c dbconfig-load-include -s p -l dbpass --description 'include the dbpass in the output.'
complete -c dbconfig-load-include -s s -l dbserver --description 'include the dbserver in the output.'
complete -c dbconfig-load-include -s P -l dbport --description 'include the dbport in the output.'
complete -c dbconfig-load-include -s u -l dbuser --description 'include the dbuser in the output.'
complete -c dbconfig-load-include -s t -l dbtype --description 'include the dbtype in the output.'
complete -c dbconfig-load-include -s h -l help --description 'display this helpful message.'
complete -c dbconfig-load-include -s v -l version --description 'output the version and exit  .'

