# decayscreen
# Autogenerated from man page /usr/share/man/man6/decayscreen.6x.gz
complete -c decayscreen -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c decayscreen -o root --description 'Draw on the root window.'
complete -c decayscreen -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c decayscreen -o install --description 'Install a private colormap for the window.'
complete -c decayscreen -o visual --description 'Specify which visual to use.'
complete -c decayscreen -o delay --description 'Slow it down.'
complete -c decayscreen -o duration --description 'How long to run before loading a new image.   Default 120 seconds.'
complete -c decayscreen -o mode --description 'The direction in which the image should tend to slide.'
complete -c decayscreen -o fps --description 'Display the current frame rate and CPU load.'

