# dehtmldiff
# Autogenerated from man page /usr/share/man/man1/dehtmldiff.1.gz
complete -c dehtmldiff -l help --description 'Display a short usage message.'
complete -c dehtmldiff -l version --description 'Display the version number of dehtmldiff.'
complete -c dehtmldiff -s l --description 'option when applying the patch, in order to ignore any whitespace differences…'

