# deluxe
# Autogenerated from man page /usr/share/man/man6/deluxe.6x.gz
complete -c deluxe -o visual --description 'Specify which visual to use.'
complete -c deluxe -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c deluxe -o root --description 'Draw on the root window.'
complete -c deluxe -o delay --description 'Per-frame delay, in microseconds.   Default: 5000 (0. 01 seconds. ).'
complete -c deluxe -o thickness --description 'Thickness of lines.   Default: 50.'
complete -c deluxe -o count --description 'Number of objects.   Default: 5.'
complete -c deluxe -o ncolors --description 'Number of colors.   Default: 20.'
complete -c deluxe -o transparent -o no-transparent --description 'Whether to use transparency.'
complete -c deluxe -o db -o no-db --description 'Whether to double buffer.'
complete -c deluxe -o fps --description 'Display the current frame rate and CPU load.'

