# demon
# Autogenerated from man page /usr/share/man/man6/demon.6x.gz
complete -c demon -o visual --description 'Specify which visual to use.'
complete -c demon -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c demon -o root --description 'Draw on the root window.'
complete -c demon -o count --description 'States.   0 - 20.   Default: 0.'
complete -c demon -o cycles --description 'Timeout.   0 - 800000.   Default: 1000.'
complete -c demon -o delay --description 'Per-frame delay, in microseconds.   Default: 50000 (0. 05 seconds. ).'
complete -c demon -o ncolors --description 'Number of Colors.   Default: 64.'
complete -c demon -o size --description 'Cell Size.   -20 - 20.   Default: -7.'
complete -c demon -o fps --description 'Display the current frame rate and CPU load.'

