# discrete
# Autogenerated from man page /usr/share/man/man6/discrete.6x.gz
complete -c discrete -o visual --description 'Specify which visual to use.'
complete -c discrete -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c discrete -o root --description 'Draw on the root window.'
complete -c discrete -o cycles --description 'Timeout.   100 - 10000. 	Default: 2500.'
complete -c discrete -o delay --description 'Per-frame delay, in microseconds.   Default: 1000 (0. 001 seconds. ).'
complete -c discrete -o ncolors --description 'Number of Colors.   Default: 100.'
complete -c discrete -o fps --description 'Display the current frame rate and CPU load.'

