# dmraid
# Autogenerated from man page /usr/share/man/man8/dmraid.8.gz
complete -c dmraid -s a -l activate --description 'Activates or deactivates all or particular software RAID set.'
complete -c dmraid -l 'block_devices}' --description 'List all or particular discovered block devices with their properties (size,…'
complete -c dmraid -s d -l 'debug]...' --description 'Enable debugging output.'
complete -c dmraid -s c -l 'display_columns][FIELD' --description 'Display properties of block devices, RAID sets and devices in column(s).'
complete -c dmraid -s f -l format --description 'Use metadata format handler(s) to discover RAID devices.'
complete -c dmraid -l 'help}' --description 'Display help text.'
complete -c dmraid -l 'ignorelocking}' --description 'Don\'t take out any locks.'
complete -c dmraid -l 'list_formats}' --description 'List all available metadata format handlers with their names and description…'
complete -c dmraid -l 'native_log}' --description 'Display metadata in native, vendor-specific format.'
complete -c dmraid -l 'partchar}' --description 'Use CHAR as the separator between the device name and the partition number.'
complete -c dmraid -l 'rebuild}' --description 'Rebuild raid array after a drive has failed and a new drive is added.'
complete -c dmraid -l 'remove}' --description 'Delete one or all existing software RAID devices from the metadata.'
complete -c dmraid -l 'create}' -l type -l size -l strip -l disk --description 'Delete one or all existing Configure a software RAID device  and store the co…'
complete -c dmraid -s S -s M --description '-S -M device-path  This command adds hot spare support for one or more RAID…'
complete -c dmraid -l 'raid_devices}' --description 'List all discovered RAID devices with format, RAID level, sectors used and d…'
complete -c dmraid -l separator --description 'Use SEPARATOR as a delimiter for all options taking or displaying lists.'
complete -c dmraid -o 's...' --description 'Display properties of RAID sets.'
complete -c dmraid -o 'l' --description 'for supported metadata formats).'
complete -c dmraid -o 'a' --description 'below).   OPTIONS.'
complete -c dmraid -o 'f' --description ', only RAID sets with such format(s) can be activated or deactivated.'
complete -c dmraid -o 'p' --description 'disables the activation of partitions on them, and.'
complete -c dmraid -o 'Z' --description 'will make dmraid tell the kernel to remove the partitions from the disks und…'
complete -c dmraid -o 'c' --description 'to display block device names only and.'
complete -c dmraid -o 'cc' --description 'for CSV column output of block device properties.  See description of.'
complete -c dmraid -o 'b:' --description '.'
complete -c dmraid -o 'r:' --description '.'
complete -c dmraid -o 's:' --description '.'
complete -c dmraid -l size: --description '.'
complete -c dmraid -l strip: --description '.'
complete -c dmraid -l disk: --description '.'
complete -c dmraid -o 'D' --description 'is added to.'
complete -c dmraid -o 'r' --description 'the RAID metadata gets dumped into a subdirectory named dmraid.'
complete -c dmraid -o 'E' --description 'is added to.'
complete -c dmraid -o 's' --description 'twice to display RAID subsets too.  Add.'
complete -c dmraid -o 'ccc' --description 'for inclusion of block devices in the listing.  Doesn\'t imply.'
complete -c dmraid -s s --description 'to show RAID subsets (implied for group sets, e. g.  isw).  Add.'
complete -c dmraid -o 'g' --description 'to include information about group RAID sets (as with Intel Software RAID) i…'
complete -c dmraid -l '->' --description '.'

