# dotlockfile
# Autogenerated from man page /usr/share/man/man1/dotlockfile.1.gz
complete -c dotlockfile -s l --description 'Create a lockfile if no preexisting valid lockfile is found, else wait and re…'
complete -c dotlockfile -s r --description 'The number of times  dotlockfile retries to acquire the lock if it failed the…'
complete -c dotlockfile -s u --description 'Remove a lockfile.'
complete -c dotlockfile -s t --description 'Touch an existing lockfile (update the timestamp).'
complete -c dotlockfile -s c --description 'For debugging only:  Check for the existence of a valid lockfile.'
complete -c dotlockfile -s p --description 'Write the  process-id of the calling process into the lockfile.'
complete -c dotlockfile -s m --description 'Lock or unlock the current users mailbox.'

