# dpkg-repack
# Autogenerated from man page /usr/share/man/man1/dpkg-repack.1.gz
complete -c dpkg-repack -l root --description 'Take package from filesystem rooted on dir.'
complete -c dpkg-repack -l arch --description 'Make the package be for a specific architecture.'
complete -c dpkg-repack -s d -l deb-option --description 'Pass option as build argument to dpkg-deb.'
complete -c dpkg-repack -l generate --description 'Generate a temporary directory suitable for building a package from, but do n…'

