# dpkg-statoverride
# Autogenerated from man page /usr/share/man/man1/dpkg-statoverride.1.gz
complete -c dpkg-statoverride -l admindir --description 'Change the directory of the dpkg database where the statoverride file is also…'
complete -c dpkg-statoverride -l force --description 'Force an action, even if a sanity check would otherwise prohibit it.'
complete -c dpkg-statoverride -l update --description 'Immediately try to change the path to the new owner and mode if it exists.'
complete -c dpkg-statoverride -l add --description 'Add an override for path.'
complete -c dpkg-statoverride -l remove --description 'Remove an override for path, the status of path is left unchanged by this com…'
complete -c dpkg-statoverride -l list --description 'List all overrides.'
complete -c dpkg-statoverride -l help --description 'Show the usage message and exit.'
complete -c dpkg-statoverride -l version --description 'Show the version and exit.'
complete -c dpkg-statoverride -l quiet --description 'Be less verbose about what we do.'

