# drift
# Autogenerated from man page /usr/share/man/man6/drift.6x.gz
complete -c drift -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c drift -o root --description 'Draw on the root window.'
complete -c drift -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c drift -o install --description 'Install a private colormap for the window.'
complete -c drift -o visual --description 'Specify which visual to use.'
complete -c drift -o ncolors --description 'How many colors should be used (if possible).   Default 200.'
complete -c drift -o no-grow --description 'Whether fractals should grow; otherwise, they are animated.'
complete -c drift -o no-liss --description 'Whether we should use lissajous figures to get points.'
complete -c drift -o count --description '.'
complete -c drift -o grow --description '.'
complete -c drift -o liss --description '.'
complete -c drift -o fps --description 'Display the current frame rate and CPU load.'

