# dumpkeys
# Autogenerated from man page /usr/share/man/man1/dumpkeys.1.gz
complete -c dumpkeys -s h -l help --description 'Prints the program\'s version number and a short usage message to the program\'…'
complete -c dumpkeys -s i -l short-info --description 'Prints some characteristics of the kernel\'s keyboard driver.'
complete -c dumpkeys -s l -l long-info --description 'This option instructs  dumpkeys to print a long information listing.'
complete -c dumpkeys -s n -l numeric --description 'This option causes  dumpkeys to by-pass the conversion of action code values …'
complete -c dumpkeys -s f -l full-table --description 'This makes  dumpkeys skip all the short-hand heuristics (see  keymaps (5)) an…'
complete -c dumpkeys -l funcs-only --description 'When this option is given,  dumpkeys prints only the function key string defi…'
complete -c dumpkeys -l keys-only --description 'When this option is given,  dumpkeys prints only the key bindings.'
complete -c dumpkeys -l compose-only --description 'When this option is given,  dumpkeys prints only the compose key combinations.'
complete -c dumpkeys -s c -l charset --description 'This instructs dumpkeys to interpret character code values according to the s…'

