# endgame
# Autogenerated from man page /usr/share/man/man6/endgame.6x.gz
complete -c endgame -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c endgame -o root --description 'Draw on the root window.'
complete -c endgame -o install --description 'Install a private colormap for the window.'
complete -c endgame -o shadows --description 'Project pieces against the board with dark blend.'
complete -c endgame -o reflections --description 'Reflect pieces in light board squares.'
complete -c endgame -o classic --description 'Use the original low-polygon piece models.'
complete -c endgame -o visual --description 'Specify which visual to use.'
complete -c endgame -o wireframe --description 'Render in wireframe instead of solid.'
complete -c endgame -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

