# engine
# Autogenerated from man page /usr/share/man/man6/engine.6x.gz
complete -c engine -o visual --description 'Specify which visual to use.'
complete -c engine -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c engine -o root --description 'Draw on the root window.'
complete -c engine -o engine --description 'What kind of engine to draw.   Default: random.'
complete -c engine -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c engine -o move -o no-move --description 'Whether the object should wander around the screen.'
complete -c engine -o spin -o no-spin --description 'Whether the object should spin.'
complete -c engine -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c engine -o title -o no-title --description 'Whether to display the name of the engine being rendered.'

