# espdiff
# Autogenerated from man page /usr/share/man/man6/espdiff.6.gz
complete -c espdiff -l deep-brainwave-mode --description 'Probes your brain deeply in a manner that takes longer, but produces better e…'
complete -c espdiff -l recurse --description 'Recurses neural pathways throughout all parts of the brain, in some cases det…'
complete -c espdiff -l compare --description 'Allows the program to scan the current directory examining existing patches t…'
complete -c espdiff -l help --description 'Display a short usage message.'
complete -c espdiff -l version --description 'Display the version number of espdiff.'

