# euler2d
# Autogenerated from man page /usr/share/man/man6/euler2d.6x.gz
complete -c euler2d -o visual --description 'Specify which visual to use.'
complete -c euler2d -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c euler2d -o root --description 'Draw on the root window.'
complete -c euler2d -o count --description 'Particles.   2 - 5000.   Default: 1024.'
complete -c euler2d -o eulertail --description 'Trail Length.   2 - 500.   Default: 10.'
complete -c euler2d -o cycles --description 'Duration.   100 - 5000. 	Default: 3000.'
complete -c euler2d -o ncolors --description 'Number of Colors.   Default: 64.'
complete -c euler2d -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c euler2d -o fps --description 'Display the current frame rate and CPU load.'

