# extcheck
# Autogenerated from man page /usr/share/man/man1/extcheck.1.gz
complete -c extcheck -o verbose --description 'br Lists JAR files in the extension directory as they are checked.'
complete -c extcheck -o Joption --description '.'

