# extrusion
# Autogenerated from man page /usr/share/man/man6/extrusion.6x.gz
complete -c extrusion -o visual --description 'Specify which visual to use.'
complete -c extrusion -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c extrusion -o root --description 'Draw on the root window.'
complete -c extrusion -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c extrusion -o name --description 'Which object to draw.'
complete -c extrusion -o light -o no-light --description 'Whether to light the scene, or use flat coloring.'
complete -c extrusion -o bitmap --description 'The texture map to use.'
complete -c extrusion -o wireframe --description 'Render in wireframe instead of solid.'
complete -c extrusion -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

