# fadeplot
# Autogenerated from man page /usr/share/man/man6/fadeplot.6x.gz
complete -c fadeplot -o visual --description 'Specify which visual to use.'
complete -c fadeplot -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c fadeplot -o root --description 'Draw on the root window.'
complete -c fadeplot -o count --description 'Count. 	0 - 20.   Default: 10.'
complete -c fadeplot -o cycles --description 'How many frames until the shape changes.   Default: 1500.'
complete -c fadeplot -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c fadeplot -o ncolors --description 'Number of colors.   Default: 64.'
complete -c fadeplot -o fps --description 'Display the current frame rate and CPU load.'

