# file-rename
# Autogenerated from man page /usr/share/man/man1/file-rename.1p.gz
complete -c file-rename -s v -o verbose --description 'Verbose: print names of files successfully renamed.'
complete -c file-rename -s n -o nono --description 'No action: print names of files to be renamed, but don\'t rename.'
complete -c file-rename -s f -o force --description 'Over write: allow existing files to be over-written.'
complete -c file-rename -s h -o help --description 'Help: print \\s-1SYNOPSIS\\s0 and \\s-1OPTIONS. \\s0.'
complete -c file-rename -s m -o man --description 'Manual: print manual page.'
complete -c file-rename -s V -o version --description 'Version: show version number.'
complete -c file-rename -s e --description 'Expression: code to act on files name.'

