# flame
# Autogenerated from man page /usr/share/man/man6/flame.6x.gz
complete -c flame -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c flame -o root --description 'Draw on the root window.'
complete -c flame -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c flame -o install --description 'Install a private colormap for the window.'
complete -c flame -o visual --description 'Specify which visual to use.'
complete -c flame -o colors --description 'How many colors should be used (if possible).   Default 64.'
complete -c flame -o iterations --description 'How many fractals to generate.   Default 25.'
complete -c flame -o points --description 'How many pixels to draw for each fractal.   Default 10000.'
complete -c flame -o delay --description 'How long we should wait between drawing each fractal.'
complete -c flame -o delay2 --description 'How long we should wait before clearing the screen when each run ends.'
complete -c flame -o fps --description 'Display the current frame rate and CPU load.'

