# flipscreen3d
# Autogenerated from man page /usr/share/man/man6/flipscreen3d.6x.gz
complete -c flipscreen3d -o visual --description 'Specify which visual to use.'
complete -c flipscreen3d -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c flipscreen3d -o root --description 'Draw on the root window.'
complete -c flipscreen3d -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c flipscreen3d -o rotate -o no-rotate --description 'Whether to rotate.'
complete -c flipscreen3d -o wireframe --description 'Just render boxes instead of textures (for debugging).'
complete -c flipscreen3d -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

