# flipflop
# Autogenerated from man page /usr/share/man/man6/flipflop.6x.gz
complete -c flipflop -o visual --description 'Specify which visual to use.'
complete -c flipflop -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c flipflop -o root --description 'Draw on the root window.'
complete -c flipflop -o count --description 'Number of tiles on the board.  A value of "0" means "default".'
complete -c flipflop -o free --description 'Number of tiles missing from the board.  See -count.'
complete -c flipflop -o size --description 'Number of tiles on each side of the board.'
complete -c flipflop -o size-x --description 'Width (in tiles) of the board.  Default: 9.'
complete -c flipflop -o size-y --description 'Length (in tiles) of the board.  Default: 9.'
complete -c flipflop -o spin --description 'Angular velocity for the rotation of the board.'
complete -c flipflop -o mode --description 'Draw hopping sticks instead of flipping tiles.'
complete -c flipflop -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c flipflop -o fps -o no-fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c flipflop -o wireframe --description 'Only draw outlines.'
complete -c flipflop -o 'size-y.' --description '.'
complete -c flipflop -o texture -o no-texture --description 'Whether to texture the tiles with a screen grab or an image.'

