# fliptext
# Autogenerated from man page /usr/share/man/man6/fliptext.6x.gz
complete -c fliptext -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c fliptext -o root --description 'Draw on the root window.'
complete -c fliptext -o install --description 'Install a private colormap for the window.'
complete -c fliptext -o visual --description 'Specify which visual to use.'
complete -c fliptext -o program --description 'This program will be run periodically, and its output will be the text that i…'
complete -c fliptext -o size --description 'How large a font to use, in points.'
complete -c fliptext -o columns --description 'At (approximately) what column to wrap lines.   Default 80.'
complete -c fliptext -o left -o center -o right --description 'Whether to align the text flush left, centered, or flush right.'
complete -c fliptext -o lines --description 'How many lines of text should be shown at once.   Default 8.'
complete -c fliptext -o speed --description 'Change the animation speed; 0. 5 to go half as fast, 2. 0 to go twice as fast.'
complete -c fliptext -o delay --description 'The delay between frames of the animation; default is 10000 (1/10th second. ).'
complete -c fliptext -o font --description 'The name of the font to use.'
complete -c fliptext -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

