# fluidballs
# Autogenerated from man page /usr/share/man/man6/fluidballs.6x.gz
complete -c fluidballs -o visual --description 'Specify which visual to use.'
complete -c fluidballs -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c fluidballs -o root --description 'Draw on the root window.'
complete -c fluidballs -o count --description 'How many balls to display.   Default: 300.'
complete -c fluidballs -o size --description 'Maximum size of each ball.   Default: 25.'
complete -c fluidballs -o gravity --description 'Coefficient of gravity.   Useful values are < 0. 1.   Default: 0. 01.'
complete -c fluidballs -o wind --description 'Wind.   Useful values are < 0. 1.   Default: 0. 00.'
complete -c fluidballs -o elasticity --description 'Coefficient of elasticity.   Useful values are 0. 2 to 1. 0.   Default: 0. 97.'
complete -c fluidballs -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c fluidballs -o nonrandom --description 'Make all balls be the same size.'
complete -c fluidballs -o no-nonrandom --description 'Make the balls be random sizes.   Default.'
complete -c fluidballs -o shake -o no-shake --description 'Whether to shake the box if the system seems to have settled down.'
complete -c fluidballs -o fps --description 'Display the current frame rate and CPU load.'

