# flyingtoasters
# Autogenerated from man page /usr/share/man/man6/flyingtoasters.6x.gz
complete -c flyingtoasters -o visual --description 'Specify which visual to use.'
complete -c flyingtoasters -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c flyingtoasters -o root --description 'Draw on the root window.'
complete -c flyingtoasters -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c flyingtoasters -o speed --description 'How fast the toasters fly.   Larger for faster.   Default: 1. 0.'
complete -c flyingtoasters -o ntoasters --description 'How many toasters to draw.   Default 20.'
complete -c flyingtoasters -o nslices --description 'How many slices of toast to draw.   Default 25.'
complete -c flyingtoasters -o no-texture --description 'Turn off texture mapping (for slow machines. ).'
complete -c flyingtoasters -o wireframe --description 'Render in wireframe instead of solid.'
complete -c flyingtoasters -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

