# fortune
# Autogenerated from man page /usr/share/man/man6/fortune.6.gz
complete -c fortune -s a --description 'Choose from all lists of maxims, both offensive and not.'
complete -c fortune -s c --description 'Show the cookie file from which the fortune came.'
complete -c fortune -s e --description 'Consider all fortune files to be of equal size (see discussion below on multi…'
complete -c fortune -s f --description 'Print out the list of files which would be searched, but don\'t print a fortun…'
complete -c fortune -s l --description 'Long dictums only.   See   -n on how ``long\'\' is defined in this sense.'
complete -c fortune -s m --description 'Print out all fortunes which match the basic regular expression R pattern .'
complete -c fortune -s n --description 'Set the longest fortune length (in characters) considered to be ``short\'\' (th…'
complete -c fortune -s o --description 'Choose only from potentially offensive aphorisms.'
complete -c fortune -s s --description 'Short apothegms only.   See  -n on which fortunes are considered ``short\'\'.'
complete -c fortune -s i --description 'Ignore case for  R -m patterns.'
complete -c fortune -s w --description 'Wait before termination for an amount of time calculated from the number of c…'
complete -c fortune -l 'H.' --description '.'
complete -c fortune -s u --description 'Don\'t translate UTF-8 fortunes to the locale when searching or translating.'

