# free
# Autogenerated from man page /usr/share/man/man1/free.1.gz
complete -c free -s b -l bytes --description 'Display the amount of memory in bytes.'
complete -c free -s k -l kilo --description 'Display the amount of memory in kilobytes.   This is the default.'
complete -c free -s m -l mega --description 'Display the amount of memory in megabytes.'
complete -c free -s g -l giga --description 'Display the amount of memory in gigabytes.'
complete -c free -l tera --description 'Display the amount of memory in terabytes.'
complete -c free -s h -l human --description 'Show all output fields automatically scaled to shortest three digit unit and …'
complete -c free -s w -l wide --description 'Switch to the wide mode.'
complete -c free -s c -l count --description 'Display the result  count times.   Requires the  -s option.'
complete -c free -s l -l lohi --description 'Show detailed low and high memory statistics.'
complete -c free -s s -l seconds --description 'Continuously display the result delay  seconds apart.'
complete -c free -l si --description 'Use power of 1000 not 1024.'
complete -c free -s t -l total --description 'Display a line showing the column totals.'
complete -c free -l help --description 'Print help.'
complete -c free -s V -l version --description 'Display version information.'

