# fwupdmgr
# Autogenerated from man page /usr/share/man/man1/fwupdmgr.1.gz
complete -c fwupdmgr -l help --description 'Show summary of options.'
complete -c fwupdmgr -l verbose --description 'Show extra debugging information.'
complete -c fwupdmgr -l allow-reinstall --description 'Allow re-installing existing firmware versions.'
complete -c fwupdmgr -l allow-older --description 'Allow downgrading firmware versions.'

