# fwupdate
# Autogenerated from man page /usr/share/man/man1/fwupdate.1.gz
complete -c fwupdate -s a -l apply --description 'Apply firmware updates.'
complete -c fwupdate -s l -l list --description 'List supported firmware updates.'
complete -c fwupdate -s s -l supported --description 'Query for firmware update support.'
complete -c fwupdate -s q -l quiet --description 'Work quietly . SS "Help options:".'
complete -c fwupdate -s '?' -l help --description 'Show this help message.'
complete -c fwupdate -l usage --description 'Display brief usage message.'

