# galaxy
# Autogenerated from man page /usr/share/man/man6/galaxy.6x.gz
complete -c galaxy -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c galaxy -o root --description 'Draw on the root window.'
complete -c galaxy -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c galaxy -o install --description 'Install a private colormap for the window.'
complete -c galaxy -o visual --description 'Specify which visual to use.'
complete -c galaxy -o ncolors --description 'How many colors should be used (if possible).   Default 64.'
complete -c galaxy -o cycles --description '.'
complete -c galaxy -o count --description '.'
complete -c galaxy -o size --description '.'
complete -c galaxy -o tracks --description '.'
complete -c galaxy -o no-tracks --description '.'
complete -c galaxy -o spin --description '.'
complete -c galaxy -o no-spin --description '.'
complete -c galaxy -o fps --description 'Display the current frame rate and CPU load.'

