# gdbus
# Autogenerated from man page /usr/share/man/man1/gdbus.1.gz
complete -c gdbus -l xml --description 'option is used, the returned introspection XML is printed, otherwise a parsed…'
complete -c gdbus -l recurse --description 'option can be used to introspect children (and their children and so on) and …'
complete -c gdbus -l only-properties --description 'option can be used to only print the interfaces with properties.  monitor.'

