# gdebi-gtk
# Autogenerated from man page /usr/share/man/man1/gdebi-gtk.1.gz
complete -c gdebi-gtk -s h -l help --description 'Show this help message and exit.'
complete -c gdebi-gtk -l n -l non-interactive --description 'Run non-interactive (dangerous!).'
complete -c gdebi-gtk -l auto-close --description 'Auto close when the install is finished.'
complete -c gdebi-gtk -l datadir --description 'Use alternative datadir.'
complete -c gdebi-gtk -s r -l remove --description 'Remove selected package.'

