# gdebi
# Autogenerated from man page /usr/share/man/man1/gdebi.1.gz
complete -c gdebi -l version --description 'Show program\'s version number and exit.'
complete -c gdebi -s h -l help --description 'Show this help message and exit.'
complete -c gdebi -l n -l non-interactive --description 'Run non-interactive (dangerous!).'
complete -c gdebi -l o -l option --description 'Set an APT configuration option.'
complete -c gdebi -l q -l quiet --description 'Do not show progress information.'
complete -c gdebi -l apt-line --description 'Simulate only and print a apt-get install compatible line to stderr.'
complete -c gdebi -l root --description 'Use alternative root dir.  EXAMPLES gdebi foo_1. 0_all. deb gdebi foo-1.'

