# gears
# Autogenerated from man page /usr/share/man/man6/gears.6x.gz
complete -c gears -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c gears -o root --description 'Draw on the root window.'
complete -c gears -o install --description 'Install a private colormap for the window.'
complete -c gears -o visual --description 'Specify which visual to use.'
complete -c gears -o delay --description 'The delay between frames of the animation, in microseconds.'
complete -c gears -o speed --description 'Larger numbers mean run faster.   Default: 1. 0.'
complete -c gears -o no-spin --description 'Don\'t rotate the object.'
complete -c gears -o no-wander --description 'Don\'t wander the object around the screen.'
complete -c gears -o count --description 'How many gears to draw.   Default: 0 for random.'
complete -c gears -o wireframe --description 'Render in wireframe instead of solid.'
complete -c gears -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

