# geodesic
# Autogenerated from man page /usr/share/man/man6/geodesic.6x.gz
complete -c geodesic -o visual --description 'Specify which visual to use.'
complete -c geodesic -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c geodesic -o root --description 'Draw on the root window.'
complete -c geodesic -o mode --description 'Face/edge display style.  Default mesh.'
complete -c geodesic -o wander -o no-wander --description 'Whether the object should wander around the screen.'
complete -c geodesic -o spin -o no-spin --description 'Whether the object should spin.'
complete -c geodesic -o fps -o no-fps --description 'Whether to show a frames-per-second display at the bottom of the screen.'
complete -c geodesic -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds).'
complete -c geodesic -o speed --description 'Animation speed.   2. 0 means twice as fast, 0. 5 means half as fast.'
complete -c geodesic -o count --description 'Depth (frequency) of the geodesic sphere.   Default: 4.'

