# geodesicgears
# Autogenerated from man page /usr/share/man/man6/geodesicgears.6x.gz
complete -c geodesicgears -o visual --description 'Specify which visual to use.'
complete -c geodesicgears -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c geodesicgears -o root --description 'Draw on the root window.'
complete -c geodesicgears -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds).'
complete -c geodesicgears -o timeout --description 'Duration before switching to a new model.   5 - 120 seconds.   Default: 20.'
complete -c geodesicgears -o labels -o no-labels --description 'Whether to show the number of gears and teeth.   Default: no.'
complete -c geodesicgears -o numbers -o no-numbers --description 'Whether to label the gears with ID numbers.   Default: no.'
complete -c geodesicgears -o wireframe -o no-wireframe --description 'Render in wireframe instead of solid.'
complete -c geodesicgears -o wander -o no-wander --description 'Whether the object should wander around the screen.'
complete -c geodesicgears -o spin -o no-spin --description 'Whether the object should spin.'
complete -c geodesicgears -o fps -o no-fps --description 'Whether to show a frames-per-second display at the bottom of the screen.'

