# getcifsacl
# Autogenerated from man page /usr/share/man/man1/getcifsacl.1.gz
complete -c getcifsacl -s v --description 'Print version number and exit.'
complete -c getcifsacl -s r --description '.'

