# git-ls-remote
# Autogenerated from man page /usr/share/man/man1/git-ls-remote.1.gz
complete -c git-ls-remote -s h -l heads -s t -l tags --description 'Limit to only refs/heads and refs/tags, respectively.'
complete -c git-ls-remote -l upload-pack --description 'Specify the full path of git-upload-pack on the remote host.'
complete -c git-ls-remote -l exit-code --description 'Exit with status "2" when no matching refs are found in the remote repository.'
complete -c git-ls-remote -l get-url --description 'Expand the URL of the given remote repository taking into account any "url.'

