# git-worktree
# Autogenerated from man page /usr/share/man/man1/git-worktree.1.gz
complete -c git-worktree -s f -l force --description 'By default, add refuses to create a new working tree when <branch> is already…'
complete -c git-worktree -s b -s B --description 'With add, create a new branch named <new-branch> starting at <branch>, and ch…'
complete -c git-worktree -l detach --description 'With add, detach HEAD in the new working tree.'
complete -c git-worktree -s n -l dry-run --description 'With prune, do not remove anything; just report what it would remove.'
complete -c git-worktree -l porcelain --description 'With list, output in an easy-to-parse format for scripts.'
complete -c git-worktree -s v -l verbose --description 'With prune, report all removals.'
complete -c git-worktree -l expire --description 'With prune, only expire unused working trees older than <time>.'
complete -c git-worktree -l detached --description 'used, then, as a convenience, a new branch based at HEAD is created automatic…'

