# git-interpret-trailers
# Autogenerated from man page /usr/share/man/man1/git-interpret-trailers.1.gz
complete -c git-interpret-trailers -l trim-empty --description 'If the <value> part of any trailer contains only whitespace, the whole traile…'
complete -c git-interpret-trailers -l trailer --description 'Specify a (<token>, <value>) pair that should be applied as a trailer to the …'

