# git-mergetool
# Autogenerated from man page /usr/share/man/man1/git-mergetool.1.gz
complete -c git-mergetool -s t -l tool --description 'Use the merge resolution program specified by <tool>.'
complete -c git-mergetool -l tool-help --description 'Print a list of merge tools that may be used with --tool.'
complete -c git-mergetool -s y -l no-prompt --description 'Don\\(cqt prompt before each invocation of the merge resolution program.'
complete -c git-mergetool -l prompt --description 'Prompt before each invocation of the merge resolution program to give the use…'
complete -c git-mergetool -l 'tool.' --description '.'

