# git-for-each-ref
# Autogenerated from man page /usr/share/man/man1/git-for-each-ref.1.gz
complete -c git-for-each-ref -l shell -l perl -l python -l tcl --description 'If given, strings that substitute %(fieldname) placeholders are quoted as str…'
complete -c git-for-each-ref -l points-at --description 'Only list refs which points at the given object.'
complete -c git-for-each-ref -l merged --description 'Only list refs whose tips are reachable from the specified commit (HEAD if no…'
complete -c git-for-each-ref -l no-merged --description 'Only list refs whose tips are not reachable from the specified commit (HEAD i…'
complete -c git-for-each-ref -l contains --description 'Only list tags which contain the specified commit (HEAD if not specified).'
complete -c git-for-each-ref -l quote --description 'everything in between %(align:.'
complete -c git-for-each-ref -l format --description 'Subject: %(*subject) Date: %(*authordate) Ref: %(*refname).'

