# git-upload-pack
# Autogenerated from man page /usr/share/man/man1/git-upload-pack.1.gz
complete -c git-upload-pack -l strict --description 'Do not try <directory>/. git/ if <directory> is no Git directory.'
complete -c git-upload-pack -l timeout --description 'Interrupt transfer after <n> seconds of inactivity.'

