# glblur
# Autogenerated from man page /usr/share/man/man6/glblur.6x.gz
complete -c glblur -o visual --description 'Specify which visual to use.'
complete -c glblur -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c glblur -o root --description 'Draw on the root window.'
complete -c glblur -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c glblur -o blursize --description 'How many copies of the scene should be laid down to make the vapor trail.'
complete -c glblur -o wander -o no-wander --description 'Whether the object should wander around the screen.'
complete -c glblur -o spin --description 'Around which axes should the object spin?.'
complete -c glblur -o no-spin --description 'None.'
complete -c glblur -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

