# gleidescope
# Autogenerated from man page /usr/share/man/man6/gleidescope.6x.gz
complete -c gleidescope -o visual --description 'Specify which visual to use.'
complete -c gleidescope -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c gleidescope -o root --description 'Draw on the root window.'
complete -c gleidescope -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c gleidescope -o move --description 'Move the camera.'
complete -c gleidescope -o rotate --description 'Rotate the camera.'
complete -c gleidescope -o zoom --description 'Zoom the camera in and out.'
complete -c gleidescope -o image --description 'The texture map to use at the end of the kaleidescope.'
complete -c gleidescope -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c gleidescope -o size --description 'The size of the hexagons being displayed [1(small)-10(large)].'
complete -c gleidescope -o duration --description 'The time in seconds before another image is chosen.'

