# glhanoi
# Autogenerated from man page /usr/share/man/man6/glhanoi.6x.gz
complete -c glhanoi -o visual --description 'Specify which visual to use.'
complete -c glhanoi -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c glhanoi -o root --description 'Draw on the root window.'
complete -c glhanoi -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c glhanoi -o count --description 'Number of disks.   Default: 7.'
complete -c glhanoi -o poles --description 'Number of poles.   Default: random from 3 to disks+1.'
complete -c glhanoi -o speed --description 'Speed multiplier (for smallest disks).   Default: 1.'
complete -c glhanoi -o trails --description 'Length of disk trails, in seconds.   Default: 2.'
complete -c glhanoi -o wireframe -o no-wireframe --description 'Render in wireframe instead of solid.'
complete -c glhanoi -o fog -o no-fog --description 'Render in fog.'
complete -c glhanoi -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c glhanoi -o light -o no-light --description 'Whether the scene is lit.'
complete -c glhanoi -o texture -o no-texture --description 'Render with textures instead of solid.'

