# glknots
# Autogenerated from man page /usr/share/man/man6/glknots.6x.gz
complete -c glknots -o visual --description 'Specify which visual to use.'
complete -c glknots -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c glknots -o root --description 'Draw on the root window.'
complete -c glknots -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c glknots -o speed --description 'Larger numbers mean run faster.   Default: 1. 0.'
complete -c glknots -o segments --description 'Number of segments in each path.   Default 800.'
complete -c glknots -o thickness --description 'How thick the tubes should be.   Default 0. 3.'
complete -c glknots -o duration --description 'How long to leave each knot up.   Default 8 seconds.'
complete -c glknots -o wander -o no-wander --description 'Whether the cubes should wander around the screen.'
complete -c glknots -o spin -o no-spin --description 'Which axes, if any, to spin around on.'
complete -c glknots -o wireframe -o no-wireframe --description 'Render in wireframe instead of solid.'
complete -c glknots -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

