# glplanet
# Autogenerated from man page /usr/share/man/man6/glplanet.6x.gz
complete -c glplanet -o visual --description 'Specify which visual to use.'
complete -c glplanet -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c glplanet -o root --description 'Draw on the root window.'
complete -c glplanet -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c glplanet -o images --description 'The texture map to wrap around the planet\'s surface.'
complete -c glplanet -o resolution --description 'The resolution of the planet.  Default: 128.'
complete -c glplanet -o wireframe --description 'Render in wireframe instead of solid.'
complete -c glplanet -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

