# glsnake
# Autogenerated from man page /usr/share/man/man6/glsnake.6x.gz
complete -c glsnake -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c glsnake -o root --description 'Draw on the root window.'
complete -c glsnake -o install --description 'Install a private colormap for the window.'
complete -c glsnake -o visual --description 'Specify which visual to use.'
complete -c glsnake -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c glsnake -o wireframe --description 'Display the snake in wireframe mode, rather than the default solid mode.'
complete -c glsnake -o altcolour --description 'Use the alternate colour scheme for the snake.'
complete -c glsnake -o angvel --description 'Change the speed at which the snake morphs to a new shape.'
complete -c glsnake -o explode --description 'Change the distance between the nodes of a snake.'
complete -c glsnake -o statictime --description 'Change the time between morphs.'
complete -c glsnake -o yangvel --description 'Change the angle of rotation around the Y axis per frame.'
complete -c glsnake -o zangvel --description 'Change the angle of rotation around the Z axis per frame.'

