# google-chrome
# Autogenerated from man page /usr/share/man/man1/google-chrome.1
complete -c google-chrome -l user-data-dir --description 'Specifies the directory that user data (your "profile") is kept in.'
complete -c google-chrome -l app --description 'Runs  URL in "app mode": with no browser toolbars.'
complete -c google-chrome -l incognito --description 'Open in incognito mode.'
complete -c google-chrome -l new-window --description 'If PATH or URL is given, open it in a new window.'
complete -c google-chrome -l proxy-server --description 'Specify the HTTP/SOCKS4/SOCKS5 proxy server to use for requests.'
complete -c google-chrome -l no-proxy-server --description 'Disables the proxy server.'
complete -c google-chrome -l proxy-auto-detect --description 'Autodetect proxy configuration.'
complete -c google-chrome -l proxy-pac-url --description 'Specify proxy autoconfiguration URL.'
complete -c google-chrome -l password-store --description 'Set the password store to use.'
complete -c google-chrome -l version --description 'Show version information.'
complete -c google-chrome -l display --description 'See the GTK documentation for more: <http://library. gnome.'

