# gpgv
# Autogenerated from man page /usr/share/man/man1/gpgv.1.gz
complete -c gpgv -s v --description 'Gives more information during processing.'
complete -c gpgv -s q --description 'Try to be as quiet as possible.'
complete -c gpgv -l keyring --description 'Add file to the list of keyrings.'
complete -c gpgv -l status-fd --description 'Write special status strings to the file descriptor n.'
complete -c gpgv -l logger-fd --description 'Write log output to file descriptor n and not to stderr.'
complete -c gpgv -l ignore-time-conflict --description 'GnuPG normally checks that the timestamps associated with keys and signatures…'
complete -c gpgv -l homedir --description 'Set the name of the home directory to dir.'
complete -c gpgv -l verbose --description '.'
complete -c gpgv -l quiet --description '.'
complete -c gpgv -l weak-digest --description 'Treat the specified digest algorithm as weak.'

