# grav
# Autogenerated from man page /usr/share/man/man6/grav.6x.gz
complete -c grav -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c grav -o root --description 'Draw on the root window.'
complete -c grav -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c grav -o install --description 'Install a private colormap for the window.'
complete -c grav -o visual --description 'Specify which visual to use.'
complete -c grav -o ncolors --description 'How many colors should be used (if possible).   Default 64.'
complete -c grav -o count --description 'Default 12.'
complete -c grav -o no-decay --description 'Whether orbits should decay.'
complete -c grav -o no-trail --description 'Whether the objects should leave trails behind them (makes it look vaguely li…'
complete -c grav -o decay --description '.'
complete -c grav -o trail --description '.'
complete -c grav -o fps --description 'Display the current frame rate and CPU load.'

