# greynetic
# Autogenerated from man page /usr/share/man/man6/greynetic.6x.gz
complete -c greynetic -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c greynetic -o root --description 'Draw on the root window.'
complete -c greynetic -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c greynetic -o install --description 'Install a private colormap for the window.'
complete -c greynetic -o visual --description 'Specify which visual to use.'
complete -c greynetic -o delay --description 'Slow it down.'
complete -c greynetic -o fps --description 'Display the current frame rate and CPU load.'

