# gst-play-1
# Autogenerated from man page /usr/share/man/man1/gst-play-1.0.1.gz
complete -c gst-play-1 -l help --description 'Print help synopsis and available command line options.'
complete -c gst-play-1 -l version --description 'Print version and exit.'
complete -c gst-play-1 -l audiosink --description 'Use the SOMESINK element as audio sink instead of autoaudiosink.'
complete -c gst-play-1 -l videosink --description 'Use the SOMESINK element as video sink instead of autovideosink.'
complete -c gst-play-1 -l volume --description 'Set initial playback volume to VOLUME, where 0. 0=silent and 1. 0=unchanged.'
complete -c gst-play-1 -l shuffle --description 'Shuffle playlist (play files in random order).'
complete -c gst-play-1 -l no-interactive --description 'Disable control through keyboard interaction in terminal (see below).'

