# gst-inspect-1
# Autogenerated from man page /usr/share/man/man1/gst-inspect-1.0.1.gz
complete -c gst-inspect-1 -l help --description 'Print help synopsis and available FLAGS.'
complete -c gst-inspect-1 -l gst-info-mask --description 'GStreamer info flags to set (list with --help).'
complete -c gst-inspect-1 -s a -l print-all --description 'Print all plugins and elements.'
complete -c gst-inspect-1 -l print-plugin-auto-install-info --description 'Print a machine-parsable list of features the specified plugin provides.'
complete -c gst-inspect-1 -l gst-debug-mask --description 'GStreamer debugging flags to set (list with --help).'
complete -c gst-inspect-1 -l gst-mask --description 'GStreamer info and debugging flags to set (list with --help).'
complete -c gst-inspect-1 -l gst-plugin-spew --description 'GStreamer info flags to set Enable printout of errors while loading GStreamer…'

