# gvfs-mime
# Autogenerated from man page /usr/share/man/man1/gvfs-mime.1.gz
complete -c gvfs-mime -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-mime -l version --description 'Shows the version number and exits.'
complete -c gvfs-mime -l query --description 'Query the handler for MIMETYPE.'
complete -c gvfs-mime -l set --description 'Set the default handler for MIMETYPE to HANDLER.'

