# gvfs-save
# Autogenerated from man page /usr/share/man/man1/gvfs-save.1.gz
complete -c gvfs-save -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-save -l version --description 'Shows the version number and exits.'
complete -c gvfs-save -s b -l backup --description 'If the destination file already exists, save a backup.'
complete -c gvfs-save -s c -l create --description 'Only create the destination file if it does not exist yet.'
complete -c gvfs-save -s a -l append --description 'Append to the end of the destination file, if it already exists.'
complete -c gvfs-save -s p -l private --description 'When creating a new file, restrict access to the current user only.'
complete -c gvfs-save -s u -l unlink --description 'When replacing an existing file, replace the destination as if it does not ex…'
complete -c gvfs-save -s v -l print-etag --description 'Print the new etag at the end.'
complete -c gvfs-save -s e -l etag --description 'The etag of the file being overwritten.'

