# gvfs-trash
# Autogenerated from man page /usr/share/man/man1/gvfs-trash.1.gz
complete -c gvfs-trash -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-trash -l version --description 'Shows the version number and exits.'
complete -c gvfs-trash -s f -l force --description 'Ignore nonexistent and non-deletable files.'
complete -c gvfs-trash -l empty --description 'Empty the trash.'

