# gvfs-tree
# Autogenerated from man page /usr/share/man/man1/gvfs-tree.1.gz
complete -c gvfs-tree -s '?' -l help --description 'Prints a short help text and exits.'
complete -c gvfs-tree -l version --description 'Shows the version number and exits.'
complete -c gvfs-tree -s h -l hidden --description 'Show hidden files.'
complete -c gvfs-tree -s l -l follow-symlinks --description 'Follow symbolic links, mounts and shortcuts.'

