# gvfs-monitor-file
# Autogenerated from man page /usr/share/man/man1/gvfs-monitor-file.1.gz
complete -c gvfs-monitor-file -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-monitor-file -l version --description 'Shows the version number and exits.'
complete -c gvfs-monitor-file -s N -l no-pair --description 'Don\\*(Aqt send single MOVED events.'

