# gvfs-ls
# Autogenerated from man page /usr/share/man/man1/gvfs-ls.1.gz
complete -c gvfs-ls -s '?' -l help --description 'Prints a short help text and exits.'
complete -c gvfs-ls -l version --description 'Shows the version number and exits.'
complete -c gvfs-ls -s a -l attributes --description 'The attributes to get, specified as a comma-separated list of gvfs file attri…'
complete -c gvfs-ls -s h -l hidden --description 'Show hidden files.'
complete -c gvfs-ls -s l -l long --description 'Use a long listing format.'
complete -c gvfs-ls -s c -l show-completions --description 'Show only filenames starting with PREFIX.'
complete -c gvfs-ls -s n -l nofollow-symlinks --description 'Don\\*(Aqt follow symlinks.'

