# gvfs-move
# Autogenerated from man page /usr/share/man/man1/gvfs-move.1.gz
complete -c gvfs-move -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-move -l version --description 'Shows the version number and exits.'
complete -c gvfs-move -s T -l no-target-directory --description 'Don\\*(Aqt move into DEST even if it is a directory.'
complete -c gvfs-move -s p -l progress --description 'Show progress.'
complete -c gvfs-move -s i -l interactive --description 'Prompt before overwriting files.'
complete -c gvfs-move -s b -l backup --description 'Backup existing destination files.'
complete -c gvfs-move -s C -l no-copy-fallback --description 'Don\\*(Aqt use copy and delete fallback.'

