# gvfs-info
# Autogenerated from man page /usr/share/man/man1/gvfs-info.1.gz
complete -c gvfs-info -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-info -l version --description 'Shows the version number and exits.'
complete -c gvfs-info -s w -l query-writable --description 'Show writable attributes and their types.'
complete -c gvfs-info -s f -l filesystem --description 'Show information about the filesystem on which the files reside.'
complete -c gvfs-info -s a -l attributes --description 'The attributes to get, specified as a comma-separated list of gvfs file attri…'
complete -c gvfs-info -s n -l nofollow-symlinks --description 'Don\\*(Aqt follow symlinks.'

