# gvfs-monitor-dir
# Autogenerated from man page /usr/share/man/man1/gvfs-monitor-dir.1.gz
complete -c gvfs-monitor-dir -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-monitor-dir -l version --description 'Shows the version number and exits.'
complete -c gvfs-monitor-dir -s N -l no-pair --description 'Don\\*(Aqt send single MOVED events.'

