# gvfs-set-attribute
# Autogenerated from man page /usr/share/man/man1/gvfs-set-attribute.1.gz
complete -c gvfs-set-attribute -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-set-attribute -l version --description 'Shows the version number and exits.'
complete -c gvfs-set-attribute -s t -l type --description 'Specifies the type of the attribute.'
complete -c gvfs-set-attribute -s n -l nofollow-symlinks --description 'Don\\*(Aqt follow symlinks.'

