# gvfs-mkdir
# Autogenerated from man page /usr/share/man/man1/gvfs-mkdir.1.gz
complete -c gvfs-mkdir -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-mkdir -l version --description 'Shows the version number and exits.'
complete -c gvfs-mkdir -s p -l parent --description 'Create parent directories when necessary.'

