# gvfs-rename
# Autogenerated from man page /usr/share/man/man1/gvfs-rename.1.gz
complete -c gvfs-rename -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-rename -l version --description 'Shows the version number and exits.'

