# gvfs-mount
# Autogenerated from man page /usr/share/man/man1/gvfs-mount.1.gz
complete -c gvfs-mount -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-mount -l version --description 'Shows the version number and exits.'
complete -c gvfs-mount -s m -l mountable --description 'Mount as a mountable.'
complete -c gvfs-mount -s d -l device --description 'Mount the volume with the given device file.'
complete -c gvfs-mount -s u -l unmount --description 'Unmount the locations.'
complete -c gvfs-mount -s e -l eject --description 'Eject the locations.'
complete -c gvfs-mount -s s -l unmount-scheme --description 'Unmount all mounts with the given scheme.'
complete -c gvfs-mount -s f -l force --description 'Ignore outstanding file operations when unmounting or ejecting.'
complete -c gvfs-mount -s a -l anonymous --description 'Use an anonymous user when authenticating.'
complete -c gvfs-mount -s l -l list --description 'List all known mounts.'
complete -c gvfs-mount -s o -l monitor --description 'Monitor mount and unmount events.'
complete -c gvfs-mount -s i -l detail --description 'Show extra information for --list and --monitor.'

