# gvfs-open
# Autogenerated from man page /usr/share/man/man1/gvfs-open.1.gz
complete -c gvfs-open -s h -l help --description 'Prints a short help text and exits.'
complete -c gvfs-open -l version --description 'Shows the version number and exits.'

