# halftone
# Autogenerated from man page /usr/share/man/man6/halftone.6x.gz
complete -c halftone -o visual --description 'Specify which visual to use.'
complete -c halftone -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c halftone -o root --description 'Draw on the root window.'
complete -c halftone -o count --description 'How many mass points to move around.  Default: 10.'
complete -c halftone -o spacing --description 'Distance between each halftone dot.  Default: 14.'
complete -c halftone -o sizefactor --description 'How big each halftone dot should be drawn compared to the spacing value.'
complete -c halftone -o minmass --description 'The minimum mass of each mass point.  Default: 0. 001.'
complete -c halftone -o maxmass --description 'The maximum mass of each mass point.  Default: 0. 02.'
complete -c halftone -o minspeed --description 'The minimum speed of each mass point.  Default: 0. 001.'
complete -c halftone -o maxspeed --description 'The maximum speed of each mass point.  Default: 0.'
complete -c halftone -o delay --description 'Per-frame delay, in microseconds.   Default: 10000.'
complete -c halftone -o fps --description 'Display the current frame rate and CPU load.'

