# halo
# Autogenerated from man page /usr/share/man/man6/halo.6x.gz
complete -c halo -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c halo -o root --description 'Draw on the root window.'
complete -c halo -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c halo -o install --description 'Install a private colormap for the window.'
complete -c halo -o visual --description 'Specify which visual to use.'
complete -c halo -o count --description 'How many circles to draw.   Default 0, meaning random.'
complete -c halo -o mode --description 'In seuss mode, alternating striped curves will be drawn.'
complete -c halo -o delay --description 'How much of a delay should be introduced between steps of the animation.'
complete -c halo -o colors --description 'How many colors to use.   Default 100.'
complete -c halo -o animate --description 'If specified, then the centerpoints of the circles will bounce around.'
complete -c halo -o fps --description 'Display the current frame rate and CPU load.'

