# hardening-check
# Autogenerated from man page /usr/share/man/man1/hardening-check.1.gz
complete -c hardening-check -l nopie -s p --description 'No not require that the checked binaries be built as \\s-1PIE. \\s0.'
complete -c hardening-check -l nostackprotector -s s --description 'No not require that the checked binaries be built with the stack protector.'
complete -c hardening-check -l nofortify -s f --description 'No not require that the checked binaries be built with Fority Source.'
complete -c hardening-check -l norelro -s r --description 'No not require that the checked binaries be built with \\s-1RELRO. \\s0.'
complete -c hardening-check -l nobindnow -s b --description 'No not require that the checked binaries be built with \\s-1BIND_NOW. \\s0.'
complete -c hardening-check -l quiet -s q --description 'Only report failures.'
complete -c hardening-check -l verbose -s v --description 'Report verbosely on failures.'
complete -c hardening-check -l report-functions -s R --description 'After the report, display all external functions needed by the \\s-1ELF. \\s0.'
complete -c hardening-check -l find-libc-functions -s F --description 'Instead of the regular report, locate the libc for the first \\s-1ELF\\s0 on th…'
complete -c hardening-check -l color -s c --description 'Enable colorized status output.'
complete -c hardening-check -l lintian -s l --description 'Switch reporting to lintian-check-parsable output.'
complete -c hardening-check -l debug --description 'Report some debugging during processing.'
complete -c hardening-check -l help -s h -s '?' --description 'Print a brief help message and exit.'

