# hddtemp
# Autogenerated from man page /usr/share/man/man8/hddtemp.8.gz
complete -c hddtemp -s b -l drivebase --description 'Display the database file that allows hddtemp to recognize a supported drive.'
complete -c hddtemp -s D -l debug --description 'Display various S. M. A. R. T.  fields and their values.'
complete -c hddtemp -s d -l daemon --description 'Execute hddtemp in TCP/IP daemon mode (port 7634 by default).'
complete -c hddtemp -s f -l file --description 'Specify the database file to use.'
complete -c hddtemp -s F -l foreground --description 'Don\'t fork into the background even in daemon mode.'
complete -c hddtemp -s l -l listen --description 'Listen on a specific address.'
complete -c hddtemp -s n -l numeric --description 'Print only the temperature (without the unit).'
complete -c hddtemp -s p -l port --description 'Port number to listen to (in TCP/IP daemon mode).'
complete -c hddtemp -s s -l separator --description 'Separator to use between fields (in TCP/IP daemon mode).'
complete -c hddtemp -s S -l syslog --description 'Switch to daemon mode and log temperatures to syslog every s seconds.'
complete -c hddtemp -s q -l quiet --description 'Don\'t check if the drive is supported.'
complete -c hddtemp -s u -l unit --description 'Force output temperature either in Celsius or Fahrenheit.'
complete -c hddtemp -s v -l version --description 'Display hddtemp version number.'
complete -c hddtemp -s w -l wake-up --description 'Wake-up the drive if needed (ATA drives only).'
complete -c hddtemp -s 4 --description 'Listen on IPv4 sockets only.'

