# hexadrop
# Autogenerated from man page /usr/share/man/man6/hexadrop.6x.gz
complete -c hexadrop -o visual --description 'Specify which visual to use.'
complete -c hexadrop -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c hexadrop -o root --description 'Draw on the root window.'
complete -c hexadrop -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c hexadrop -o speed --description 'Speed.  0. 5 for half as fast; 2. 0 for twice as fast.'
complete -c hexadrop -o size --description 'How many tiles to fit horizontally on the screen.   Default 15.'
complete -c hexadrop -o sides --description 'Shape of the tiles.  3, 4, 6 or 8.  Default: random.'
complete -c hexadrop -o uniform-speed -o no-uniform-speed --description 'Whether each tile should drop at the same speed.  Default: random.'
complete -c hexadrop -o lockstep -o no-lockstep --description 'Whether each tile should drop at the same time.  Default: random.'
complete -c hexadrop -o fps -o no-fps --description 'Whether to show a frames-per-second display at the bottom of the screen.'

