# hexchat
# Autogenerated from man page /usr/share/man/man1/hexchat.1.gz
complete -c hexchat -s h -l help --description 'Show help options.'
complete -c hexchat -l help-all --description 'Show all help options.'
complete -c hexchat -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c hexchat -s a -l no-auto --description 'Don\'t auto connect to servers.'
complete -c hexchat -s d -l cfgdir --description 'Use a different config directory.'
complete -c hexchat -s n -l no-plugins --description 'Don\'t auto load any plugins.'
complete -c hexchat -s p -l plugindir --description 'Show plugin auto-load directory.'
complete -c hexchat -s u -l configdir --description 'Show user config directory.'
complete -c hexchat -l url --description 'Open an irc://server:port/channel?key URL.'
complete -c hexchat -s c -l command --description 'Execute command:.'
complete -c hexchat -s e -l existing --description 'Open URL or execute command in an existing HexChat.'
complete -c hexchat -l minimize --description 'Begin minimized.  Level 0=Normal 1=Iconified 2=Tray.'
complete -c hexchat -s v -l version --description 'Show version information.'
complete -c hexchat -l display --description 'X display to use.'

