# ideviceinfo
# Autogenerated from man page /usr/share/man/man1/ideviceinfo.1.gz
complete -c ideviceinfo -s d -l debug --description 'enable communication debugging.'
complete -c ideviceinfo -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c ideviceinfo -s q -l domain --description 'set domain of query to NAME.  Default: None.'
complete -c ideviceinfo -s k -l key --description 'only query key specified by NAME.  Default: All keys.'
complete -c ideviceinfo -s x -l xml --description 'output information as xml plist instead of key/value pairs.'
complete -c ideviceinfo -s h -l help --description 'prints usage information.'

