# ideviceinstaller
# Autogenerated from man page /usr/share/man/man1/ideviceinstaller.1.gz
complete -c ideviceinstaller -s d -l debug --description 'enable communication debugging.'
complete -c ideviceinstaller -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c ideviceinstaller -s h -l help --description 'prints usage information  . SS Commands:.'
complete -c ideviceinstaller -s l -l list-apps --description 'list apps installed on the device. RS  Additional options:.'
complete -c ideviceinstaller -s o --description 'list user apps only (apps installed by the user)  This is the default.'
complete -c ideviceinstaller -s i -l install --description 'install app from a package file specified by ARCHIVE.  ARCHIVE can also be a .'
complete -c ideviceinstaller -s U -l uninstall --description 'uninstall app specified by APPID.'
complete -c ideviceinstaller -s g -l upgrade --description 'upgrade app from a package file specified by ARCHIVE.'
complete -c ideviceinstaller -s r -l restore --description 'restore archived app specified by APPID.'
complete -c ideviceinstaller -s L -l list-archives --description 'list archived applications on the device. RS  Additional options:.'
complete -c ideviceinstaller -s a -l archive --description 'archive app specified by APPID. RS  Additional options:.'
complete -c ideviceinstaller -s R -l remove-archive --description 'remove app archive specified by APPID.'

