# ideviceimagemounter
# Autogenerated from man page /usr/share/man/man1/ideviceimagemounter.1.gz
complete -c ideviceimagemounter -s d -l debug --description 'enable communication debugging.'
complete -c ideviceimagemounter -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c ideviceimagemounter -s l -l list --description 'list mount information.'
complete -c ideviceimagemounter -s t -l imagetype --description 'the image type to use, default is \'Developer\'.'
complete -c ideviceimagemounter -s x -l xml --description 'use XML output.'
complete -c ideviceimagemounter -s h -l help --description 'prints usage information.'

