# idevicename
# Autogenerated from man page /usr/share/man/man1/idevicename.1.gz
complete -c idevicename -s d -l debug --description 'enable communication debugging.'
complete -c idevicename -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c idevicename -s h -l help --description 'prints usage information.'

