# ideviceenterrecovery
# Autogenerated from man page /usr/share/man/man1/ideviceenterrecovery.1.gz
complete -c ideviceenterrecovery -s d -l debug --description 'enable communication debugging.'
complete -c ideviceenterrecovery -s h -l help --description 'prints usage information.'

