# idevicediagnostics
# Autogenerated from man page /usr/share/man/man1/idevicediagnostics.1.gz
complete -c idevicediagnostics -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c idevicediagnostics -s d -l debug --description 'enable communication debugging.'
complete -c idevicediagnostics -s h -l help --description 'prints usage information.'

