# idevicescreenshot
# Autogenerated from man page /usr/share/man/man1/idevicescreenshot.1.gz
complete -c idevicescreenshot -s d -l debug --description 'enable communication debugging.'
complete -c idevicescreenshot -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c idevicescreenshot -s h -l help --description 'prints usage information.'

