# idevicepair
# Autogenerated from man page /usr/share/man/man1/idevicepair.1.gz
complete -c idevicepair -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c idevicepair -s d -l debug --description 'enable communication debugging.'
complete -c idevicepair -s h -l help --description 'prints usage information.'

