# idevicedebugserverproxy
# Autogenerated from man page /usr/share/man/man1/idevicedebugserverproxy.1.gz
complete -c idevicedebugserverproxy -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c idevicedebugserverproxy -s d -l debug --description 'enable communication debugging.'
complete -c idevicedebugserverproxy -s h -l help --description 'prints usage information.'

