# idevice_id
# Autogenerated from man page /usr/share/man/man1/idevice_id.1.gz
complete -c idevice_id -s l -l list --description 'list UDID of all attached devices.'
complete -c idevice_id -s d -l debug --description 'enable communication debugging.'
complete -c idevice_id -s h -l help --description 'prints usage information.'

