# idevicesyslog
# Autogenerated from man page /usr/share/man/man1/idevicesyslog.1.gz
complete -c idevicesyslog -s d -l debug --description 'enable communication debugging.'
complete -c idevicesyslog -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c idevicesyslog -s h -l help --description 'prints usage information.'

