# idevicedebug
# Autogenerated from man page /usr/share/man/man1/idevicedebug.1.gz
complete -c idevicedebug -s e -l env --description 'set environment variable NAME to VALUE.'
complete -c idevicedebug -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c idevicedebug -s d -l debug --description 'enable communication debugging.'
complete -c idevicedebug -s h -l help --description 'prints usage information.'

