# idevicecrashreport
# Autogenerated from man page /usr/share/man/man1/idevicecrashreport.1.gz
complete -c idevicecrashreport -s e -l extract --description 'extract raw crash report into separate \'. crash\' files.'
complete -c idevicecrashreport -s k -l keep --description 'copy but do not remove crash reports from device.'
complete -c idevicecrashreport -s d -l debug --description 'enable communication debugging.'
complete -c idevicecrashreport -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c idevicecrashreport -s h -l help --description 'prints usage information.'

