# idevicedate
# Autogenerated from man page /usr/share/man/man1/idevicedate.1.gz
complete -c idevicedate -s d -l debug --description 'enable communication debugging.'
complete -c idevicedate -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c idevicedate -s s -l set --description 'set UTC time described by TIMESTAMP.'
complete -c idevicedate -s c -l sync --description 'set time of device to current system time.'
complete -c idevicedate -s h -l help --description 'prints usage information.'

