# ifuse
# Autogenerated from man page /usr/share/man/man1/ifuse.1.gz
complete -c ifuse -s o --description 'mount options.'
complete -c ifuse -s u -l uuid --description 'mount specific device by its 40-digit device UUID.'
complete -c ifuse -s h -l help --description 'prints usage information.'
complete -c ifuse -s V -l version --description 'print version.'
complete -c ifuse -l appid --description 'mount \'Documents\' folder of app identified by APPID.'
complete -c ifuse -l root --description 'mount root file system (jailbroken device required).'
complete -c ifuse -l debug --description 'enable libimobiledevice communication debugging.'

