# initctl
# Autogenerated from man page /usr/share/man/man8/initctl.8.gz
complete -c initctl -l user --description 'User mode.'
complete -c initctl -l session --description 'Connect to  init (8) daemon using the existing D-Bus session bus (for testing…'
complete -c initctl -l system --description 'Communication with the  init (8) daemon is normally performed over a private …'
complete -c initctl -l dest --description 'Specifies the well-known name of the  init (8) daemon when using  --system .'
complete -c initctl -l no-wait --description 'Applies to the  start ", " stop ", " restart " and " emit commands.'
complete -c initctl -l quiet --description 'Reduces output of all commands to errors only.'
complete -c initctl -s e -l enumerate --description '.'
complete -c initctl -s i -l ignore-events --description '.'
complete -c initctl -s w -l warn --description 'If specified, treat any unknown jobs and events as errors.'
complete -c initctl -s g -l global --description 'Operate on the global job environment table.'
complete -c initctl -s r -l retain --description 'If any of the specified variables are already set, do not modify them.'
complete -c initctl -l verbose --description 'the full path of the stale session file is displayed).'

