# intel_gpu_frequency
# Autogenerated from man page /usr/share/man/man1/intel_gpu_frequency.1.gz
complete -c intel_gpu_frequency -s e --description 'Lock frequency to the most efficient frequency.'
complete -c intel_gpu_frequency -s g -l get --description 'Get all the current frequency settings.'
complete -c intel_gpu_frequency -s s -l set --description 'Lock frequency to an absolute value (MHz).'
complete -c intel_gpu_frequency -s c -l custom --description 'Set a min, or max frequency "min=X | max=Y".'
complete -c intel_gpu_frequency -s m -l max --description 'Lock frequency to max frequency.'
complete -c intel_gpu_frequency -s i -l min --description 'Lock frequency to min (never a good idea, DEBUG ONLY).'
complete -c intel_gpu_frequency -s d -l defaults --description 'Return the system to hardware defaults.'
complete -c intel_gpu_frequency -s h -l help --description 'Returns this.'
complete -c intel_gpu_frequency -s v -l version --description 'EXAMPLES.'

