# interference
# Autogenerated from man page /usr/share/man/man6/interference.6x.gz
complete -c interference -o visual --description 'Specify which visual to use.'
complete -c interference -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c interference -o root --description 'Draw on the root window.'
complete -c interference -o count --description 'Number of Waves.   0 - 20.   Default: 3.'
complete -c interference -o gridsize --description 'Magnification. 	1 - 20.   Default: 2.'
complete -c interference -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c interference -o speed --description 'Wave Speed.   1 - 100.   Default: 30.'
complete -c interference -o radius --description 'Wave Size.   50 - 1500. 	Default: 800.'
complete -c interference -o ncolors --description 'Number of Colors.   Default: 192.'
complete -c interference -o color-shift --description 'Color Contrast.   0 - 100.   Default: 60.'
complete -c interference -o hue --description 'Hue of the base color (0-360, as in HSV space. )  Default 0, meaning random.'
complete -c interference -o db -o no-db --description 'Whether to double buffer.'
complete -c interference -o fps --description 'Display the current frame rate and CPU load.'

