# intermomentary
# Autogenerated from man page /usr/share/man/man6/intermomentary.6x.gz
complete -c intermomentary -o num-discs --description 'Number of slowly moving and growing discs to use.'
complete -c intermomentary -o draw-delay --description 'Delay in ms between drawing cycles.'
complete -c intermomentary -o max-riders --description 'Maximum number of \'riders\', single dots moving around the edge of the discs.'
complete -c intermomentary -o max-radius --description 'Maximum possible radius of a disc.'
complete -c intermomentary -o fps --description 'Display the current frame rate and CPU load.'

