# intel_reg
# Autogenerated from man page /usr/share/man/man1/intel_reg.1.gz
complete -c intel_reg -l verbose --description '.'
complete -c intel_reg -l quiet --description '.'
complete -c intel_reg -l count --description '.'
complete -c intel_reg -l binary --description '.'
complete -c intel_reg -l all --description '.'
complete -c intel_reg -l mmio --description '.'
complete -c intel_reg -l devid --description '.'
complete -c intel_reg -l spec --description '.'
complete -c intel_reg -l help --description '.'

