# ip-addrlabel
# Autogenerated from man page /usr/share/man/man8/ip-addrlabel.8.gz
complete -c ip-addrlabel -s V --description '.'
complete -c ip-addrlabel -s s --description '.'
complete -c ip-addrlabel -s r --description '.'
complete -c ip-addrlabel -s f --description 'inet  |  inet6  |  ipx  |  dnet  |  link  } | .'
complete -c ip-addrlabel -s o --description 'ip addrlabel  {  add  |  del  }  prefix PREFIX  [  dev DEV  ] [  label NUMBER…'

