# ip-link
# Autogenerated from man page /usr/share/man/man8/ip-link.8.gz
complete -c ip-link -s V --description '.'
complete -c ip-link -s h --description '.'
complete -c ip-link -s s --description '.'
complete -c ip-link -s r --description '.'
complete -c ip-link -s f --description 'inet  |  inet6  |  ipx  |  dnet  |  link  } | .'
complete -c ip-link -s o --description '.'
complete -c ip-link -o br --description 'ip link add [  link DEVICE  ] [  name  ] NAME.'
complete -c ip-link -s t -s A -s j -l set-class --description 'and this "4" priority can be used in the egress qos mapping to set VLAN prio …'
complete -c ip-link -o stats -o statistics --description 'output more statistics about packet usage.'
complete -c ip-link -s d -o details --description 'output more detailed information.'
complete -c ip-link -o human -o human-readable --description 'output statistics with human readable values number followed by suffix.'
complete -c ip-link -o iec --description 'print human readable rates in IEC units (ie.  1K = 1024).'

