# ippusbxd
# Autogenerated from man page /usr/share/man/man1/ippusbxd.1.gz
complete -c ippusbxd -s h --description 'Show help message.'
complete -c ippusbxd -s v --description 'USB vendor id of desired printer.'
complete -c ippusbxd -s m --description 'USB product id of desired printer.'
complete -c ippusbxd -s s --description 'Serial number of desired printer.'
complete -c ippusbxd -s p --description 'Port number ippusbxd will expose the printer over.'
complete -c ippusbxd -s l --description 'Send all logging to syslog.'
complete -c ippusbxd -s q --description 'Enable verbose logging.'
complete -c ippusbxd -s n --description 'Enables no fork mode.  Disables deamonization.'
complete -c ippusbxd -s d --description 'Enables debug mode.  Implies -q and -n.'

