# jar
# Autogenerated from man page /usr/share/man/man1/jar.1.gz
complete -c jar -s C --description 'br When creating (\\f3c) or updating (\\f3u) a JAR file, this option temporaril…'
complete -c jar -o Joption --description 'Sets the specified JVM option to be used when the JRE runs the JAR file.'

