# javah
# Autogenerated from man page /usr/share/man/man1/javah.1.gz
complete -c javah -s o --description 'br Concatenates the resulting header or source files for all the classes list…'
complete -c javah -s d --description 'br Sets the directory where the \\f3javah command saves the header files or th…'
complete -c javah -o stubs --description 'br Causes the \\f3javah command to generate C declarations from the Java objec…'
complete -c javah -o verbose --description 'br Indicates verbose output and causes the \\f3javah command to print a messag…'
complete -c javah -o help --description 'br Prints a help message for \\f3javah usage.'
complete -c javah -o version --description 'br Prints \\f3javah command release information.'
complete -c javah -o jni --description 'br Causes the \\f3javah command to create an output file containing JNI-style …'
complete -c javah -o classpath --description 'br Specifies the path the \\f3javah command uses to look up classes.'
complete -c javah -o bootclasspath --description 'br Specifies the path from which to load bootstrap classes.'
complete -c javah -o old --description 'br Specifies that old JDK 1. 0-style header files should be generated.'
complete -c javah -o force --description 'br Specifies that output files should always be written.'
complete -c javah -o Joption --description '.'

