# jcmd
# Autogenerated from man page /usr/share/man/man1/jcmd.1.gz
complete -c jcmd -s f --description 'Reads commands from the specified file.'
complete -c jcmd -o 'h
.br
-help' --description 'Prints a help message.'
complete -c jcmd -s l --description 'Prints the list of running Java processes identifiers with the main class and…'
complete -c jcmd -s h --description 'or.'
complete -c jcmd -o help --description 'option prints the tool\'s help message.'

