# jconsole
# Autogenerated from man page /usr/share/man/man1/jconsole.1.gz
complete -c jconsole -o interval --description 'br Sets the update interval to n seconds (default is 4 seconds).'
complete -c jconsole -o notile --description 'br Does not tile windows initially (for two or more connections).'
complete -c jconsole -o pluginpath --description 'br Specifies a list of directories or JAR files to be searched for \\f3JConsol…'
complete -c jconsole -o version --description 'br Displays release information and exits.'
complete -c jconsole -o help --description 'br Displays a help message.'
complete -c jconsole -o Jflag --description '.'

