# jigglypuff
# Autogenerated from man page /usr/share/man/man6/jigglypuff.6x.gz
complete -c jigglypuff -o visual --description 'Specify which visual to use.'
complete -c jigglypuff -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c jigglypuff -o root --description 'Draw on the root window.'
complete -c jigglypuff -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c jigglypuff -o wireframe --description 'Render in wireframe instead of solid.  Default: render solid.'
complete -c jigglypuff -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c jigglypuff -o tetra -o no-tetra --description 'Whether to start the shape in the form of a tetrahedron.'
complete -c jigglypuff -o color --description 'Available options for colorspec are: cycle, flowerbox, clownpuke, chrome and …'
complete -c jigglypuff -o spooky --description 'This option controls a kind of interesting effect obtained by using unnormali…'
complete -c jigglypuff -o complexity --description 'Valid options are 1, 2, and 3.'
complete -c jigglypuff -o speed --description 'Controls how fast the blob moves around the screen.  Default: 500.'
complete -c jigglypuff -o spherism -o hold -o distance -o damping --description 'These options control the \'jigglyness\'.'
complete -c jigglypuff -o random --description 'Probably the only parameter you\'l ever need.'

