# jigsaw
# Autogenerated from man page /usr/share/man/man6/jigsaw.6x.gz
complete -c jigsaw -o delay --description 'How long to wait between animation frames; default 20000.'
complete -c jigsaw -o speed --description 'Less than 1 for slower, greater than 1 for faster.   Default 1.'
complete -c jigsaw -o complexity --description 'Less than 1 for simpler puzzles (fewer pieces), greater than 1 for more compl…'
complete -c jigsaw -o resolution --description 'Smoothness of the edges of the pieces.'
complete -c jigsaw -o thickness --description 'Thickness of the puzzle pieces (relative to their width).  Default 0. 06.'
complete -c jigsaw -o no-wobble --description 'Keep the display stationary instead of very slowly wobbling back and forth.'
complete -c jigsaw -o fps --description 'Display the current frame rate, polygon count, and CPU load.'
complete -c jigsaw -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c jigsaw -o root --description 'Draw on the root window.'
complete -c jigsaw -o install --description 'Install a private colormap for the window.'
complete -c jigsaw -o visual --description 'Specify which visual to use.'

