# jinfo
# Autogenerated from man page /usr/share/man/man1/jinfo.1.gz
complete -c jinfo -o flag --description 'br Prints the name and value of the specified command-line flag.'
complete -c jinfo -o ']name' --description 'br enables or disables the specified Boolean command-line flag.'
complete -c jinfo -o flags --description 'br Prints command-line flags passed to the JVM.'
complete -c jinfo -o sysprops --description 'br Prints Java system properties as name-value pairs.'
complete -c jinfo -s h --description 'br Prints a help message.'
complete -c jinfo -o help --description '.'

