# join-dctrl
# Autogenerated from man page /usr/share/man/man1/join-dctrl.1.gz
complete -c join-dctrl -s 1 -l 1st-join-field --description 'Specify the join  field of the first input file.'
complete -c join-dctrl -s 2 -l 2nd-join-field --description 'Specify the join  field of the second input file.'
complete -c join-dctrl -s j -l join-field --description 'Specify a common join  field for all files.'
complete -c join-dctrl -s a -l unpairable-from --description 'Specify that unmatched paragraphs from the first (if  1 is given) or the seco…'
complete -c join-dctrl -s o -l output-fields --description 'Specify which fields are included in the output.'
complete -c join-dctrl -s l -l errorlevel --description 'Set log level to R level .'
complete -c join-dctrl -s V -l version --description 'Print out version information.'
complete -c join-dctrl -s C -l copying --description 'Print out the copyright license.'
complete -c join-dctrl -s h -l help --description 'Print out a help summary.'

