# jpegexiforient
# Autogenerated from man page /usr/share/man/man1/jpegexiforient.1.gz
complete -c jpegexiforient -l help --description 'display this help and exit.'
complete -c jpegexiforient -l version --description 'output version information and exit.'
complete -c jpegexiforient -s n --description 'Do not output the trailing newline.'
complete -c jpegexiforient -l ----+-------------+----------- --description '  1   | top         | left side   2   | top         | right side   3   | bott…'
complete -c jpegexiforient -s 1 -s 8 --description 'Set orientation value 1 .  8 AUTHOR  Guido Vollbeding <guido@jpegclub.'

