# jrunscript
# Autogenerated from man page /usr/share/man/man1/jrunscript.1.gz
complete -c jrunscript -o classpath --description 'br Indicate where any class files are that the script needs to access.'
complete -c jrunscript -o cp --description 'br Same as \\f3-classpath\\f3path.'
complete -c jrunscript -o Dname --description 'br Sets a Java system property.'
complete -c jrunscript -o Jflag --description 'br Passes \\f3flag directly to the Java Virtual Machine where the \\f3jrunscrip…'
complete -c jrunscript -s I --description 'br Uses the specified scripting language.  By default, JavaScript is used.'
complete -c jrunscript -s e --description 'br Evaluates the specified script.'
complete -c jrunscript -o encoding --description 'br Specifies the character encoding used to read script files.'
complete -c jrunscript -s f --description 'br Evaluates the specified script file (batch mode).'
complete -c jrunscript -o help --description 'br Displays a help message and exits.'
complete -c jrunscript -s '?' --description 'br Displays a help message and exits.'
complete -c jrunscript -s q --description '.'

