# jstack
# Autogenerated from man page /usr/share/man/man1/jstack.1.gz
complete -c jstack -s F --description 'br Force a stack dump when \\f3jstack [\\f3-l] \\f3pid does not respond.'
complete -c jstack -s l --description 'br Long listing.'
complete -c jstack -s m --description 'br Prints a mixed mode stack trace that has both Java and native C/C++ frames.'
complete -c jstack -s h --description 'br Prints a help message.'
complete -c jstack -o help --description '.'

