# julia
# Autogenerated from man page /usr/share/man/man6/julia.6x.gz
complete -c julia -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c julia -o root --description 'Draw on the root window.'
complete -c julia -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c julia -o install --description 'Install a private colormap for the window.'
complete -c julia -o visual --description 'Specify which visual to use.'
complete -c julia -o ncolors --description 'How many colors should be used (if possible).   Default 200.'
complete -c julia -o cycles --description '.'
complete -c julia -o count --description '.'
complete -c julia -o fps --description 'Display the current frame rate and CPU load.'

