# jwt
# Autogenerated from man page /usr/share/man/man1/jwt.1.gz
complete -c jwt -l version --description 'show program\'s version number and exit.'
complete -c jwt -s h -l help --description 'show this help message and exit.'
complete -c jwt -s n -l no-verify --description 'ignore signature verification on decode.'
complete -c jwt -l key --description 'set the secret key to sign with.'
complete -c jwt -l alg --description 'set crypto algorithm to sign with.  default=HS256 EXAMPLES Decoding:.'

