# kaleidescope
# Autogenerated from man page /usr/share/man/man6/kaleidescope.6x.gz
complete -c kaleidescope -o root --description 'Draw on the root window.'
complete -c kaleidescope -o color_mode --description 'Specify how kaleidescope uses colors.'
complete -c kaleidescope -o install --description 'Install a private colormap for the window.'
complete -c kaleidescope -o visual --description 'Specify which visual to use.'
complete -c kaleidescope -o nsegments --description 'The number of segments to draw.  Default is 7.'
complete -c kaleidescope -o ntrails --description 'The number of trails to draw.  Default is 100.'
complete -c kaleidescope -o local_rotation --description 'The rate at which segments rotate around their center.  Default is -59.'
complete -c kaleidescope -o global_rotation --description 'The rate at which segments rotate around the center of the window.'
complete -c kaleidescope -o redmin -o greenmin -o bluemin -o redrange -o greenrange -o bluerange --description 'All take an integer argument.'
complete -c kaleidescope -o delay --description 'How much of a delay should be introduced between steps of the animation.'
complete -c kaleidescope -o fps --description 'Display the current frame rate and CPU load.'

