# kaleidocycle
# Autogenerated from man page /usr/share/man/man6/kaleidocycle.6x.gz
complete -c kaleidocycle -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c kaleidocycle -o root --description 'Draw on the root window.'
complete -c kaleidocycle -o install --description 'Install a private colormap for the window.'
complete -c kaleidocycle -o visual --description 'Specify which visual to use.'
complete -c kaleidocycle -o count --description 'The initial number of segments.  Default 16.'
complete -c kaleidocycle -o speed --description 'Adjust the animation speed.  0. 5 for half as fast, 2. 0 for twice as fast.'
complete -c kaleidocycle -o wander --description 'Move the text around the screen.   This is the default.'
complete -c kaleidocycle -o no-wander --description 'Keep the text centered on the screen.'
complete -c kaleidocycle -o spin --description 'Which axes around which the text should spin.'
complete -c kaleidocycle -o no-spin --description 'Don\'t spin the text at all: the same as -spin "".'
complete -c kaleidocycle -o wireframe --description 'Render in wireframe instead of solid.'
complete -c kaleidocycle -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

