# kazam
# Autogenerated from man page /usr/share/man/man1/kazam.1.gz
complete -c kazam -s h -l help --description 'show this help message and exit.'
complete -c kazam -l debug --description 'enable debug mode.'
complete -c kazam -l silent --description 'silent start, no UI shown.'
complete -c kazam -l nosound --description 'disable PulseAudio.'
complete -c kazam -l test --description 'generate test video signal.'
complete -c kazam -s v -l version --description 'show program\'s version number and exit.'
complete -c kazam -s f -l fullscreen --description 'instant screenshot of a full screen.'
complete -c kazam -s a -l area --description 'instant screenshot of a preselected screen area.'
complete -c kazam -s s -l select --description 'instant screenshot of a preselected window.'
complete -c kazam -s w -l window --description 'instant screenshot of an active window.'
complete -c kazam -s p -l preferences --description 'show preferences window.'
complete -c kazam -s g -l godmode --description 'god mode of capture.'
complete -c kazam -s x -l instance --description 'spawn new instance.'

