# kdesu
# Autogenerated from man page /usr/share/man/man1/kdesu.1.gz
complete -c kdesu -s c --description 'This specifies the command to run as root.'
complete -c kdesu -s d --description 'Show debug information.'
complete -c kdesu -s f --description 'This option allow efficient use of KDE su in . desktop files.'
complete -c kdesu -s i --description 'Specify icon to use in the password dialog.'
complete -c kdesu -s n --description 'Do not keep the password.'
complete -c kdesu -s p --description 'Set priority value.'
complete -c kdesu -s r --description 'Use realtime scheduling.'
complete -c kdesu -s s --description 'Stop the kdesu daemon.'
complete -c kdesu -s t --description 'Enable terminal output.  This disables password keeping.'
complete -c kdesu -s u --description 'While the most common use for KDE su is to run a command as the superuser, yo…'
complete -c kdesu -l noignorebutton --description 'Do not display an ignore button.'
complete -c kdesu -l attach --description 'Makes the dialog transient for an X app specified by winid.'

