# kpartx
# Autogenerated from man page /usr/share/man/man8/kpartx.8.gz
complete -c kpartx -s a --description 'Add partition mappings.'
complete -c kpartx -s r --description 'Read-only partition mappings.'
complete -c kpartx -s d --description 'Delete partition mappings.'
complete -c kpartx -s u --description 'Update partition mappings.'
complete -c kpartx -s l --description 'List partition mappings that would be added -a.'
complete -c kpartx -s p --description 'set device name-partition number delimiter.'
complete -c kpartx -s f --description 'force creation of mappings; overrides \'no_partitions\' feature.'
complete -c kpartx -s g --description 'force GUID partition table (GPT).'
complete -c kpartx -s v --description 'Operate verbosely.'
complete -c kpartx -s s --description 'Sync mode.'

