# kumppa
# Autogenerated from man page /usr/share/man/man6/kumppa.6x.gz
complete -c kumppa -o visual --description 'Specify which visual to use.'
complete -c kumppa -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c kumppa -o root --description 'Draw on the root window.'
complete -c kumppa -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c kumppa -o speed --description 'Density.   0. 0001 - 0. 2.   Default: 0. 1.'
complete -c kumppa -o random -o no-random --description 'Whether to randomize.'
complete -c kumppa -o dbuf -o no-dbuf --description 'Whether to double buffer.'
complete -c kumppa -o fps --description 'Display the current frame rate and CPU load.'

