# lament
# Autogenerated from man page /usr/share/man/man6/lament.6x.gz
complete -c lament -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c lament -o root --description 'Draw on the root window.'
complete -c lament -o install --description 'Install a private colormap for the window.'
complete -c lament -o visual --description 'Specify which visual to use.'
complete -c lament -o texture --description 'Use texture maps.   This is the default.'
complete -c lament -o no-texture --description 'Do not use texture maps.   This is boring and wrong.'
complete -c lament -o wireframe --description 'Only draw outlines.'
complete -c lament -o delay --description 'How long to pause between frames.   Default is 20000, or 0. 02 second.'
complete -c lament -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

