# lcdscrub
# Autogenerated from man page /usr/share/man/man6/lcdscrub.6x.gz
complete -c lcdscrub -o visual --description 'Specify which visual to use.'
complete -c lcdscrub -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c lcdscrub -o root --description 'Draw on the root window.'
complete -c lcdscrub -o delay --description 'Per-frame delay, in microseconds.   Default: 1000000 (1 second. ).'
complete -c lcdscrub -o spread --description 'Distance between lines.   Default 8.'
complete -c lcdscrub -o cycles --description 'Steps before switching display mode.   Default 60.'
complete -c lcdscrub -o fps --description 'Display the current frame rate and CPU load.'

