# linux32
# Autogenerated from man page /usr/share/man/man1/linux32.1.gz
complete -c linux32 -l list --description 'List the architectures that setarch knows about.'
complete -c linux32 -l 'uname-2.6' --description 'Causes the program to see a kernel version number beginning with 2. 6.'
complete -c linux32 -s v -l verbose --description 'Be verbose.'
complete -c linux32 -s 3 -l 3gb --description 'Specifies that processes should use a maximum of 3GB of address space on syst…'
complete -c linux32 -l 4gb --description 'Ignored (for backward compatibility only).'
complete -c linux32 -s B -l 32bit --description 'Turns on ADDR_LIMIT_32BIT.'
complete -c linux32 -s F -l fdpic-funcptrs --description 'Userspace function pointers point to descriptors (turns on FDPIC_FUNCPTRS).'
complete -c linux32 -s I -l short-inode --description 'Turns on SHORT_INODE.'
complete -c linux32 -s L -l addr-compat-layout --description 'Changes the way virtual memory is allocated (turns on the ADDR_COMPAT_LAYOUT).'
complete -c linux32 -s R -l addr-no-randomize --description 'Disables randomization of the virtual address space (turns on ADDR_NO_RANDOMI…'
complete -c linux32 -s S -l whole-seconds --description 'Turns on WHOLE_SECONDS.'
complete -c linux32 -s T -l sticky-timeouts --description 'Turns on STICKY_TIMEOUTS.'
complete -c linux32 -s X -l read-implies-exec --description 'Turns on READ_IMPLIES_EXEC.'
complete -c linux32 -s Z -l mmap-page-zero --description 'Turns on MMAP_PAGE_ZERO.'
complete -c linux32 -s V -l version --description 'Display version information and exit.'
complete -c linux32 -s h -l help --description 'Display help text and exit.'

