# lockward
# Autogenerated from man page /usr/share/man/man6/lockward.6x.gz
complete -c lockward -o visual --description 'Specify which visual to use.'
complete -c lockward -o window --description 'Draw on a newly-created window (default).'
complete -c lockward -o root --description 'Draw on the root window.'
complete -c lockward -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (50 frames/sec).'
complete -c lockward -o blink -o no-blink --description 'Enables/disables the blinking effects.   Default: Enabled.'
complete -c lockward -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c lockward -o rotateidle-max --description 'The minimum and maximum time each spinner will sit idle, in milliseconds.'
complete -c lockward -o blinkidle-max --description 'The minimum and maximum time between blinking effects, in milliseconds.'
complete -c lockward -o rotateidle-min --description '.'
complete -c lockward -o blinkidle-min --description '.'
complete -c lockward -o blinkdwell-min --description '.'
complete -c lockward -o blinkdwell-max --description 'The minimum and maximum dwell time for the blinking effects, in milliseconds.'

