# loop
# Autogenerated from man page /usr/share/man/man6/loop.6x.gz
complete -c loop -o visual --description 'Specify which visual to use.'
complete -c loop -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c loop -o root --description 'Draw on the root window.'
complete -c loop -o cycles --description 'Timeout.   0 - 8000.   Default: 1600.'
complete -c loop -o delay --description 'Per-frame delay, in microseconds.   Default: 100000 (0. 10 seconds. ).'
complete -c loop -o ncolors --description 'Number of Colors.   Default: 15.'
complete -c loop -o size --description 'Size.   -50 - 50.   Default: -12.'
complete -c loop -o fps --description 'Display the current frame rate and CPU load.'

