# lvdisplay
# Autogenerated from man page /usr/share/man/man8/lvdisplay.8.gz
complete -c lvdisplay -l all --description 'Include information in the output about internal Logical Volumes that are com…'
complete -c lvdisplay -s C -l columns --description 'Display output in columns, the equivalent of lvs(8).'
complete -c lvdisplay -s c -l colon --description 'Generate colon separated output for easier parsing in scripts or programs.  N.'
complete -c lvdisplay -l 'columns.' --description '.'
complete -c lvdisplay -s m -l maps --description 'Display the mapping of logical extents to physical volumes and physical exten…'

