# lvm-lvpoll
# Autogenerated from man page /usr/share/man/man8/lvm-lvpoll.8.gz
complete -c lvm-lvpoll -l polloperation --description 'Mandatory option.  pvmove refers to a pvmove operation that is moving data.'
complete -c lvm-lvpoll -l abort --description 'Abort pvmove in progress.   See pvmove(8).'
complete -c lvm-lvpoll -l handlemissingpvs --description 'Used when the polling operation needs to handle missing PVs to be able to con…'
complete -c lvm-lvpoll -s i -l interval --description 'Report progress at regular intervals.'

