# lvresize
# Autogenerated from man page /usr/share/man/man8/lvresize.8.gz
complete -c lvresize -s f -l force --description 'Force resize without prompting even when it may cause data loss.'
complete -c lvresize -s n -l nofsck --description 'Do not perform fsck before resizing filesystem when filesystem requires it.'
complete -c lvresize -s r -l resizefs --description 'Resize underlying filesystem together with the logical volume using fsadm(8).'
complete -c lvresize -s l -l extents --description 'Change or set the logical volume size in units of logical extents.'
complete -c lvresize -s L -l size --description 'Change or set the logical volume size in units of megabytes.'
complete -c lvresize -s i -l stripes --description 'Gives the number of stripes to use when extending a Logical Volume.'
complete -c lvresize -l poolmetadatasize --description 'Change or set the thin pool metadata logical volume size.'
complete -c lvresize -s I -l stripesize --description 'Gives the number of kilobytes for the granularity of the stripes.'
complete -c lvresize -l noudevsync --description 'Disable udev synchronisation.'

