# lvremove
# Autogenerated from man page /usr/share/man/man8/lvremove.8.gz
complete -c lvremove -s f -l force --description 'Remove active logical volumes without confirmation.'
complete -c lvremove -l noudevsync --description 'Disable udev synchronisation.'

