# lvreduce
# Autogenerated from man page /usr/share/man/man8/lvreduce.8.gz
complete -c lvreduce -s f -l force --description 'Force size reduction without prompting even when it may cause data loss.'
complete -c lvreduce -s l -l extents --description 'Reduce or set the logical volume size in units of logical extents.'
complete -c lvreduce -s L -l size --description 'Reduce or set the logical volume size in units of megabytes.'
complete -c lvreduce -s n -l nofsck --description 'Do not perform fsck before resizing filesystem when filesystem requires it.'
complete -c lvreduce -l noudevsync --description 'Disable udev synchronisation.'
complete -c lvreduce -s r -l resizefs --description 'Resize underlying filesystem together with the logical volume using fsadm (8).'

