# lvs
# Autogenerated from man page /usr/share/man/man8/lvs.8.gz
complete -c lvs -l aligned --description 'Use with --separator to align the output columns.'
complete -c lvs -l binary --description 'Use binary values "0" or "1" instead of descriptive literal values for column…'
complete -c lvs -l all --description 'Include information in the output about internal Logical Volumes that are com…'
complete -c lvs -l nameprefixes --description 'Add an "LVM2_" prefix plus the field name to the output.'
complete -c lvs -l noheadings --description 'Suppress the headings line that is normally the first line of output.'
complete -c lvs -l nosuffix --description 'Suppress the suffix on output sizes.'
complete -c lvs -s o -l options --description 'Comma-separated ordered list of columns.'
complete -c lvs -l segments --description 'otherwise any "lv_" prefixes are optional.'
complete -c lvs -s O -l sort --description 'Comma-separated ordered list of columns to sort by.'
complete -c lvs -l rows --description 'Output columns as rows.'
complete -c lvs -s S -l select --description 'Display only rows that match Selection criteria.'
complete -c lvs -l separator --description 'String to use to separate each column.   Useful if grepping the output.'
complete -c lvs -l unbuffered --description 'Produce output immediately without sorting or aligning the columns properly.'
complete -c lvs -l units --description 'All sizes are output in these units: (h)uman-readable, (b)ytes, (s)ectors, (k…'
complete -c lvs -l unquoted --description 'When used with --nameprefixes, output values in the field=value pairs are not…'

