# MAKEDEV
# Autogenerated from man page /usr/share/man/man8/MAKEDEV.8.gz
complete -c MAKEDEV -s n --description 'Do not actually update the devices, just print the actions that would be perf…'
complete -c MAKEDEV -s d --description 'Delete the devices.   The main use for this flag is by  MAKEDEV itself.'
complete -c MAKEDEV -s v --description 'Be verbose.   Print out the actions as they are performed.'

