# mate-panel
# Autogenerated from man page /usr/share/man/man1/mate-panel.1.gz
complete -c mate-panel -l replace --description 'Replace a currently running instance of mate-panel.'
complete -c mate-panel -l reset --description 'Reset the panel configuration to the default setting.'
complete -c mate-panel -l run-dialog --description 'Open the "Run Application" dialog, also accessible by pressing ALT+F2.'
complete -c mate-panel -l display --description 'X display to use.'
complete -c mate-panel -s '?' -s h -l help --description 'Print standard command line options.'

