# mate-panel-test-applets
# Autogenerated from man page /usr/share/man/man1/mate-panel-test-applets.1.gz
complete -c mate-panel-test-applets -l iid --description 'Specify an applet IID to load.'
complete -c mate-panel-test-applets -l prefs-path --description 'Specify a gsettings path in which the applet preferences should be stored.'
complete -c mate-panel-test-applets -l size --description 'Specify the initial size of the applet (xx-small, medium, large etc. ).'
complete -c mate-panel-test-applets -l orient --description 'Specify the initial orientation of the applet (top, bottom, left or right).'
complete -c mate-panel-test-applets -l display --description 'X display to use.'
complete -c mate-panel-test-applets -s '?' -s h -l help --description 'Print standard command line options.'

