# mawk
# Autogenerated from man page /usr/share/man/man1/mawk.1.gz
complete -c mawk -s f --description 'Program text is read from file instead of from the command line.'
complete -c mawk -s v --description 'assigns   value to program variable  R var .'
complete -c mawk -s '\\' --description 'indicates the unambiguous end of options.'
complete -c mawk -s W --description 'writes an assembler like listing of the internal representation of the progra…'
complete -c mawk -s F --description 'sets the field separator, FS, to  value .'
complete -c mawk -o '1.1e4' --description 'computations are done in floating point arithmetic.'

