# memscroller
# Autogenerated from man page /usr/share/man/man6/memscroller.6x.gz
complete -c memscroller -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c memscroller -o root --description 'Draw on the root window.'
complete -c memscroller -o install --description 'Install a private colormap for the window.'
complete -c memscroller -o visual --description 'Specify which visual to use.'
complete -c memscroller -o color --description 'Render each three bytes of memory as R, G, B.   This is the default.'
complete -c memscroller -o mono --description 'Render each byte of memory in shades of green.'
complete -c memscroller -o ram --description 'Read from the process\'s address space.   This is the default.'
complete -c memscroller -o random --description 'Instead of reading from memory, generate random numbers.'
complete -c memscroller -o filename --description 'Instead of reading from memory, read from the given file until EOF, then re-o…'
complete -c memscroller -o delay --description 'How much of a delay should be introduced between steps of the animation.'
complete -c memscroller -o fps --description 'Display the current frame rate and CPU load.'

