# menger
# Autogenerated from man page /usr/share/man/man6/menger.6x.gz
complete -c menger -o visual --description 'Specify which visual to use.'
complete -c menger -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c menger -o root --description 'Draw on the root window.'
complete -c menger -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c menger -o speed --description 'Number of frames before changing shape.   Default: 150.'
complete -c menger -o depth --description 'Max depth to descend.   Default: 3.'
complete -c menger -o wander -o no-wander --description 'Whether the object should wander around the screen.'
complete -c menger -o spin --description 'Around which axes should the object spin?.'
complete -c menger -o no-spin --description 'None.'
complete -c menger -o wireframe --description 'Render in wireframe instead of solid.'
complete -c menger -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

