# metacity
# Autogenerated from man page /usr/share/man/man1/metacity.1.gz
complete -c metacity -l display --description 'Connect to X display DISPLAY.'
complete -c metacity -l replace --description 'a window manager which is running is replaced by metacity.'
complete -c metacity -l sm-client-id --description 'Specify a session management ID.'
complete -c metacity -l sm-disable --description 'Disable the session management.'
complete -c metacity -l sm-save-file --description 'Load a session from FILENAME.'
complete -c metacity -l sync --description 'Make X calls synchronous.'
complete -c metacity -l composite --description 'Turn compositing on.'
complete -c metacity -l no-composite --description 'Turn compositing off.'
complete -c metacity -l no-force-fullscreen --description 'Don\'t make fullscreen windows that are maximized and have no decorations.'
complete -c metacity -l version --description 'Print the version number.'
complete -c metacity -s '?' -l help --description 'Show summary of options.'

