# mintstick
# Autogenerated from man page /usr/share/man/man1/mintstick.1.gz
complete -c mintstick -l debug --description '        show status and debug messages.'
complete -c mintstick -l help --description '        print a message with basic usage information.'
complete -c mintstick -s m -s i -l iso --description '        Write an . img or . iso file to a USB key.'
complete -c mintstick -s u -l usb -s f --description '        Format a USB key.'

