# ModemManager
# Autogenerated from man page /usr/share/man/man8/ModemManager.8.gz
complete -c ModemManager -l version --description 'Print the ModemManager software version and exit.'
complete -c ModemManager -l help --description 'Print ModemManager\'s available options and exit.'
complete -c ModemManager -l debug --description 'Runs ModemManager with "DEBUG" log level and without daemonizing.'
complete -c ModemManager -l log-level --description 'Sets how much information ModemManager sends to the log destination (usually …'
complete -c ModemManager -l log-file --description 'Specify location of the file where ModemManager will dump its log messages, i…'
complete -c ModemManager -l timestamps --description 'Include absolute timestamps in the log output.'
complete -c ModemManager -l relative-timestamps --description 'Include timestamps, relative to the start time of the daemon, in the log outp…'

