# moebius
# Autogenerated from man page /usr/share/man/man6/moebius.6x.gz
complete -c moebius -o visual --description 'Specify which visual to use.'
complete -c moebius -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c moebius -o root --description 'Draw on the root window.'
complete -c moebius -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. ).'
complete -c moebius -o solidmoebius --description 'Solid Floor.'
complete -c moebius -o wireframe --description 'Render in wireframe instead of solid.'
complete -c moebius -o noants -o no-noants --description 'Draw Ants.   Boolean.'
complete -c moebius -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

