# moebiusgears
# Autogenerated from man page /usr/share/man/man6/moebiusgears.6x.gz
complete -c moebiusgears -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c moebiusgears -o root --description 'Draw on the root window.'
complete -c moebiusgears -o install --description 'Install a private colormap for the window.'
complete -c moebiusgears -o visual --description 'Specify which visual to use.'
complete -c moebiusgears -o delay --description 'The delay between frames of the animation, in microseconds.'
complete -c moebiusgears -o speed --description 'Larger numbers mean run faster.   Default: 1. 0.'
complete -c moebiusgears -o no-spin --description 'Don\'t rotate the object.'
complete -c moebiusgears -o no-wander --description 'Don\'t wander the object around the screen.'
complete -c moebiusgears -o no-roll --description 'Don\'t slowly roll the moebius strip inside out.'
complete -c moebiusgears -o count --description 'How many gears to draw.   Default: 17.   Minimum 11, must be odd.'
complete -c moebiusgears -o teeth --description 'How many teeth to draw on each draw.   Default: 15.   Minimum 7, must be odd.'
complete -c moebiusgears -o wireframe --description 'Render in wireframe instead of solid.'
complete -c moebiusgears -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

