# moire
# Autogenerated from man page /usr/share/man/man6/moire.6x.gz
complete -c moire -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c moire -o root --description 'Draw on the root window.'
complete -c moire -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c moire -o install --description 'Install a private colormap for the window.'
complete -c moire -o visual --description 'Specify which visual to use.'
complete -c moire -o delay --description 'How long to wait before starting over.   Default 5 seconds.'
complete -c moire -o random --description 'Whether to ignore the foreground/background colors, and pick them randomly in…'
complete -c moire -o offset --description 'The maximum random radius increment to use.'
complete -c moire -o ncolors --description 'How many colors should be allocated in the color ramp (note that this value i…'
complete -c moire -o fps --description 'Display the current frame rate and CPU load.'

