# moire2
# Autogenerated from man page /usr/share/man/man6/moire2.6x.gz
complete -c moire2 -o visual --description 'Specify which visual to use.'
complete -c moire2 -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c moire2 -o root --description 'Draw on the root window.'
complete -c moire2 -o delay --description 'Per-frame delay, in microseconds.   Default: 50000 (0. 05 seconds. ).'
complete -c moire2 -o ncolors --description 'Number of Colors.   Default: 150.'
complete -c moire2 -o thickness --description 'Thickness of lines, in pixels.   Default: 0.'
complete -c moire2 -o fps --description 'Display the current frame rate and CPU load.'

