# morph3d
# Autogenerated from man page /usr/share/man/man6/morph3d.6x.gz
complete -c morph3d -o visual --description 'Specify which visual to use.'
complete -c morph3d -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c morph3d -o root --description 'Draw on the root window.'
complete -c morph3d -o count --description '0 - 20.   Default: 0.'
complete -c morph3d -o delay --description 'Per-frame delay, in microseconds.   Default: 40000 (0. 04 seconds. ).'
complete -c morph3d -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

