# mountain
# Autogenerated from man page /usr/share/man/man6/mountain.6x.gz
complete -c mountain -o visual --description 'Specify which visual to use.'
complete -c mountain -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c mountain -o root --description 'Draw on the root window.'
complete -c mountain -o count --description 'Count. 	0 - 100.   Default: 30.'
complete -c mountain -o delay --description 'Per-frame delay, in microseconds.   Default: 1000 (0. 001 seconds. ).'
complete -c mountain -o ncolors --description 'Number of colors.   Default: 64.'
complete -c mountain -o fps --description 'Display the current frame rate and CPU load.'

