# muffin
# Autogenerated from man page /usr/share/man/man1/muffin.1.gz
complete -c muffin -l display --description 'Connect to X display DISPLAY.'
complete -c muffin -l replace --description 'a window manager which is running is replaced by muffin.'
complete -c muffin -l sm-client-id --description 'Specify a session management ID.'
complete -c muffin -l sm-disable --description 'Disable the session management.'
complete -c muffin -l sm-save-file --description 'Load a session from FILENAME.'
complete -c muffin -l version --description 'Print the version number.'
complete -c muffin -s '?' -l help --description 'Show summary of options.'

