# munch
# Autogenerated from man page /usr/share/man/man6/munch.6x.gz
complete -c munch -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c munch -o root --description 'Draw on the root window.'
complete -c munch -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c munch -o install --description 'Install a private colormap for the window.'
complete -c munch -o visual --description 'Specify which visual to use.'
complete -c munch -o delay --description 'The delay between steps of the animation, in microseconds.   Default: 2500.'
complete -c munch -o xor --description 'Use the XOR drawing function.   This is the default.'
complete -c munch -o no-xor --description 'Don\'t use the XOR drawing function.'
complete -c munch -o clear --description 'Number of squares to misdraw before clearing the display.   Default: 65.'
complete -c munch -o simul --description 'Number of squares to misdraw simultaneously.   Default: 5.'
complete -c munch -o classic --description 'Draw classic munching squares only.'
complete -c munch -o mismunch --description 'Draw "mismunch" only.'
complete -c munch -o random --description 'Do one or the other.'
complete -c munch -o fps --description 'Display the current frame rate and CPU load.'

