# native2ascii
# Autogenerated from man page /usr/share/man/man1/native2ascii.1.gz
complete -c native2ascii -o reverse --description 'br Perform the reverse operation: Converts a file encoded in ISO-8859-1 with …'
complete -c native2ascii -o encoding --description 'br Specifies the name of the character encoding to be used by the conversion …'
complete -c native2ascii -o Joption --description '.'

