# ndiswrapper
# Autogenerated from man page /usr/share/man/man8/ndiswrapper.8.gz
complete -c ndiswrapper -s i --description 'installs new Windows XP driver, where <inf file> is full path to INF file for…'
complete -c ndiswrapper -s l --description 'lists the currently installed drivers.'
complete -c ndiswrapper -s e --description 'removes an installed Windows XP driver named <driver>.'
complete -c ndiswrapper -s m --description 'writes an alias for wlan0 (default wireless device) into module configuration…'

