# ntp-wait
# Autogenerated from man page /usr/share/man/man8/ntp-wait.8.gz
complete -c ntp-wait -s f --description 'Force hard failure if state is unknown.'
complete -c ntp-wait -s n --description 'Number of tries before giving up (default 1000 = 10min+).'
complete -c ntp-wait -s s --description 'Seconds to sleep between tries (default 6s = 10/min).'
complete -c ntp-wait -s v --description 'Be verbose.'

