# ntpdate
# Autogenerated from man page /usr/share/man/man8/ntpdate.8.gz
complete -c ntpdate -s a --description 'Enable the authentication function and specify the key identifier to be used …'
complete -c ntpdate -s B --description 'Force the time to always be slewed using the adjtime() system call, even if t…'
complete -c ntpdate -s b --description 'Force the time to be stepped using the settimeofday() system call, rather tha…'
complete -c ntpdate -s d --description 'Enable the debugging mode, in which ntpdate will go through all the steps, bu…'
complete -c ntpdate -s e --description 'Specify the processing delay to perform an authentication function as the val…'
complete -c ntpdate -s k --description 'Specify the path for the authentication key file as the string keyfile.'
complete -c ntpdate -s o --description 'Specify the NTP version for outgoing packets as the integer version, which ca…'
complete -c ntpdate -s p --description 'Specify the number of samples to be acquired from each server as the integer …'
complete -c ntpdate -s q --description 'Query only - don\'t set the clock.'
complete -c ntpdate -s s --description 'Divert logging output from the standard output (default) to the system syslog…'
complete -c ntpdate -s t --description 'Specify the maximum time waiting for a server response as the value timeout, …'
complete -c ntpdate -s u --description 'Direct ntpdate to use an unprivileged port for outgoing packets.'
complete -c ntpdate -s v --description 'Be verbose.'

