# ntpdc
# Autogenerated from man page /usr/share/man/man1/ntpdc.1.gz
complete -c ntpdc -s 4 --description 'Force DNS resolution of following host names on the command line to the IPv4 …'
complete -c ntpdc -s 6 --description 'Force DNS resolution of following host names on the command line to the IPv6 …'
complete -c ntpdc -s c --description 'The following argument is interpreted as an interactive format command and is…'
complete -c ntpdc -s i --description 'Force ntpdc to operate in interactive mode.'
complete -c ntpdc -s l --description 'Obtain a list of peers which are known to the server(s).'
complete -c ntpdc -s n --description 'Output all host addresses in dotted-quad numeric format rather than convertin…'
complete -c ntpdc -s p --description 'Print a list of the peers known to the server as well as a summary of their s…'
complete -c ntpdc -s s --description 'Print a list of the peers known to the server as well as a summary of their s…'

