# ntpq
# Autogenerated from man page /usr/share/man/man1/ntpq.1.gz
complete -c ntpq -s 4 --description 'Force DNS resolution of following host names on the command line to the IPv4 …'
complete -c ntpq -s 6 --description 'Force DNS resolution of following host names on the command line to the IPv6 …'
complete -c ntpq -s c --description 'The following argument is interpreted as an interactive format command and is…'
complete -c ntpq -s i --description 'Force ntpq to operate in interactive mode.'
complete -c ntpq -s n --description 'Output all host addresses in dotted-quad numeric format rather than convertin…'
complete -c ntpq -s p --description 'Print a list of the peers known to the server as well as a summary of their s…'

