# ntpsweep
# Autogenerated from man page /usr/share/man/man1/ntpsweep.1.gz
complete -c ntpsweep -l help --description 'Print this short help text and exit.'
complete -c ntpsweep -l host --description 'Speficy a single host, bypassing the need for a hosts file.'
complete -c ntpsweep -l peers --description 'List all peers a host synchronizes to.'
complete -c ntpsweep -l strip --description 'Strip <string> from hostnames.'

