# ntptime
# Autogenerated from man page /usr/share/man/man8/ntptime.8.gz
complete -c ntptime -s c --description 'Display the execution time of ntptime itself.'
complete -c ntptime -s e --description 'Specify estimated error, in microseconds.'
complete -c ntptime -s f --description 'Specify frequency offset, in parts per million.'
complete -c ntptime -s h --description 'Display help information.'
complete -c ntptime -s m --description 'Specify max possible errors, in microseconds.'
complete -c ntptime -s o --description 'Specify clock offset, in microseconds.'
complete -c ntptime -s r --description 'Display Unix and NTP times in raw format.'
complete -c ntptime -s s --description 'Specify clock status.  Better know what you are doing.'
complete -c ntptime -s t --description 'Specify time constant, an integer in the range 0-10.'

