# ntptrace
# Autogenerated from man page /usr/share/man/man1/ntptrace.1.gz
complete -c ntptrace -s m --description 'Sets the number of server hops to follow (default = 99).'
complete -c ntptrace -s n --description 'Turns off the printing of host names; instead, host IP addresses are given.'

