# odbcinst
# Autogenerated from man page /usr/share/man/man1/odbcinst.1.gz
complete -c odbcinst -s i --description 'option.'
complete -c odbcinst -s l --description 'is used) or to $HOME/. odbc.'
complete -c odbcinst -o 'h).' --description 'Uninstalling Uninstalling a driver is done with the command odbcinst -u -d -n…'
complete -c odbcinst -s h --description 'are used with.'
complete -c odbcinst -s s --description 'to specify which  odbc. ini file to configure.'

