# ods-server
# Autogenerated from man page /usr/share/man/man1/ods-server.1.gz
complete -c ods-server -s h -l help --description 'show this help message and exit.'
complete -c ods-server -s l -l local --description 'ADDRESS of Bluetooth adapter to listen on.  Default is 00:00:00:00:00:00.'
complete -c ods-server -s p -l pairing --description 'Require remote devices to be paired before allowing them to connect.'
complete -c ods-server -s r -l readonly --description 'Disallow any write operations.  Allowed by default.'
complete -c ods-server -s t -l thumbnails --description 'Require remote device to send thumbnails when using Imaging (BIP) server.'
complete -c ods-server -s a -l ask-to-accept --description 'Prompt user to accept or reject every file.'

