# open
# Autogenerated from man page /usr/share/man/man1/open.1.gz
complete -c open -s c -l console --description 'Use the given VT number and not the first available.'
complete -c open -s f -l force --description 'Force opening a VT without checking whether it is already in use;.'
complete -c open -s e -l exec --description 'Directly execute the given command, without forking.'
complete -c open -s s -l switch --description 'Switch to the new VT when starting the command.'
complete -c open -s u -l user --description 'Figure out the owner of the current VT, and run login as that user.'
complete -c open -s l -l login --description 'Make the command a login shell.'
complete -c open -s v -l verbose --description 'Be a bit more verbose;.'
complete -c open -s w -l wait --description 'wait for command to complete.'
complete -c open -s V -l version --description 'print program version and exit;.'
complete -c open -s h -l help --description 'show this text and exit.'

