# pdfinfo
# Autogenerated from man page /usr/share/man/man1/pdfinfo.1.gz
complete -c pdfinfo -s f --description 'Specifies the first page to examine.'
complete -c pdfinfo -s l --description 'Specifies the last page to examine.'
complete -c pdfinfo -o box --description 'Prints the page box bounding boxes: MediaBox, CropBox, BleedBox, TrimBox, and…'
complete -c pdfinfo -o meta --description 'Prints document-level metadata.'
complete -c pdfinfo -o js --description 'Prints all JavaScript in the PDF.'
complete -c pdfinfo -o rawdates --description 'Prints the raw (undecoded) date strings, directly from the PDF file.'
complete -c pdfinfo -o enc --description 'Sets the encoding to use for text output.  This defaults to "UTF-8".'
complete -c pdfinfo -o listenc --description 'Lits the available encodings.'
complete -c pdfinfo -o opw --description 'Specify the owner password for the PDF file.'
complete -c pdfinfo -o upw --description 'Specify the user password for the PDF file.'
complete -c pdfinfo -s v --description 'Print copyright and version information.'
complete -c pdfinfo -s h --description 'Print usage information.  ( -help and.'
complete -c pdfinfo -l help --description 'are equivalent. ) EXIT CODES The Xpdf tools use the following exit codes:.'

