# pedal
# Autogenerated from man page /usr/share/man/man6/pedal.6x.gz
complete -c pedal -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c pedal -o root --description 'Draw on the root window.'
complete -c pedal -o foreground --description 'The color for the foreground.   Default is white.'
complete -c pedal -o background --description 'The color for the background.   Default is black.'
complete -c pedal -o delay --description 'The number of seconds to pause between each picture.'
complete -c pedal -o maxlines --description 'The maximum number of lines in the drawing.'
complete -c pedal -o fps --description 'Display the current frame rate and CPU load.'

