# penetrate
# Autogenerated from man page /usr/share/man/man6/penetrate.6x.gz
complete -c penetrate -o display --description 'Specifies which X display we should use.'
complete -c penetrate -o root --description 'Draw on the root window.'
complete -c penetrate -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c penetrate -o install --description 'Install a private colormap for the window.'
complete -c penetrate -o noinstall --description 'Don\'t install a private colormap for the window.'
complete -c penetrate -o visual --description 'Specify which visual to use.'
complete -c penetrate -o foreground --description 'Specifies the default foreground color.'
complete -c penetrate -o background --description 'Specifies the default background color.'
complete -c penetrate -o bgrowth --description 'Specifies the growth rate of the bomb explosions.'
complete -c penetrate -o lrate --description 'Set the initial rate of laser fire.'
complete -c penetrate -o smart --description 'Have the computer player skip the learning process.'
complete -c penetrate -o fps --description 'Display the current frame rate and CPU load.'

