# penrose
# Autogenerated from man page /usr/share/man/man6/penrose.6x.gz
complete -c penrose -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c penrose -o root --description 'Draw on the root window.'
complete -c penrose -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c penrose -o install --description 'Install a private colormap for the window.'
complete -c penrose -o visual --description 'Specify which visual to use.'
complete -c penrose -o ncolors --description 'How many colors should be used (if possible).   Default 64.'
complete -c penrose -o size --description 'How big the tiles should be.   Default 40 pixels.'
complete -c penrose -o delay --description 'How long (in 1/1,000,000\'ths of a second) to wait between drawing each tile.'
complete -c penrose -o no-ammann --description 'Whether Ammann lines should be added.'
complete -c penrose -o ammann --description '.'
complete -c penrose -o fps --description 'Display the current frame rate and CPU load.'

