# pg
# Autogenerated from man page /usr/share/man/man1/pg.1.gz
complete -c pg -s c --description 'Clear the screen before a page is displayed, if the terminfo entry for the te…'
complete -c pg -s e --description 'Do not pause and display . SM (EOF) at the end of a file.'
complete -c pg -s f --description 'Do not split long lines.'
complete -c pg -s n --description 'Without this option, commands must be terminated by a newline character.'
complete -c pg -s p --description 'Instead of the normal prompt R : ,  string is displayed.'
complete -c pg -s r --description 'Disallow the shell escape.'
complete -c pg -s s --description 'Print messages in  standout mode, if the terminfo entry for the terminal prov…'
complete -c pg -s V -l version --description 'Disaplay version information and exit.'
complete -c pg -s h -l help --description 'Display help text and exit.'

