# photopile
# Autogenerated from man page /usr/share/man/man6/photopile.6x.gz
complete -c photopile -o visual --description 'Specify which visual to use.'
complete -c photopile -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c photopile -o root --description 'Draw on the root window.'
complete -c photopile -o count --description 'How many images to display.   Default 7.'
complete -c photopile -o scale --description 'Size of images in relation to the size of the window.   Default 0. 4.'
complete -c photopile -o maxTilt --description 'Maximum deviation from vertical.   Default 50 degrees.'
complete -c photopile -o duration --description 'Every duration seconds, one of the images will be replaced with a new one.'
complete -c photopile -o speed --description 'Speed up or slow down the animation.   0.'
complete -c photopile -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c photopile -o titles -o no-titles --description 'Whether to display the file names of the images beneath them.   Default: no.'
complete -c photopile -o polaroid -o no-polaroid --description 'Whether to simulate images taken by an instant camera.   Default: yes.'
complete -c photopile -o shadows -o no-shadows --description 'Whether to draw images with drop shadows.   Default: no.'
complete -c photopile -o font --description 'The font to use for the initial loading screen.'
complete -c photopile -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c photopile -o debug --description 'Prints debugging info to stderr.'
complete -c photopile -o wireframe --description 'Another debug mode.'

