# pinion
# Autogenerated from man page /usr/share/man/man6/pinion.6x.gz
complete -c pinion -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c pinion -o root --description 'Draw on the root window.'
complete -c pinion -o install --description 'Install a private colormap for the window.'
complete -c pinion -o visual --description 'Specify which visual to use.'
complete -c pinion -o delay --description 'The delay between frames of the animation, in microseconds: default 15000.'
complete -c pinion -o spin --description 'How fast the gears should spin; default 1. 0.   2. 0 means twice as fast, 0.'
complete -c pinion -o scroll --description 'How fast the gears should scroll past the screen; default 1. 0.    2.'
complete -c pinion -o size --description 'How big the gears should be, on average; default 1. 0.   2.'
complete -c pinion -o max-rpm --description 'If any gear exceeds the maximum RPM, the current gear train is broken there, …'
complete -c pinion -o wireframe --description 'Render in wireframe instead of solid.'
complete -c pinion -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

