# pipes
# Autogenerated from man page /usr/share/man/man6/pipes.6x.gz
complete -c pipes -o visual --description 'Specify which visual to use.'
complete -c pipes -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c pipes -o root --description 'Draw on the root window.'
complete -c pipes -o count --description 'Curved Pipes.'
complete -c pipes -o cycles --description 'Number of pipe systems to draw at once.   Default: 5.'
complete -c pipes -o size --description 'Length of each pipe system.   Default: 500.'
complete -c pipes -o factory --description 'How much gadgetry to create; Useful range is 0-10.   Default: 2.'
complete -c pipes -o delay --description 'How long (in microseconds) to sleep between frames.   Default: 10000.'
complete -c pipes -o fisheye -o no-fisheye --description 'Whether to use a fisheye lens.'
complete -c pipes -o tightturns -o no-tightturns --description 'Whether to allow tight turns.'
complete -c pipes -o db -o no-db --description 'Whether to double-buffer.'
complete -c pipes -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

