# pix
# Autogenerated from man page /usr/share/man/man1/pix.1.gz
complete -c pix -s f -l fullscreen --description 'Start in fullscreen mode.'
complete -c pix -s s -l slideshow --description 'Automatically start a slideshow.'
complete -c pix -l import-photos --description 'Automatically import digital camera photos.'
complete -c pix -l help --description 'Output help information and exit.'
complete -c pix -l version --description 'Output version information and exit.'

