# pm-suspend
# Autogenerated from man page /usr/share/man/man8/pm-suspend.8.gz
complete -c pm-suspend -l quirk-dpms-on --description 'This option forces the video hardware to turn on the screen during resume.'
complete -c pm-suspend -l quirk-dpms-suspend --description 'This option forces the video hardware to turn off the screen when suspending.'
complete -c pm-suspend -l quirk-radeon-off --description 'This option forces Radeon hardware to turn off the display during suspend and…'
complete -c pm-suspend -l quirk-s3-bios --description 'This option calls the video BIOS during S3 resume.'
complete -c pm-suspend -l quirk-s3-mode --description 'This option initializes the video card into a VGA text mode, and then uses th…'
complete -c pm-suspend -l quirk-vbe-post --description 'This option will attempt to reinitialize the video card when resuming from su…'
complete -c pm-suspend -l quirk-vbemode-restore --description 'This option will save and restore the current VESA mode which may be necessar…'
complete -c pm-suspend -l quirk-vbestate-restore --description 'This option saves and restores some low level hardware state which may be inv…'
complete -c pm-suspend -l quirk-vga-mode-3 --description 'This option will try to force the video card into a standard text mode on res…'
complete -c pm-suspend -l quirk-save-pci --description 'Save the PCI config space for the VGA card.'
complete -c pm-suspend -l store-quirks-as-lkw --description 'Save the quirks the video adaptor required by pm-suspend or pm-suspend-hybrid…'

