# polyominoes
# Autogenerated from man page /usr/share/man/man6/polyominoes.6x.gz
complete -c polyominoes -o visual --description 'Specify which visual to use.'
complete -c polyominoes -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c polyominoes -o root --description 'Draw on the root window.'
complete -c polyominoes -o identical -o no-identical --description 'Whether to use identical pieces.'
complete -c polyominoes -o cycles --description 'Duration.   500 - 5000. 	Default: 2000.'
complete -c polyominoes -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c polyominoes -o ncolors --description 'Number of Colors.   Default: 64.'
complete -c polyominoes -o fps --description 'Display the current frame rate and CPU load.'

