# polyhedra
# Autogenerated from man page /usr/share/man/man6/polyhedra.6x.gz
complete -c polyhedra -o visual --description 'Specify which visual to use.'
complete -c polyhedra -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c polyhedra -o root --description 'Draw on the root window.'
complete -c polyhedra -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c polyhedra -o speed --description 'Larger numbers mean run faster.   Default: 1. 0.'
complete -c polyhedra -o duration --description 'How long before switching to a new polyhedron.   Default 12 seconds.'
complete -c polyhedra -o wander -o no-wander --description 'Whether the objects should wander around the screen.'
complete -c polyhedra -o spin -o no-spin --description 'Which axes, if any, to spin around on.'
complete -c polyhedra -o titles -o no-titles --description 'Whether to display text describing each object.'
complete -c polyhedra -o which --description 'Display only one particular object, identified by number, name, or Whthoff sy…'
complete -c polyhedra -o wireframe -o no-wireframe --description 'Render in wireframe instead of solid.'
complete -c polyhedra -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

