# poweroff
# Autogenerated from man page /usr/share/man/man8/poweroff.8.gz
complete -c poweroff -l help --description 'Print a short help text and exit.'
complete -c poweroff -l halt --description 'Halt the machine, regardless of which one of the three commands is invoked.'
complete -c poweroff -s p -l poweroff --description 'Power-off the machine, regardless of which one of the three commands is invok…'
complete -c poweroff -l reboot --description 'Reboot the machine, regardless of which one of the three commands is invoked.'
complete -c poweroff -s f -l force --description 'Force immediate halt, power-off, reboot.  Do not contact the init system.'
complete -c poweroff -s w -l wtmp-only --description 'Only write wtmp shutdown entry, do not actually halt, power-off, reboot.'
complete -c poweroff -s d -l no-wtmp --description 'Do not write wtmp shutdown entry.'
complete -c poweroff -l no-wall --description 'Do not send wall message before halt, power-off, reboot.'

