# providence
# Autogenerated from man page /usr/share/man/man6/providence.6x.gz
complete -c providence -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c providence -o root --description 'Draw on the root window.'
complete -c providence -o install --description 'Install a private colormap for the window.'
complete -c providence -o eye --description 'Draw an eye/$.'
complete -c providence -o visual --description 'Specify which visual to use.'
complete -c providence -o wireframe --description 'Render in wireframe (with hidden line removal) instead of as textured solids.'
complete -c providence -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

