# pulsar
# Autogenerated from man page /usr/share/man/man6/pulsar.6x.gz
complete -c pulsar -o visual --description 'Specify which visual to use.'
complete -c pulsar -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c pulsar -o root --description 'Draw on the root window.'
complete -c pulsar -o light -o no-light --description 'Use Flat Coloring.'
complete -c pulsar -o wire --description 'Render in wireframe instead of solid.'
complete -c pulsar -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c pulsar -o image --description 'The texture map to use.'
complete -c pulsar -o quads --description 'Quad Count.   1 - 50.   Default: 5.'
complete -c pulsar -o fog -o no-fog --description 'Whether to enable fog.'
complete -c pulsar -o texture -o no-texture --description 'Whether to enable texturing.'
complete -c pulsar -o mipmap -o no-mipmap --description 'Whether to enable texture mipmaps.'
complete -c pulsar -o blend -o no-blend --description 'Whether to enable blending.'
complete -c pulsar -o antialias -o no-antialias --description 'Whether to anti-alias lines.'
complete -c pulsar -o texture_quality -o no-texture_quality --description 'Whether to enable texture filtering.'
complete -c pulsar -o do_depth -o no-do_depth --description 'Whether to enable depth buffer.'
complete -c pulsar -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

