# pvchange
# Autogenerated from man page /usr/share/man/man8/pvchange.8.gz
complete -c pvchange -s a -l all --description 'If PhysicalVolumePath is not specified on the command line all physical volum…'
complete -c pvchange -l metadataignore --description 'Ignore or un-ignore metadata areas on this physical volume.'
complete -c pvchange -s u -l uuid --description 'Generate new random UUID for specified physical volumes.'
complete -c pvchange -s x -l allocatable --description 'Enable or disable allocation of physical extents on this physical volume.'

