# pvdisplay
# Autogenerated from man page /usr/share/man/man8/pvdisplay.8.gz
complete -c pvdisplay -s C -l columns --description 'Display output in columns, the equivalent of pvs(8).'
complete -c pvdisplay -s c -l colon --description 'Generate colon separated output for easier parsing in scripts or programs.  N.'
complete -c pvdisplay -s s -l short --description 'Only display the size of the given physical volumes.'
complete -c pvdisplay -s m -l maps --description 'Display the mapping of physical extents to logical volumes and logical extent…'

