# pvs
# Autogenerated from man page /usr/share/man/man8/pvs.8.gz
complete -c pvs -l all --description 'Include information in the output about devices that have not been initialize…'
complete -c pvs -l aligned --description 'Use with --separator to align the output columns.'
complete -c pvs -l binary --description 'Use binary values "0" or "1" instead of descriptive literal values for column…'
complete -c pvs -l nameprefixes --description 'Add an "LVM2_" prefix plus the field name to the output.'
complete -c pvs -l noheadings --description 'Suppress the headings line that is normally the first line of output.'
complete -c pvs -l nosuffix --description 'Suppress the suffix on output sizes.'
complete -c pvs -s o -l options --description 'Comma-separated ordered list of columns.'
complete -c pvs -l segments --description '"pv_" prefixes are optional.   Columns mentioned in vgs(8) can also be chosen.'
complete -c pvs -s S -l select --description 'Display only rows that match Selection criteria.'
complete -c pvs -s O -l sort --description 'Comma-separated ordered list of columns to sort by.'
complete -c pvs -l rows --description 'Output columns as rows.'
complete -c pvs -l separator --description 'String to use to separate each column.   Useful if grepping the output.'
complete -c pvs -l unbuffered --description 'Produce output immediately without sorting or aligning the columns properly.'
complete -c pvs -l units --description 'All sizes are output in these units: (h)uman-readable, (b)ytes, (s)ectors, (k…'
complete -c pvs -l unquoted --description 'When used with --nameprefixes, output values in the field=value pairs are not…'

