# pyhtmlizer
# Autogenerated from man page /usr/share/man/man1/pyhtmlizer.1.gz
complete -c pyhtmlizer -l stylesheet -s s --description 'Links to the stylesheet at <url>.'
complete -c pyhtmlizer -l help --description 'Output help information and exit.'

