# python-config
# Autogenerated from man page /usr/share/man/man1/python-config.1.gz
complete -c python-config -l cflags --description 'print the C compiler flags.'
complete -c python-config -l ldflags --description 'print the flags that should be passed to the linker.'
complete -c python-config -l includes --description 'similar to --cflags but only with -I options (path to python header files).'
complete -c python-config -l libs --description 'similar to --ldflags but only with -l options (used libraries).'
complete -c python-config -l prefix --description 'prints the prefix (base directory) under which python can be found.'
complete -c python-config -l exec-prefix --description 'print the prefix used for executable program directories (such as bin, sbin, …'
complete -c python-config -l extension-suffix --description 'print suffix used for extension modules (including the _d modified for debug …'
complete -c python-config -l configdir --description 'prints the path to the configuration directory under which the Makefile, etc.'
complete -c python-config -l help --description 'print the usage message.'

