# quasicrystal
# Autogenerated from man page /usr/share/man/man6/quasicrystal.6x.gz
complete -c quasicrystal -o visual --description 'Specify which visual to use.'
complete -c quasicrystal -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c quasicrystal -o root --description 'Draw on the root window.'
complete -c quasicrystal -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c quasicrystal -o speed --description 'Animation speed.  2 for twice as fast, 0. 5 for half as fast.'
complete -c quasicrystal -o contrast --description 'Contrast.  Sort of.   Default 30%.'
complete -c quasicrystal -o count --description 'How many planes to use.  Default 17.'
complete -c quasicrystal -o wander -o no-wander --description 'Whether the planes should displace horizontally and vertically.'
complete -c quasicrystal -o spin -o no-spin --description 'Whether the planes should rotate.'
complete -c quasicrystal -o asymmetric --description 'Allow each plane to rotate freely instead of being constrained to an even dis…'
complete -c quasicrystal -o fps -o no-fps --description 'Whether to show a frames-per-second display at the bottom of the screen.'

