# queens
# Autogenerated from man page /usr/share/man/man6/queens.6x.gz
complete -c queens -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c queens -o root --description 'Draw on the root window.'
complete -c queens -o install --description 'Install a private colormap for the window.'
complete -c queens -o visual --description 'Specify which visual to use.'
complete -c queens -o wireframe --description 'Render in wireframe instead of solid.'
complete -c queens -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

