# rdate
# Autogenerated from man page /usr/share/man/man8/rdate.8.gz
complete -c rdate -s 4 --description 'Forces rdate to use IPv4 addresses only.'
complete -c rdate -s 6 --description 'Forces rdate to use IPv6 addresses only.'
complete -c rdate -s a --description 'Use the adjtime 2 call to gradually skew the local time to the remote time ra…'
complete -c rdate -s c --description 'Correct leap seconds.  Sometimes required when synchronizing to an NTP server.'
complete -c rdate -s n --description 'Use SNTP (RFC 2030) instead of the RFC 868 time protocol.'
complete -c rdate -s o --description 'Use port port instead of port 37.'
complete -c rdate -s p --description 'Do not set, just print the remote time.'
complete -c rdate -s s --description 'Do not print the time.'
complete -c rdate -s u --description 'Use UDP instead of TCP as transport.'
complete -c rdate -s v --description 'Verbose output.  Always show the adjustment.'

