# rename
# Autogenerated from man page /usr/share/man/man1/rename.ul.1.gz
complete -c rename -s s -l symlink --description 'Do not rename a symlink but its target.'
complete -c rename -l verbose --description 'Show which files where renamed, if any.'
complete -c rename -l version --description 'Display version information and exit.'
complete -c rename -l help --description 'Display help text and exit.  EXAMPLES Given the files foo1 , .'

