# resolvconf
# Autogenerated from man page /usr/share/man/man8/resolvconf.8.gz
complete -c resolvconf -s a --description 'Add or overwrite the record  IFACE.'
complete -c resolvconf -s d --description 'Delete the record  IFACE.'
complete -c resolvconf -s u --description 'Just run the update scripts (if updating is enabled).'
complete -c resolvconf -o u: --description 'if updating is not enabled, schedule a delayed update.'
complete -c resolvconf -l enable-updates --description 'Set the flag indicating that   resolvconf should run update scripts when invo…'
complete -c resolvconf -l disable-updates --description 'Clear the flag.'
complete -c resolvconf -l updates-are-enabled --description 'Return 0 if the flag is set, otherwise return 1.'

