# ri
# Autogenerated from man page /usr/share/man/man1/ri.1.gz
complete -c ri -l version --description 'Prints the version of ri.  Pp.'
complete -c ri -s T --description '.'
complete -c ri -l no-pager --description 'Send output directly to stdout, rather than to a pager.  Pp.'
complete -c ri -s d --description '.'
complete -c ri -l doc-dir --description 'List of directories from which to source documentation in addition to the sta…'
complete -c ri -s f --description '.'
complete -c ri -l fmt --description '.'
complete -c ri -l format --description 'Format to use when displaying output: Pp ansi, bs, html, plain, simple Pp Use…'
complete -c ri -s i --description '.'
complete -c ri -l interactive --description 'This makes ri go into interactive mode.'
complete -c ri -l list-doc-dirs --description 'List the directories from which ri will source documentation on stdout and ex…'
complete -c ri -l no-standard-docs --description 'Do not include documentation from the Ruby standard library, site_lib, instal…'
complete -c ri -s w --description '.'
complete -c ri -l width --description 'Set the width of the output.'

