# ri2
# Autogenerated from man page /usr/share/man/man1/ri2.3.1.gz
complete -c ri2 -l version --description 'Prints the version of ri2.  Pp.'
complete -c ri2 -s T --description '.'
complete -c ri2 -l no-pager --description 'Send output directly to stdout, rather than to a pager.  Pp.'
complete -c ri2 -s d --description '.'
complete -c ri2 -l doc-dir --description 'List of directories from which to source documentation in addition to the sta…'
complete -c ri2 -s f --description '.'
complete -c ri2 -l fmt --description '.'
complete -c ri2 -l format --description 'Format to use when displaying output: Pp ansi, bs, html, plain, simple Pp Use…'
complete -c ri2 -s i --description '.'
complete -c ri2 -l interactive --description 'This makes ri2 go into interactive mode.'
complete -c ri2 -l list-doc-dirs --description 'List the directories from which ri will source documentation on stdout and ex…'
complete -c ri2 -l no-standard-docs --description 'Do not include documentation from the Ruby standard library, site_lib, instal…'
complete -c ri2 -s w --description '.'
complete -c ri2 -l width --description 'Set the width of the output.'

