# ripples
# Autogenerated from man page /usr/share/man/man6/ripples.6x.gz
complete -c ripples -o visual --description 'Specify which visual to use.'
complete -c ripples -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c ripples -o root --description 'Draw on the root window.'
complete -c ripples -o delay --description 'Per-frame delay, in microseconds.   Default: 50000 (0. 05 seconds. ).'
complete -c ripples -o duration --description 'How long to run before loading a new image.   Default 120 seconds.'
complete -c ripples -o rate --description 'Drizzle.   1 - 100.   Default: 5.'
complete -c ripples -o fluidity --description 'Small Drops.   0 - 16.   Default: 6.'
complete -c ripples -o light --description 'Lighting Effect.   0 - 8.   Default: 0.'
complete -c ripples -o water -o no-water --description 'Grab Screen Image.   Boolean.'
complete -c ripples -o stir -o no-stir --description 'Moving Splashes.   Boolean.'
complete -c ripples -o oily -o no-oily --description 'Psychedelic Colors.   Boolean.'
complete -c ripples -o grayscale --description 'Convert the screen image to grayscale.'
complete -c ripples -o colors --description 'Colors Two.   Default: 200.'
complete -c ripples -o shm -o no-shm --description 'Use Shared Memory.   Boolean.'
complete -c ripples -o fps --description 'Display the current frame rate and CPU load.'

