# rocks
# Autogenerated from man page /usr/share/man/man6/rocks.6x.gz
complete -c rocks -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c rocks -o root --description 'Draw on the root window.'
complete -c rocks -o mono --description 'Make all the rocks the same color.'
complete -c rocks -o ncolors --description 'How many different colors to use.   Default 5.   Colors are chosen randomly.'
complete -c rocks -o install --description 'Install a private colormap for the window.'
complete -c rocks -o visual --description 'Specify which visual to use.'
complete -c rocks -o count --description 'Maximum number of rocks to draw on the screen at once.   Default 100.'
complete -c rocks -o speed --description 'A measure of the speed with which the observer and the rocks pass each other,…'
complete -c rocks -o delay --description 'Number of microseconds to delay between each frame.'
complete -c rocks -o norotate --description 'Don\'t rotate the observer; just fly through the field on the level.'
complete -c rocks -o nomove --description 'Don\'t turn the observer; just fly straight ahead through the field.'
complete -c rocks -o 3d --description 'Do red/blue 3d separations: if you look at the screen with 3d glasses, the ro…'
complete -c rocks -o fps --description 'Display the current frame rate and CPU load.'

