# rorschach
# Autogenerated from man page /usr/share/man/man6/rorschach.6x.gz
complete -c rorschach -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c rorschach -o root --description 'Draw on the root window.'
complete -c rorschach -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c rorschach -o install --description 'Install a private colormap for the window.'
complete -c rorschach -o visual --description 'Specify which visual to use.'
complete -c rorschach -o iterations --description 'How many dots should be drawn each time.   Default 4000.'
complete -c rorschach -o offset --description 'How far apart the dots should be.   Default 4 pixels.'
complete -c rorschach -o xsymmetry --description 'Whether the images should be horizontally symmetrical.   Default true.'
complete -c rorschach -o ysymmetry --description 'Whether the images should be vertically symmetrical.   Default false.'
complete -c rorschach -o erase-speed --description 'This controls the speed at which the screen will be erased.'
complete -c rorschach -o delay --description 'This sets the number of seconds that the figure will be on the screen.'
complete -c rorschach -o fps --description 'Display the current frame rate and CPU load.'

