# rotzoomer
# Autogenerated from man page /usr/share/man/man6/rotzoomer.6x.gz
complete -c rotzoomer -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c rotzoomer -o root --description 'Draw on the root window.'
complete -c rotzoomer -o install --description 'Install a private colormap for the window.'
complete -c rotzoomer -o visual --description 'Specify which visual to use.'
complete -c rotzoomer -o delay --description 'How much of a delay should be introduced between steps of the animation.'
complete -c rotzoomer -o duration --description 'How long to run before loading a new image.   Default 120 seconds.'
complete -c rotzoomer -o move --description 'Make the rectangles should wander around the screen.'
complete -c rotzoomer -o no-move --description 'Make the rectangles be stationary.   This is the default.'
complete -c rotzoomer -s n --description 'How many rectangles to animate simultaneously.   Default 2.'
complete -c rotzoomer -o no-shm --description 'Disable use of the SHM extension, even if it appears to be available.'
complete -c rotzoomer -o fps --description 'Display the current frame rate and CPU load.'

