# route
# Autogenerated from man page /usr/share/man/man8/route.8.gz
complete -c route -s A --description 'use the specified address family (eg `inet\'; use `route --help\' for a full  l…'
complete -c route -s F --description 'operate on the kernel\'s FIB (Forwarding Information Base) routing table.'
complete -c route -s C --description 'operate on the kernel\'s routing cache.'
complete -c route -s v --description 'select verbose operation.'
complete -c route -s n --description 'show numerical addresses instead of trying to determine symbolic host names.'
complete -c route -s e --description 'use  netstat (8)-format for displaying the routing table.'
complete -c route -o net --description 'the  target is a network.'
complete -c route -o host --description 'the  target  is a host.'
complete -c route -o ee --description 'will generate a very long line with all parameters from the routing table.'

