# rubik
# Autogenerated from man page /usr/share/man/man6/rubik.6x.gz
complete -c rubik -o visual --description 'Specify which visual to use.'
complete -c rubik -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c rubik -o root --description 'Draw on the root window.'
complete -c rubik -o count --description 'Count. 	-100 - 100.   Default: -30.'
complete -c rubik -o cycles --description 'Timeout.   0 - 60.   Default: 5.'
complete -c rubik -o delay --description 'Per-frame delay, in microseconds.   Default: 40000 (0. 04 seconds. ).'
complete -c rubik -o size --description 'Size.   -20 - 20.   Default: -6.'
complete -c rubik -o hideshuffling -o no-hideshuffling --description 'Show Shuffling.   Boolean.'
complete -c rubik -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

