# saned
# Autogenerated from man page /usr/share/man/man8/saned.8.gz
complete -c saned -s a --description 'flag requests that saned run in standalone daemon mode.'
complete -c saned -s d --description 'and.'
complete -c saned -s s --description 'flags request that saned run in debug mode (as opposed to inetd (8) daemon mo…'
complete -c saned -o d128 --description 'will request printing of all debug info.'
complete -c saned -s h --description 'flag displays a short help message.'

