# sass-convert
# Autogenerated from man page /usr/share/man/man1/sass-convert.1.gz
complete -c sass-convert -s F -l from --description 'The format to convert from.  Can be css, scss, sass.'
complete -c sass-convert -s T -l to --description 'The format to convert to.  Can be scss or sass.'
complete -c sass-convert -s i -l in-place --description 'Convert a file to its own syntax.'
complete -c sass-convert -s R -l recursive --description 'Convert all the files in a directory.  Requires --from and --to.'
complete -c sass-convert -s '?' -s h -l help --description 'Show this help message.'
complete -c sass-convert -s v -l version --description 'Print the Sass version. SS "Style:".'
complete -c sass-convert -l dasherize --description 'Convert underscores to dashes.'
complete -c sass-convert -l indent --description 'How many spaces to use for each level of indentation.  Defaults to 2.'
complete -c sass-convert -l old --description 'Output the old-style ":prop val" property syntax.'
complete -c sass-convert -s s -l stdin --description 'Read input from standard input instead of an input file.'
complete -c sass-convert -s E -l default-encoding --description 'Specify the default encoding for input files.'
complete -c sass-convert -l unix-newlines --description 'Use Unix-style newlines in written files.  Always true on Unix.'
complete -c sass-convert -l cache-location --description 'The path to save parsed Sass files.  Defaults to . sass-cache.'
complete -c sass-convert -s C -l no-cache --description 'Don\'t cache to sassc files.'
complete -c sass-convert -l trace --description 'Show a full Ruby stack trace on error.'

