# sballs
# Autogenerated from man page /usr/share/man/man6/sballs.6x.gz
complete -c sballs -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c sballs -o root --description 'Draw on the root window.'
complete -c sballs -o install --description 'Install a private colormap for the window.'
complete -c sballs -o visual --description 'Specify which visual to use.'
complete -c sballs -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c sballs -o object --description 'Specify how the spheres are grouped (forming an object).  Objects are:.'
complete -c sballs -o size --description 'Viewport of GL scene is specified size if greater than 32 and less than scree…'
complete -c sballs -o texture --description 'Show a textured background and spheres.  This is the default.'
complete -c sballs -o no-texture --description 'Disables texturing the animation.'
complete -c sballs -o trackmouse --description 'Let the mouse be a joystick to change the view of the animation.'
complete -c sballs -o no-trackmouse --description 'Disables mouse tracking.  This is the default.'
complete -c sballs -o 'no-wander.' --description '.'
complete -c sballs -o wire --description 'Draw a wireframe rendition of the spheres.'

