# schemagen
# Autogenerated from man page /usr/share/man/man1/schemagen.1.gz
complete -c schemagen -s d --description 'br The location where the \\f3schemagen command places processor-generated and…'
complete -c schemagen -o cp --description 'br The location where the \\f3schemagen command places user-specified files.'
complete -c schemagen -o classpath --description 'br The location where the \\f3schemagen command places user-specified files.'
complete -c schemagen -o encoding --description 'br Specifies the encoding to use for \\f3apt or \\f3javac command invocations.'
complete -c schemagen -o episode --description 'br Generates an episode file for separate compilation.'
complete -c schemagen -o version --description 'br Displays release information.'
complete -c schemagen -o help --description '.'

