# seahorse
# Autogenerated from man page /usr/share/man/man1/seahorse.1.gz
complete -c seahorse -s '?' -l help --description 'Show help options.'
complete -c seahorse -l help-all --description 'Show all help options.'
complete -c seahorse -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c seahorse -s v -l version --description 'Version of this application.'
complete -c seahorse -l display --description 'X display to use.'

