# servertool
# Autogenerated from man page /usr/share/man/man1/servertool.1.gz
complete -c servertool -o ORBInitialHost --description 'br This options is required.'
complete -c servertool -o Joption --description '.'

