# setcifsacl
# Autogenerated from man page /usr/share/man/man1/setcifsacl.1.gz
complete -c setcifsacl -s h --description 'Print usage message and exit.'
complete -c setcifsacl -s v --description '.'
complete -c setcifsacl -s a --description '.'
complete -c setcifsacl -s D --description '.'
complete -c setcifsacl -s M --description '.'
complete -c setcifsacl -s S --description '.'

