# shadebobs
# Autogenerated from man page /usr/share/man/man6/shadebobs.6x.gz
complete -c shadebobs -o visual --description 'Specify which visual to use.'
complete -c shadebobs -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c shadebobs -o root --description 'Draw on the root window.'
complete -c shadebobs -o ncolors --description 'Number of Colors.   Default: 64.'
complete -c shadebobs -o count --description 'Count. 	0 - 20.   Default: 4.'
complete -c shadebobs -o delay --description 'Per-frame delay, in microseconds.   Default: 5000 (0. 005 seconds. ).'
complete -c shadebobs -o cycles --description 'Duration.   0 - 100.   Default: 10.'
complete -c shadebobs -o fps --description 'Display the current frame rate and CPU load.'

