# sierpinski
# Autogenerated from man page /usr/share/man/man6/sierpinski.6x.gz
complete -c sierpinski -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c sierpinski -o root --description 'Draw on the root window.'
complete -c sierpinski -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c sierpinski -o install --description 'Install a private colormap for the window.'
complete -c sierpinski -o visual --description 'Specify which visual to use.'
complete -c sierpinski -o ncolors --description 'How many colors should be used (if possible).   Default 64.'
complete -c sierpinski -o cycles --description '.'
complete -c sierpinski -o count --description '.'
complete -c sierpinski -o fps --description 'Display the current frame rate and CPU load.'

