# slidescreen
# Autogenerated from man page /usr/share/man/man6/slidescreen.6x.gz
complete -c slidescreen -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c slidescreen -o root --description 'Draw on the root window.'
complete -c slidescreen -o install --description 'Install a private colormap for the window.'
complete -c slidescreen -o visual --description 'Specify which visual to use.'
complete -c slidescreen -o grid-size --description 'The size of the grid cells.   Default 70 pixels.'
complete -c slidescreen -o ibw --description 'The size of the "gutter" between grid cells.   Default 4 pixel.'
complete -c slidescreen -o increment --description 'How many pixels by which a piece should be moved when sliding to a new  locat…'
complete -c slidescreen -o delay --description 'How much of a delay should be introduced between steps of the animation of th…'
complete -c slidescreen -o delay2 --description 'How much of a delay should be introduced between the end of the motion of one…'
complete -c slidescreen -o duration --description 'How long to run before loading a new image.   Default 120 seconds.'
complete -c slidescreen -o fps --description 'Display the current frame rate and CPU load.'

