# slip
# Autogenerated from man page /usr/share/man/man6/slip.6x.gz
complete -c slip -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c slip -o root --description 'Draw on the root window.'
complete -c slip -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c slip -o install --description 'Install a private colormap for the window.'
complete -c slip -o visual --description 'Specify which visual to use.'
complete -c slip -o ncolors --description 'How many colors should be used (if possible).   Default 200.'
complete -c slip -o count --description 'How many whooziwhatsis to generate.   Default 35.'
complete -c slip -o cycles --description 'How long to frobnicate.   Default 50.'
complete -c slip -o delay --description 'How long we should wait between drawing each step.'
complete -c slip -o fps --description 'Display the current frame rate and CPU load.'

