# sonar
# Autogenerated from man page /usr/share/man/man6/sonar.6x.gz
complete -c sonar -o ping --description 'The list of things to ping, separated by commas or spaces.'
complete -c sonar -o ping-timeout --description 'The amount of time in milliseconds the program will wait for an answer to a p…'
complete -c sonar -o delay --description 'Delay between frames, in microseconds.   Default 20000.'
complete -c sonar -o speed --description 'Less than 1 for slower, greater than 1 for faster.   Default 1.'
complete -c sonar -o sweep-size --description 'How big the glowing sweep area should be.  Default 0. 3.'
complete -c sonar -o font-size --description 'How large the text should be.   Default 10 points.'
complete -c sonar -o no-wobble --description 'Keep the display stationary instead of very slowly wobbling back and forth.'
complete -c sonar -o no-dns --description 'Do not attempt to resolve IP addresses to hostnames.'
complete -c sonar -o no-times --description 'Do not display ping times beneath the host names.'
complete -c sonar -o team-a-name --description 'In simulation mode, the name of team A.'
complete -c sonar -o team-b-name --description 'In simulation mode, the name of team B.'
complete -c sonar -o team-a-count --description 'In simulation mode, the number of bogies on team A.'
complete -c sonar -o team-b-count --description 'In simulation mode, the number of bogies on team B.'
complete -c sonar -o fps --description 'Display the current frame rate, polygon count, and CPU load.'

