# sort-dctrl
# Autogenerated from man page /usr/share/man/man1/sort-dctrl.1.gz
complete -c sort-dctrl -s k -l key-spec --description 'Specify one or more keys for sorting.'
complete -c sort-dctrl -s q -l quiet -l silent --description 'Output nothing to the standard output stream.'
complete -c sort-dctrl -s l -l errorlevel --description 'Set log level to R level .'
complete -c sort-dctrl -s V -l version --description 'Print out version information.'
complete -c sort-dctrl -s C -l copying --description 'Print out the copyright license.'
complete -c sort-dctrl -s h -l help --description 'Print out a help summary.'

