# spellintian
# Autogenerated from man page /usr/share/man/man1/spellintian.1.gz
complete -c spellintian -l picky --description 'Also use the \\*(L"picky\\*(R" data set on top of the regular spelling data set.'
complete -c spellintian -s h -l help --description 'Display usage information and exit.'

