# spheremonics
# Autogenerated from man page /usr/share/man/man6/spheremonics.6x.gz
complete -c spheremonics -o visual --description 'Specify which visual to use.'
complete -c spheremonics -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c spheremonics -o root --description 'Draw on the root window.'
complete -c spheremonics -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c spheremonics -o duration --description 'Duration.   5 - 1000.   Default: 100.'
complete -c spheremonics -o resolution --description 'Resolution.   5 - 100.   Default: 64.'
complete -c spheremonics -o wander -o no-wander --description 'Whether the object should wander around the screen.'
complete -c spheremonics -o spin --description 'Around which axes should the object spin?.'
complete -c spheremonics -o no-spin --description 'Don\'t spin.'
complete -c spheremonics -o wireframe --description 'Render in wireframe instead of solid.'
complete -c spheremonics -o smooth -o no-smooth --description 'Smoothed Lines.   Boolean.'
complete -c spheremonics -o grid -o no-grid --description 'Draw Grid.   Boolean.'
complete -c spheremonics -o bbox -o no-bbox --description 'Draw Bounding Box.   Boolean.'
complete -c spheremonics -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

