# splitdiff
# Autogenerated from man page /usr/share/man/man1/splitdiff.1.gz
complete -c splitdiff -s a --description 'Split out every single file-level patch.'
complete -c splitdiff -s d --description 'Create file names such as a_b. c. patch for a patch that modifies a/b. c.'
complete -c splitdiff -s D --description 'Write output files into subdirectory dir.  Implies -d.'
complete -c splitdiff -s p --description 'Strip the first n components of the pathname to aid comparisons.'
complete -c splitdiff -s E --description 'Don\\*(Aqt use . patch filename extension when writing output files.'
complete -c splitdiff -l help --description 'Display a short usage message.'
complete -c splitdiff -l version --description 'Display the version number of splitdiff.'
complete -c splitdiff -o 'd.' --description '.'

