# splitflap
# Autogenerated from man page /usr/share/man/man6/splitflap.6x.gz
complete -c splitflap -o visual --description 'Specify which visual to use.'
complete -c splitflap -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c splitflap -o root --description 'Draw on the root window.'
complete -c splitflap -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds).'
complete -c splitflap -o speed --description 'Animation speed.   2. 0 means twice as fast, 0. 5 means half as fast.'
complete -c splitflap -o width --description 'Columns of the display.   Default: 22.'
complete -c splitflap -o height --description 'Rows of the display.  Default: 8.'
complete -c splitflap -o mode --description 'Display a 12-hour clock.'
complete -c splitflap -o front -o no-front --description 'When spinning, never spin all the way around or upside down: always face most…'
complete -c splitflap -o wander -o no-wander --description 'Whether the object should wander around the screen.'
complete -c splitflap -o spin --description 'Which axes around which the text should spin.'
complete -c splitflap -o wireframe -o no-wireframe --description 'Render in wireframe instead of solid.'
complete -c splitflap -o fps -o no-fps --description 'Whether to show a frames-per-second display at the bottom of the screen.'

