# spotlight
# Autogenerated from man page /usr/share/man/man6/spotlight.6x.gz
complete -c spotlight -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c spotlight -o root --description 'Draw on the root window.'
complete -c spotlight -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c spotlight -o install --description 'Install a private colormap for the window.'
complete -c spotlight -o visual --description 'Specify which visual to use.'
complete -c spotlight -o delay --description 'Slow it down.'
complete -c spotlight -o duration --description 'How long to run before loading a new image.   Default 120 seconds.'
complete -c spotlight -o radius --description 'Radius of the spotlight in pixels.'
complete -c spotlight -o fps --description 'Display the current frame rate and CPU load.'

