# sproingies
# Autogenerated from man page /usr/share/man/man6/sproingies.6x.gz
complete -c sproingies -o visual --description 'Specify which visual to use.'
complete -c sproingies -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c sproingies -o root --description 'Draw on the root window.'
complete -c sproingies -o count --description 'How many sproingies to draw at once.   Default: 5.'
complete -c sproingies -o delay --description 'Per-frame delay, in microseconds.   Default: 25000 (0. 03 seconds. ).'
complete -c sproingies -o size --description 'How much to scale the image down.   Default 0 (full screen. ).'
complete -c sproingies -o no-fall --description 'Make sproingies "smart", so they do not fall down the edge.'
complete -c sproingies -o wireframe --description 'Render in wireframe instead of solid.'
complete -c sproingies -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

