# stonerview
# Autogenerated from man page /usr/share/man/man6/stonerview.6x.gz
complete -c stonerview -o visual --description 'Specify which visual to use.'
complete -c stonerview -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c stonerview -o root --description 'Draw on the root window.'
complete -c stonerview -o wireframe --description 'Render in wireframe instead of solid.'
complete -c stonerview -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

