# strange
# Autogenerated from man page /usr/share/man/man6/strange.6x.gz
complete -c strange -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c strange -o root --description 'Draw on the root window.'
complete -c strange -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c strange -o install --description 'Install a private colormap for the window.'
complete -c strange -o visual --description 'Specify which visual to use.'
complete -c strange -o ncolors --description 'How many colors should be used (if possible).   Default 100.'
complete -c strange -o fps --description 'Display the current frame rate and CPU load.'

