# strfile
# Autogenerated from man page /usr/share/man/man1/strfile.1.gz
complete -c strfile -s c --description 'Change the delimiting character from the percent sign to  R char .'
complete -c strfile -s i --description 'Ignore case when ordering the strings.'
complete -c strfile -s o --description 'Order the strings in alphabetical order.'
complete -c strfile -s r --description 'Randomize access to the strings.'
complete -c strfile -s s --description 'Run silently; don\'t give a summary message when finished.'
complete -c strfile -s x --description 'Note that each alphabetic character in the groups of lines is rotated 13 posi…'

