# su
# Autogenerated from man page /usr/share/man/man1/su.1.gz
complete -c su -s c -l commandCOMMAND --description 'Specify a command that will be invoked by the shell using its -c.'
complete -c su -s l -l login --description 'Provide an environment similar to what the user would expect had the user log…'
complete -c su -l command --description '.'
complete -c su -o 'c.' --description '.'
complete -c su -s s -l shell --description '.'
complete -c su -l preserve-environment --description 'is used, the shell specified by the $SHELL environment variable.'
complete -c su -s m -s p --description '.'

