# superquadrics
# Autogenerated from man page /usr/share/man/man6/superquadrics.6x.gz
complete -c superquadrics -o visual --description 'Specify which visual to use.'
complete -c superquadrics -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c superquadrics -o root --description 'Draw on the root window.'
complete -c superquadrics -o delay --description 'Per-frame delay, in microseconds.   Default: 40000 (0. 04 seconds. ).'
complete -c superquadrics -o spinspeed --description '0. 1 - 15. 0.   Default: 5. 0.'
complete -c superquadrics -o count --description '0 - 100.   Default: 25.'
complete -c superquadrics -o cycles --description '0 - 100.   Default: 40.'
complete -c superquadrics -o wireframe --description 'Render in wireframe instead of solid.'
complete -c superquadrics -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

