# swirl
# Autogenerated from man page /usr/share/man/man6/swirl.6x.gz
complete -c swirl -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c swirl -o root --description 'Draw on the root window.'
complete -c swirl -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c swirl -o install --description 'Install a private colormap for the window.'
complete -c swirl -o visual --description 'Specify which visual to use.'
complete -c swirl -o ncolors --description 'How many colors should be used (if possible).   Default 200.'
complete -c swirl -o count --description '.'
complete -c swirl -o fps --description 'Display the current frame rate and CPU load.'

