# syslinux-legacy
# Autogenerated from man page /usr/share/man/man1/syslinux-legacy.1.gz
complete -c syslinux-legacy -s s --description 'Install a "safe, slow and stupid" version of syslinux.'
complete -c syslinux-legacy -s f --description 'Force install even if it appears unsafe.'
complete -c syslinux-legacy -s r --description 'RAID mode.'
complete -c syslinux-legacy -s d --description 'Install the \\s-1SYSLINUX\\s+1 control files in a subdirectory with the specifi…'
complete -c syslinux-legacy -o style --description 'any kernel parameters.'
complete -c syslinux-legacy -s o --description 'Indicates that the filesystem is at an offset from the base of the device or …'
complete -c syslinux-legacy -l ---------------------------------------------------- --description '<DLE> = <Ctrl-P> = ASCII 16     No      No      No <DC1> = <Ctrl-Q> = ASCII 1…'

