# systemd-activate
# Autogenerated from man page /usr/share/man/man8/systemd-activate.8.gz
complete -c systemd-activate -s l -l listen --description 'Listen on this address.  Takes a string like "2000" or "127. 0. 0. 1:2001".'
complete -c systemd-activate -s a -l accept --description 'Launch an instance of the service binary for each connection and pass the con…'
complete -c systemd-activate -s d -l datagram --description 'Listen on a datagram socket (SOCK_DGRAM), instead of a stream socket (SOCK_ST…'
complete -c systemd-activate -l seqpacket --description 'Listen on a sequential packet socket (SOCK_SEQPACKET), instead of a stream so…'
complete -c systemd-activate -l inetd --description 'Use the inetd protocol for passing file descriptors, i. e.'
complete -c systemd-activate -s E -l setenv --description 'Add this variable to the environment of the launched process.'
complete -c systemd-activate -l fdname --description 'Specify a name for the activation file descriptors.'
complete -c systemd-activate -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-activate -l version --description 'Print a short version string and exit.'
complete -c systemd-activate -l 'seqpacket.' --description '.'
complete -c systemd-activate -l 'datagram.' --description '.'

