# systemd-socket-proxyd
# Autogenerated from man page /usr/share/man/man8/systemd-socket-proxyd.8.gz
complete -c systemd-socket-proxyd -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-socket-proxyd -l version --description 'Print a short version string and exit.'

