# systemd-bus-proxyd
# Autogenerated from man page /usr/share/man/man8/systemd-bus-proxyd.8.gz
complete -c systemd-bus-proxyd -l address --description 'when that option is given.'
complete -c systemd-bus-proxyd -s h -l help --description '.'
complete -c systemd-bus-proxyd -l version --description '.'

