# systemd-journal-upload
# Autogenerated from man page /usr/share/man/man8/systemd-journal-upload.8.gz
complete -c systemd-journal-upload -s u -l url -l url --description 'Upload to the specified address.'
complete -c systemd-journal-upload -l system -l user --description 'Limit uploaded entries to entries from system services and the kernel, or to …'
complete -c systemd-journal-upload -s m -l merge --description 'Upload entries interleaved from all available journals, including other machi…'
complete -c systemd-journal-upload -s D -l directory --description 'Takes a directory path as argument.'
complete -c systemd-journal-upload -l file --description 'Takes a file glob as an argument.'
complete -c systemd-journal-upload -l cursor --description 'Upload entries from the location in the journal specified by the passed curso…'
complete -c systemd-journal-upload -l after-cursor --description 'Upload entries from the location in the journal after the location specified …'
complete -c systemd-journal-upload -l save-state --description 'Upload entries from the location in the journal after the location specified …'
complete -c systemd-journal-upload -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-journal-upload -l version --description 'Print a short version string and exit.'
complete -c systemd-journal-upload -l 'url.' --description 'OPTIONS.'

