# systemd-resolve
# Autogenerated from man page /usr/share/man/man1/systemd-resolve.1.gz
complete -c systemd-resolve -s 4 -s 6 --description 'By default, when resolving a hostname, both IPv4 and IPv6 addresses are acqui…'
complete -c systemd-resolve -s i -l interface --description 'Specifies the network interface to execute the query on.'
complete -c systemd-resolve -s p -l protocol --description 'Specifies the network protocol for the query.  May be one of "dns" (i. e.'
complete -c systemd-resolve -s t -l type -s c -l class --description 'Specifies the DNS resource record type (e. g.  A, AAAA, MX, . ) and class (e.'
complete -c systemd-resolve -l service --description 'Enables service resolution.'
complete -c systemd-resolve -l service-address --description 'Takes a boolean parameter.'
complete -c systemd-resolve -l service-txt --description 'Takes a boolean parameter.'
complete -c systemd-resolve -l cname --description 'Takes a boolean parameter.'
complete -c systemd-resolve -l search --description 'Takes a boolean parameter.'
complete -c systemd-resolve -l legend --description 'Takes a boolean parameter.'
complete -c systemd-resolve -l statistics --description 'If specified general resolver statistics are shown, including information whe…'
complete -c systemd-resolve -l reset-statistics --description 'Resets the statistics counters shown in --statistics to zero.'
complete -c systemd-resolve -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-resolve -l version --description 'Print a short version string and exit.'

