# systemd-bootchart
# Autogenerated from man page /usr/share/man/man1/systemd-bootchart.1.gz
complete -c systemd-bootchart -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-bootchart -s n -l sample --description 'Specify the number of samples, N, to record.'
complete -c systemd-bootchart -s f -l freq --description 'Specify the sample log frequency, a positive real f, in Hz.'
complete -c systemd-bootchart -s r -l rel --description 'Use relative times instead of absolute times.'
complete -c systemd-bootchart -s F -l no-filter --description 'Disable filtering of tasks that did not contribute significantly to the boot.'
complete -c systemd-bootchart -s C -l cmdline --description 'Display the full command line with arguments of processes, instead of only th…'
complete -c systemd-bootchart -s g -l control-group --description 'Display process control group.'
complete -c systemd-bootchart -s o -l output --description 'Specify the output directory for the graphs.'
complete -c systemd-bootchart -s i -l init --description 'Use this init binary.  Defaults to /lib/systemd/systemd.'
complete -c systemd-bootchart -s p -l pss --description 'Enable logging and graphing of processes\\*(Aq PSS (Proportional Set Size) mem…'
complete -c systemd-bootchart -s e -l entropy --description 'Enable logging and graphing of the kernel random entropy pool size.'
complete -c systemd-bootchart -s x -l scale-x --description 'Horizontal scaling factor for all variable graph components.'
complete -c systemd-bootchart -s y -l scale-y --description 'Vertical scaling factor for all variable graph components.'
complete -c systemd-bootchart -l 'freq.' --description '.'

