# tailf
# Autogenerated from man page /usr/share/man/man1/tailf.1.gz
complete -c tailf -s n -l lines -o number --description 'Output the last  number lines, instead of the last 10.'
complete -c tailf -s V -l version --description 'Display version information and exit.'
complete -c tailf -s h -l help --description 'Display help text and exit.'

