# tbl-dctrl
# Autogenerated from man page /usr/share/man/man1/tbl-dctrl.1.gz
complete -c tbl-dctrl -s d -l delimiter --description 'Instead of drawing nice borders to the table, use the specified  delimiter st…'
complete -c tbl-dctrl -s H -l no-heading --description 'Do not print a table heading (column titles).'
complete -c tbl-dctrl -s l -l errorlevel --description 'Set log level to R level .'
complete -c tbl-dctrl -s V -l version --description 'Print out version information.'
complete -c tbl-dctrl -s C -l copying --description 'Print out the copyright license.'
complete -c tbl-dctrl -s c -l column --description 'switch with a column specification.'
complete -c tbl-dctrl -s h -l help --description 'Print out a help summary.'

