# tessellimage
# Autogenerated from man page /usr/share/man/man6/tessellimage.6x.gz
complete -c tessellimage -o visual --description 'Specify which visual to use.'
complete -c tessellimage -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c tessellimage -o root --description 'Draw on the root window.'
complete -c tessellimage -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds).'
complete -c tessellimage -o duration --description 'Length of time until loading a new image.  Default: 2 minutes.'
complete -c tessellimage -o duration2 --description 'Length of time until increasing or decreasing the triangulation depth.'
complete -c tessellimage -o max-depth --description 'The maximum number of triangles to render.   Default: 40000.'
complete -c tessellimage -o outline -o no-outline --description 'Whether to outline the triangles.'
complete -c tessellimage -o fill-screen -o no-fill-screen --description 'Whether to zoom in on the image to completely fill the screen, or to center i…'
complete -c tessellimage -o fps -o no-fps --description 'Whether to show a frames-per-second display at the bottom of the screen.'

