# thornbird
# Autogenerated from man page /usr/share/man/man6/thornbird.6x.gz
complete -c thornbird -o visual --description 'Specify which visual to use.'
complete -c thornbird -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c thornbird -o root --description 'Draw on the root window.'
complete -c thornbird -o count --description 'Points.   10 - 1000.   Default: 800.'
complete -c thornbird -o cycles --description 'Thickness.   2 - 500.   Default: 16.'
complete -c thornbird -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c thornbird -o ncolors --description 'Number of Colors.   Default: 64.'
complete -c thornbird -o fps --description 'Display the current frame rate and CPU load.'

