# thunderbird
# Autogenerated from man page /usr/share/man/man1/thunderbird.1.gz
complete -c thunderbird -s P --description 'If  no profile is given to the -P option, the profile  manager will pop-up.'

