# tomboy
# Autogenerated from man page /usr/share/man/man1/tomboy.1.gz
complete -c tomboy -l new-note --description 'Create and display a new note.'
complete -c tomboy -l open-note --description 'Display the existing note matching TITLE or URL.'
complete -c tomboy -l note-path --description 'Load/store note data in this directory.'
complete -c tomboy -l start-here --description 'Display the "Start Here" note.'
complete -c tomboy -l panel-applet --description 'Launches Tomboy as a panel applet.'
complete -c tomboy -l search --description 'Searches notes for the specified TEXT and opens the Search All Notes window w…'
complete -c tomboy -l highlight-search --description 'Search and highlight TEXT in the opened note.'
complete -c tomboy -l help --description 'Show summary of options.'
complete -c tomboy -l version --description 'Show version of program.'
complete -c tomboy -l debug --description 'Turn on debugging output.'

