# tracepath6
# Autogenerated from man page /usr/share/man/man8/tracepath6.8.gz
complete -c tracepath6 -s n --description 'Print primarily IP addresses numerically.'
complete -c tracepath6 -s b --description 'Print both of host names and IP addresses.'
complete -c tracepath6 -s l --description 'Sets the initial packet length to pktlen instead of 65535 for tracepath or 12…'
complete -c tracepath6 -o 'm/term>' --description 'Set maximum hops (or maximum TTLs) to max_hops instead of 30.'

