# triangle
# Autogenerated from man page /usr/share/man/man6/triangle.6x.gz
complete -c triangle -o visual --description 'Specify which visual to use.'
complete -c triangle -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c triangle -o root --description 'Draw on the root window.'
complete -c triangle -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. ).'
complete -c triangle -o ncolors --description 'Number of Colors.   Default: 128.'
complete -c triangle -o fps --description 'Display the current frame rate and CPU load.'

