# tronbit
# Autogenerated from man page /usr/share/man/man6/tronbit.6x.gz
complete -c tronbit -o visual --description 'Specify which visual to use.'
complete -c tronbit -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c tronbit -o root --description 'Draw on the root window.'
complete -c tronbit -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c tronbit -o speed --description 'How fast the animation should run.'
complete -c tronbit -o no-spin --description 'Don\'t rotate.'
complete -c tronbit -o no-wander --description 'Don\'t wander around.'
complete -c tronbit -o wireframe --description 'Render in wireframe instead of solid.'
complete -c tronbit -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

