# udisksctl
# Autogenerated from man page /usr/share/man/man1/udisksctl.1.gz
complete -c udisksctl -l 'options.' --description 'suid or dev that would allow the caller to gain additional privileges, are re…'
complete -c udisksctl -l force --description 'can be used to request that the device is unmounted even if active references…'
complete -c udisksctl -l no-user-interaction --description 'can be used to request that no interaction (such as the user being presented …'

