# unknownpleasures
# Autogenerated from man page /usr/share/man/man6/unknownpleasures.6x.gz
complete -c unknownpleasures -o visual --description 'Specify which visual to use.'
complete -c unknownpleasures -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c unknownpleasures -o root --description 'Draw on the root window.'
complete -c unknownpleasures -o delay --description 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. ).'
complete -c unknownpleasures -o speed --description 'Animation speed.  2 for twice as fast, 0. 5 for half as fast.'
complete -c unknownpleasures -o count --description 'Scanlines (vertical resolution).   Default: 80.'
complete -c unknownpleasures -o ortho -o no-ortho --description 'Whether to use an orthographic projection.'
complete -c unknownpleasures -o fps -o no-fps --description 'Whether to show a frames-per-second display at the bottom of the screen.'

