# unwrapdiff
# Autogenerated from man page /usr/share/man/man1/unwrapdiff.1.gz
complete -c unwrapdiff -s v --description 'Verbose operation.'
complete -c unwrapdiff -l help --description 'Display a short usage message.'
complete -c unwrapdiff -l version --description 'Display the version number of unwrapdiff.'
complete -c unwrapdiff -s l --description 'option when applying the patch, in order to ignore any whitespace differences…'

