# update-gconf-defaults
# Autogenerated from man page /usr/share/man/man8/update-gconf-defaults.8.gz
complete -c update-gconf-defaults -l source --description 'Specify an alternate source directory where to find the defaults.'
complete -c update-gconf-defaults -l destination --description 'Specify an alternate destination directory where to build the resulting GConf…'
complete -c update-gconf-defaults -l mandatory --description 'Sets source and destination directories appropriate for the mandatory values.'

