# update-java-alternatives
# Autogenerated from man page /usr/share/man/man8/update-java-alternatives.8.gz
complete -c update-java-alternatives -s l -l list --description 'List all installed packages (or just <jname>) providing information to set a …'
complete -c update-java-alternatives -s a -l auto --description 'Switch all alternatives of registered jre/sdk installations to automatic mode.'
complete -c update-java-alternatives -s s -l set --description 'Set all alternatives of the registered jre/sdk installation to the program pa…'
complete -c update-java-alternatives -l jre --description 'Limit the actions to alternatives belong to a runtime environment, not a deve…'
complete -c update-java-alternatives -l jre-headless --description 'Limit the actions to alternatives belong to the headless part of a runtime en…'
complete -c update-java-alternatives -l plugin --description 'Limit the actions to alternatives providing browser plugins.'
complete -c update-java-alternatives -s h -l help --description 'Display a help message.'
complete -c update-java-alternatives -s v -l verbose --description 'Verbose output.'

