# upstart-file-bridge
# Autogenerated from man page /usr/share/man/man8/upstart-file-bridge.8.gz
complete -c upstart-file-bridge -l daemon --description 'Detach and run in the background. \\".'
complete -c upstart-file-bridge -l debug --description 'Enable debugging output. \\".'
complete -c upstart-file-bridge -l help --description 'Show brief usage summary. \\".'
complete -c upstart-file-bridge -l user --description 'User-session mode: connect to Upstart via the user session rather than over t…'
complete -c upstart-file-bridge -l verbose --description 'Enable verbose output.'

