# upstart-local-bridge
# Autogenerated from man page /usr/share/man/man8/upstart-local-bridge.8.gz
complete -c upstart-local-bridge -l any-user --description 'By default the bridge will only accept connections from clients running under…'
complete -c upstart-local-bridge -l daemon --description 'Detach and run in the background. \\".'
complete -c upstart-local-bridge -l debug --description 'Enable debugging output. \\".'
complete -c upstart-local-bridge -l event --description 'Specify name of event to emit on receipt of a name=value pair. \\".'
complete -c upstart-local-bridge -l help --description 'Show brief usage summary. \\".'
complete -c upstart-local-bridge -l path --description 'Specify path for local/abstract socket to listen on.'
complete -c upstart-local-bridge -l verbose --description 'Enable verbose output.'

