# upstart-event-bridge
# Autogenerated from man page /usr/share/man/man8/upstart-event-bridge.8.gz
complete -c upstart-event-bridge -l daemon --description 'Detach and run in the background. \\".'
complete -c upstart-event-bridge -l debug --description 'Enable debugging output. \\".'
complete -c upstart-event-bridge -l help --description 'Show brief usage summary. \\".'
complete -c upstart-event-bridge -l verbose --description 'Enable verbose output.'

