# ureadahead
# Autogenerated from man page /usr/share/man/man8/ureadahead.8.gz
complete -c ureadahead -l verbose --description 'May be used to report on  ureadahead \'s operation.'
complete -c ureadahead -l daemon --description 'Places  ureadahead into the background once the pack file has been read, or o…'
complete -c ureadahead -l force-trace --description 'Discards all pack files and forces re-tracing. \\".'
complete -c ureadahead -l timeout --description 'Normally when tracing,  ureadahead will wait for a  TERM or  INT signal befor…'
complete -c ureadahead -l dump --description 'Dump the contents of the pack file to standard output in a pretty format, doe…'
complete -c ureadahead -l sort --description 'Used with.'

