# VBoxClient
# Autogenerated from man page /usr/share/man/man1/VBoxClient.1.gz
complete -c VBoxClient -l clipboard --description 'start the shared clipboard service.'
complete -c VBoxClient -l draganddrop --description 'start the drag and drop service.'
complete -c VBoxClient -l display --description 'start the display management service .'
complete -c VBoxClient -l seamless --description 'start the seamless windows service.'
complete -c VBoxClient -l checkhostversion --description '.'
complete -c VBoxClient -s d -l nodaemon --description 'continue running as a system service.'

