# vboxheadless
# Autogenerated from man page /usr/share/man/man1/vboxheadless.1.gz
complete -c vboxheadless -s s -o startvm -l startvm --description 'Start given VM (required argument).'
complete -c vboxheadless -s v -o vrde -l vrde --description 'Enable (default) or disable the VRDE server or don\'t change the setting.'
complete -c vboxheadless -s e -o vrdeproperty -l vrdeproperty --description '"TCP/Ports" - comma-separated list of ports the VRDE server can bind to.'
complete -c vboxheadless -l settingspw --description 'Specify the settings password.'
complete -c vboxheadless -l settingspwfile --description 'Specify a file containing the settings password.'
complete -c vboxheadless -s c -o capture -l capture --description 'Record the VM screen output to a file.'
complete -c vboxheadless -s w -l width --description 'Frame width when recording.'
complete -c vboxheadless -s h -l height --description 'Frame height when recording.'
complete -c vboxheadless -s r -l bitrate --description 'Recording bit rate when recording.'
complete -c vboxheadless -s f -l filename --description 'File name when recording.'

