# veritysetup
# Autogenerated from man page /usr/share/man/man8/veritysetup.8.gz
complete -c veritysetup -l verbose -s v --description 'Print more information on command execution.'
complete -c veritysetup -l debug --description 'Run in debug mode with full diagnostic logs.'
complete -c veritysetup -l no-superblock --description 'Create or use dm-verity without permanent on-disk superblock.'
complete -c veritysetup -l format --description 'Specifies the hash version type.  Format type 0 is original Chrome OS verion.'
complete -c veritysetup -l data-block-size --description 'Used block size for the data device.'
complete -c veritysetup -l hash-block-size --description 'Used block size for the hash device.'
complete -c veritysetup -l data-blocks --description 'Size of data device used in verification.'
complete -c veritysetup -l hash-offset --description 'Offset of hash area/superblock on hash_device.'
complete -c veritysetup -l salt --description 'Salt used for format or verification.  Format is a hexadecimal string.'
complete -c veritysetup -l uuid --description 'Use the provided UUID for format command instead of generating new one.'
complete -c veritysetup -l version --description 'Show the program version.'

