# vermiculate
# Autogenerated from man page /usr/share/man/man6/vermiculate.6x.gz
complete -c vermiculate -o visual --description 'Specify which visual to use.'
complete -c vermiculate -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c vermiculate -o root --description 'Draw on the root window.'
complete -c vermiculate -o fps --description 'Display the current frame rate and CPU load.'

