# vgcfgrestore
# Autogenerated from man page /usr/share/man/man8/vgcfgrestore.8.gz
complete -c vgcfgrestore -s l -l list --description 'List files pertaining to VolumeGroupName List metadata backup and archive fil…'
complete -c vgcfgrestore -s f -l file --description 'Name of LVM metadata backup file Specifies a metadata backup or archive file …'
complete -c vgcfgrestore -l force --description 'Necessary to restore metadata with thin pool volumes.'

