# vgcreate
# Autogenerated from man page /usr/share/man/man8/vgcreate.8.gz
complete -c vgcreate -s c -l clustered --description 'If clustered locking is enabled, this defaults to y indicating that this Volu…'
complete -c vgcreate -s l -l maxlogicalvolumes --description 'Sets the maximum number of logical volumes allowed in this volume group.'
complete -c vgcreate -s p -l maxphysicalvolumes --description 'Sets the maximum number of physical volumes that can belong to this volume gr…'
complete -c vgcreate -l metadataprofile --description 'Uses and attaches the ProfileName configuration profile to the volume group m…'
complete -c vgcreate -s s -l physicalextentsize --description 'Sets the physical extent size on physical volumes of this volume group.'
complete -c vgcreate -l shared --description 'Create a shared VG using lvmlockd.'
complete -c vgcreate -l restorefile -l uuid -l physicalvolumesize --description 'are not available.'
complete -c vgcreate -l systemid --description 'Specifies the system ID that will be given to the new VG, overriding the syst…'
complete -c vgcreate -s f -l force --description '.'
complete -c vgcreate -s y -l yes --description '.'
complete -c vgcreate -s Z -l zero --description '.'
complete -c vgcreate -l labelsector --description '.'
complete -c vgcreate -l metadatasize --description '.'
complete -c vgcreate -l pvmetadatacopies --description '.'
complete -c vgcreate -l dataalignment --description '.'
complete -c vgcreate -l dataalignmentoffset --description 'Examples Creates a volume group named "test_vg" using physical volumes "/dev/…'

