# vgdisplay
# Autogenerated from man page /usr/share/man/man8/vgdisplay.8.gz
complete -c vgdisplay -s A -l activevolumegroups --description 'Only select the active volume groups.'
complete -c vgdisplay -s C -l columns --description 'Display output in columns, the equivalent of vgs(8).'
complete -c vgdisplay -s c -l colon --description 'Generate colon separated output for easier parsing in scripts or programs.  N.'
complete -c vgdisplay -s s -l short --description 'Give a short listing showing the existence of volume groups.'
complete -c vgdisplay -s v -l verbose --description 'Display verbose information containing long listings of physical and logical …'
complete -c vgdisplay -l version --description 'Display version and exit successfully.'

