# vgextend
# Autogenerated from man page /usr/share/man/man8/vgextend.8.gz
complete -c vgextend -l restorefile -l uuid -l physicalvolumesize --description 'are not available.'
complete -c vgextend -s f -l force --description '.'
complete -c vgextend -s y -l yes --description '.'
complete -c vgextend -s Z -l zero --description '.'
complete -c vgextend -l labelsector --description '.'
complete -c vgextend -l metadatasize --description '.'
complete -c vgextend -l metadataignore --description '.'
complete -c vgextend -l pvmetadatacopies --description '.'
complete -c vgextend -l dataalignment --description '.'
complete -c vgextend -l dataalignmentoffset --description 'Examples Extends the existing volume group "vg00" by the new physical volumes…'

