# vgimportclone
# Autogenerated from man page /usr/share/man/man8/vgimportclone.8.gz
complete -c vgimportclone -s n -l basevgname --description 'By default the snapshot VG will be renamed to the original name plus a numeri…'
complete -c vgimportclone -s i -l import --description 'Import exported Volume Groups.'

