# vgimport
# Autogenerated from man page /usr/share/man/man8/vgimport.8.gz
complete -c vgimport -s a -l all --description 'Import all exported Volume Groups.'
complete -c vgimport -l force --description 'Import exported Volume Groups even if there are missing Physical Volumes.'

