# vgmerge
# Autogenerated from man page /usr/share/man/man8/vgmerge.8.gz
complete -c vgmerge -s l -l list --description 'Display merged DestinationVolumeGroupName like vgdisplay -v.'
complete -c vgmerge -s t -l test --description 'Do a test run WITHOUT making any real changes.'

