# vgmknodes
# Autogenerated from man page /usr/share/man/man8/vgmknodes.8.gz
complete -c vgmknodes -l refresh --description 'If any logical volume in the volume group is active, reload its metadata.'

