# vgreduce
# Autogenerated from man page /usr/share/man/man8/vgreduce.8.gz
complete -c vgreduce -s a -l all --description 'Removes all empty physical volumes if none are given on command line.'
complete -c vgreduce -l removemissing --description 'Removes all missing physical volumes from the volume group, if there are no l…'

