# vgremove
# Autogenerated from man page /usr/share/man/man8/vgremove.8.gz
complete -c vgremove -s f -l force --description 'Force the removal of any logical volumes on the volume group without confirma…'
complete -c vgremove -l noudevsync --description 'Disable udev synchronisation.'

