# vgs
# Autogenerated from man page /usr/share/man/man8/vgs.8.gz
complete -c vgs -l all --description 'List all volume groups.   Equivalent to not specifying any volume groups.'
complete -c vgs -l aligned --description 'Use with --separator to align the output columns.'
complete -c vgs -l binary --description 'Use binary values "0" or "1" instead of descriptive literal values for column…'
complete -c vgs -l nameprefixes --description 'Add an "LVM2_" prefix plus the field name to the output.'
complete -c vgs -l noheadings --description 'Suppress the headings line that is normally the first line of output.'
complete -c vgs -l nosuffix --description 'Suppress the suffix on output sizes.'
complete -c vgs -s o -l options --description 'Comma-separated ordered list of columns.'
complete -c vgs -s O -l sort --description 'Comma-separated ordered list of columns to sort by.'
complete -c vgs -l rows --description 'Output columns as rows.'
complete -c vgs -s S -l select --description 'Display only rows that match Selection criteria.'
complete -c vgs -l separator --description 'String to use to separate each column.   Useful if grepping the output.'
complete -c vgs -l unbuffered --description 'Produce output immediately without sorting or aligning the columns properly.'
complete -c vgs -l units --description 'All sizes are output in these units: (h)uman-readable, (b)ytes, (s)ectors, (k…'
complete -c vgs -l unquoted --description 'When used with --nameprefixes, output values in the field=value pairs are not…'

