# vgscan
# Autogenerated from man page /usr/share/man/man8/vgscan.8.gz
complete -c vgscan -l mknodes --description 'Also checks the LVM special files in /dev that are needed for active  logical…'
complete -c vgscan -l cache --description 'Scan devices for LVM physical volumes and volume groups and instruct the lvme…'

