# vgsplit
# Autogenerated from man page /usr/share/man/man8/vgsplit.8.gz
complete -c vgsplit -l alloc --description '.'
complete -c vgsplit -l clustered --description '.'
complete -c vgsplit -l maxlogicalvolumes --description '.'
complete -c vgsplit -l metadatatype --description '.'
complete -c vgsplit -l maxphysicalvolumes --description '.'

