# virtualenv
# Autogenerated from man page /usr/share/man/man1/virtualenv.1.gz
complete -c virtualenv -s h -l help --description 'Show summary of options.'
complete -c virtualenv -l version --description 'Show the version of the program.'
complete -c virtualenv -s v -l verbose --description 'Be more verbose.'
complete -c virtualenv -s q -l quiet --description 'Be less verbose; suppress unimportant output.'
complete -c virtualenv -l clear --description 'Clear out a previously-created virtual Python instance in this location befor…'
complete -c virtualenv -s p -l python --description 'The Python interpreter to use to create the new environment.'
complete -c virtualenv -l no-site-packages --description 'Ignored (the default).'
complete -c virtualenv -l system-site-packages --description 'Give access to the global site-packages modules to the virtual environment.'
complete -c virtualenv -l always-copy --description 'Always copy files rather than symlinking.'
complete -c virtualenv -l unzip-setuptools --description 'Unzip Setuptools when installing it.  This fixes up scripts and makes all .'
complete -c virtualenv -l relocatable --description 'Make an EXISTING virtualenv environment relocatable.'
complete -c virtualenv -l no-setuptools --description 'Do not install setuptools (or pip) in the new virtualenv.'
complete -c virtualenv -l no-pip --description 'Do not install pip in the new virtualenv.'
complete -c virtualenv -l extra-search-dir --description 'Directory to search for setuptools/distribute/pip distributions in.'
complete -c virtualenv -l prompt --description '.'

