# voronoi
# Autogenerated from man page /usr/share/man/man6/voronoi.6x.gz
complete -c voronoi -o visual --description 'Specify which visual to use.'
complete -c voronoi -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c voronoi -o root --description 'Draw on the root window.'
complete -c voronoi -o points --description 'How many points to add each time we zoom in.'
complete -c voronoi -o point-size --description 'How big to draw the stars, in pixels.   0 for no stars.'
complete -c voronoi -o point-speed --description 'How fast the points should wander.'
complete -c voronoi -o point-delay --description 'How quickly to insert new points, when adding.'
complete -c voronoi -o zoom-speed --description 'How fast to zoom in.  Less than 1 for slower, greater than 1 for faster.'
complete -c voronoi -o zoom-delay --description 'Zoom in every this-many seconds.'
complete -c voronoi -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

