# wander
# Autogenerated from man page /usr/share/man/man6/wander.6x.gz
complete -c wander -o visual --description 'Specify which visual to use.'
complete -c wander -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c wander -o root --description 'Draw on the root window.'
complete -c wander -o density --description 'Density.   1 - 30.   Default: 2.'
complete -c wander -o reset --description 'Number of frames before resetting.   Default: 2500000.'
complete -c wander -o length --description 'Number of iterations. 	Default: 25000.'
complete -c wander -o delay --description 'Sustain.   0 - 60.   Default: 1.'
complete -c wander -o circles -o no-circles --description 'Whether to draw spots.'
complete -c wander -o size --description 'Size.   0 - 100.   Default: 1.'
complete -c wander -o advance --description 'Color Contrast.   1 - 100.   Default: 1.'
complete -c wander -o fps --description 'Display the current frame rate and CPU load.'

