# whirlwindwarp
# Autogenerated from man page /usr/share/man/man6/whirlwindwarp.6x.gz
complete -c whirlwindwarp -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c whirlwindwarp -o root --description 'Draw on the root window.'
complete -c whirlwindwarp -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c whirlwindwarp -o install --description 'Install a private colormap for the window.'
complete -c whirlwindwarp -o visual --description 'Specify which visual to use.'
complete -c whirlwindwarp -o points --description 'The number of stars plotted (default 400).'
complete -c whirlwindwarp -o tails --description 'The length of the tail of each star (default 8).'
complete -c whirlwindwarp -o fps --description 'Display the current frame rate and CPU load.'

