# winduprobot
# Autogenerated from man page /usr/share/man/man6/winduprobot.6x.gz
complete -c winduprobot -o visual --description 'Specify which visual to use.'
complete -c winduprobot -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c winduprobot -o root --description 'Draw on the root window.'
complete -c winduprobot -o delay --description 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds).'
complete -c winduprobot -o count --description 'Number of robots.   1 - 100.   Default: 25.'
complete -c winduprobot -o speed --description 'Animation speed.   2. 0 means twice as fast, 0. 5 means half as fast.'
complete -c winduprobot -o size --description 'Robot size.   2. 0 means twice as big, 0. 5 means half as big.'
complete -c winduprobot -o opacity --description 'Robot skin transparency.   0. 0 - 1. 0.   Default: 1. 0.'
complete -c winduprobot -o talk --description 'How often to occasionally pop up a word bubble with random text in it.  0.'
complete -c winduprobot -o texture -o no-texture --description 'Whether the robot\'s surface should be reflective chrome.'
complete -c winduprobot -o fade -o no-fade --description 'Whether to sometimes fade the robot\'s opacity to show the inner mechanism.'
complete -c winduprobot -o fps -o no-fps --description 'Whether to show a frames-per-second display at the bottom of the screen.'

