# wormhole
# Autogenerated from man page /usr/share/man/man6/wormhole.6x.gz
complete -c wormhole -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c wormhole -o root --description 'Draw on the root window.'
complete -c wormhole -o mono --description 'Make all the rocks the same color.'
complete -c wormhole -o install --description 'Install a private colormap for the window.'
complete -c wormhole -o visual --description 'Specify which visual to use.'
complete -c wormhole -o stars --description 'Number of stars to create every animation loop.'
complete -c wormhole -o zspeed --description 'Speed light streaks fly by.'
complete -c wormhole -o delay --description 'Number of microseconds to delay between each frame.'
complete -c wormhole -o fps --description 'Display the current frame rate and CPU load.'

