# x86_64-linux-gnu-ar
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-ar.1.gz
complete -c x86_64-linux-gnu-ar -l help --description 'Displays the list of command line options supported by ar and then exits.'
complete -c x86_64-linux-gnu-ar -l version --description 'Displays the version information of ar and then exits.'

