# xanalogtv
# Autogenerated from man page /usr/share/man/man6/xanalogtv.6x.gz
complete -c xanalogtv -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c xanalogtv -o root --description 'Draw on the root window.'
complete -c xanalogtv -o install --description 'Install a private colormap for the window.'
complete -c xanalogtv -o visual --description 'Specify which visual to use.'
complete -c xanalogtv -o fps --description 'Display the current frame rate and CPU load.'

