# xclip-cutfile
# Autogenerated from man page /usr/share/man/man1/xclip-cutfile.1.gz
complete -c xclip-cutfile -s p --description 'preserve path formation xclip-pastefile pastes the files out of the clipboard…'

