# xed
# Autogenerated from man page /usr/share/man/man1/xed.1.gz
complete -c xed -l display --description 'X display to use.'
complete -c xed -l encoding --description 'Set the character encoding to be used for opening the files listed on the com…'
complete -c xed -l new-window --description 'Create a new toplevel window in an existing instance of xed.'
complete -c xed -l new-document --description 'Create a new document in an existing instance of xed, on the last Xed window …'
complete -c xed -l list-encodings --description 'Display list of possible values for the encoding option and exit.'
complete -c xed -l version --description 'Output version information and exit.'
complete -c xed -s '?' -s h -l help --description 'Print standard command line options.'

