# xflame
# Autogenerated from man page /usr/share/man/man6/xflame.6x.gz
complete -c xflame -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c xflame -o root --description 'Draw on the root window.'
complete -c xflame -o install --description 'Install a private colormap for the window.'
complete -c xflame -o visual --description 'Specify which visual to use.'
complete -c xflame -o foreground -o fg --description 'The color of the flames; default red.   (The background color is always black.'
complete -c xflame -o bitmap --description 'Specifies the bitmap file to use (a monochrome XBM file.'
complete -c xflame -o fps --description 'Display the current frame rate and CPU load.'

