# xmatrix
# Autogenerated from man page /usr/share/man/man6/xmatrix.6x.gz
complete -c xmatrix -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c xmatrix -o root --description 'Draw on the root window.'
complete -c xmatrix -o install --description 'Install a private colormap for the window.'
complete -c xmatrix -o visual --description 'Specify which visual to use.'
complete -c xmatrix -o delay --description 'The delay between steps of the animation, in microseconds: default 10000.'
complete -c xmatrix -o density --description 'The approximate percentage of the screen that should be filled with  characte…'
complete -c xmatrix -o top -o bottom -o both --description 'If -top is specified, the characters will only drop in from the top of the sc…'
complete -c xmatrix -o small -o large --description 'These options specify the sizes of the characters.   The default is -large.'
complete -c xmatrix -o mode --description 'Start off with a representation of a phone number being traced.'
complete -c xmatrix -o phone --description 'The phone number to trace, if -trace is specified.'
complete -c xmatrix -o program --description 'The command to run to generate the text to display.'

