# xplayer-video-thumbnailer
# Autogenerated from man page /usr/share/man/man1/xplayer-video-thumbnailer.1.gz
complete -c xplayer-video-thumbnailer -s j -l jpeg --description 'Switch the output format to \\s-1JPEG\\s0.  The default is \\s-1PNG\\s0.'
complete -c xplayer-video-thumbnailer -s g -l gallery --description 'Output a gallery of the given number (0 is the default) of screenshots.'
complete -c xplayer-video-thumbnailer -s l -l no-limit --description 'Don\'t limit the thumbnailing time to 30 seconds.  For debugging purposes.'

