# xrayswarm
# Autogenerated from man page /usr/share/man/man6/xrayswarm.6x.gz
complete -c xrayswarm -o visual --description 'Specify which visual to use.'
complete -c xrayswarm -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c xrayswarm -o root --description 'Draw on the root window.'
complete -c xrayswarm -o delay --description 'Per-frame delay, in microseconds.   Default: 0 (0. 00 seconds. ).'

