# xscreensaver-getimage-file
# Autogenerated from man page /usr/share/man/man1/xscreensaver-getimage-file.1.gz
complete -c xscreensaver-getimage-file -l verbose --description 'Print diagnostics.'
complete -c xscreensaver-getimage-file -l name --description 'Don\'t load an image: instead just print the file name to stdout.'
complete -c xscreensaver-getimage-file -l no-cache --description 'Update the cache immediately, even if it is not time yet.'

