# xspirograph
# Autogenerated from man page /usr/share/man/man6/xspirograph.6x.gz
complete -c xspirograph -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c xspirograph -o root --description 'Draw on the root window.'
complete -c xspirograph -o install --description 'Install a private colormap for the window.'
complete -c xspirograph -o visual --description 'Specify which visual to use.'
complete -c xspirograph -o delay --description 'The delay between finishing one draw and starting the next.'
complete -c xspirograph -o subdelay --description 'The time to delay between each hundred line draws.'
complete -c xspirograph -o alwaysfinish -o noalwaysfinish --description 'If you want each pattern to draw until it is done, specify the first.'
complete -c xspirograph -o 'window' --description 'Draw on a newly-created window.   This is the default.'
complete -c xspirograph -o 'root' --description 'Draw on the root window.'
complete -c xspirograph -o 'install' --description 'Install a private colormap for the window.'
complete -c xspirograph -o 'noalwaysfinish' --description 'If you want each pattern to draw until it is done, specify the first.'
complete -c xspirograph -o layers --description 'Number of pairs of patterns to draw between each erase.   ENVIRONMENT.'

