# zoom
# Autogenerated from man page /usr/share/man/man6/zoom.6x.gz
complete -c zoom -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c zoom -o root --description 'Draw on the root window.'
complete -c zoom -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c zoom -o install --description 'Install a private colormap for the window.'
complete -c zoom -o visual --description 'Specify which visual to use.'
complete -c zoom -o delay --description 'Slow it down.'
complete -c zoom -o duration --description 'How long to run before loading a new image.   Default 120 seconds.'
complete -c zoom -o lenses --description 'Instead of doing magnification we just copy an offset region from the origina…'
complete -c zoom -o pixwidth --description 'Width of the magnified pixels.'
complete -c zoom -o pixheight --description 'Height of the magnified pixels.'
complete -c zoom -o pixspacex --description 'Amount of black space between magnified pixels (X direction).'
complete -c zoom -o pixspacey --description 'Amount of black space between magnified pixels (Y direction).'
complete -c zoom -o lensoffsetx --description 'Distance in X direction between consecutive copied regions (only effective wh…'
complete -c zoom -o lensoffsety --description 'Distance in Y direction between consecutive copied regions (only effective wh…'

